-- =====================================================================
-- FixMyRide - am_admin schema and seed data
-- Target database : am_admin   (PostgreSQL 18, server "automate")
-- Generated from  : docs/FixMyRide-SRS-HLD-LLD.pdf, section 7.2 (Data design)
--
-- Schema is a faithful port of the LLD tables. SQLite -> PostgreSQL mapping:
--   INTEGER PK AUTOINCREMENT -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--   TEXT                     -> TEXT
--   REAL (money)             -> NUMERIC(10,2)      REAL (rating) -> NUMERIC(2,1)
--   TEXT DEFAULT datetime()  -> TIMESTAMPTZ DEFAULT now()
--   INTEGER 0/1 flags        -> INTEGER (kept as in the LLD, not BOOLEAN)
-- Cross-module columns (mechanic_id in user db, service_request_id in mechanic
-- db, every mirror table in admin db) carry NO foreign key, exactly as the LLD
-- specifies - the three databases stay independently deployable.
--
-- IDs are aligned across all three databases: user #7 is user #7 everywhere,
-- mechanic #12 is mechanic #12 everywhere, and service request #5 is job #5
-- and service_overview #5. This makes the mirrors joinable by hand.
--
-- Contains: admins, managed_users, managed_mechanics, managed_payments, service_overview, job_assignments, system_logs, notifications
-- Each table is seeded with 30 rows. Password for every seeded principal is
-- "password123" (stored as a real bcrypt hash).
--
-- Run with:
--   psql -U postgres -h localhost -d am_admin -f <this file>
-- The script is idempotent: it drops and recreates its own tables.
-- =====================================================================

BEGIN;


-- ---------------------------------------------------------------------
-- 1. SCHEMA
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS job_assignments, service_overview, managed_payments,
                     managed_mechanics, managed_users, system_logs,
                     notifications, admins CASCADE;

CREATE TABLE admins (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL,
    email         TEXT        NOT NULL UNIQUE,
    password_hash TEXT        NOT NULL,
    role          TEXT        NOT NULL DEFAULT 'admin',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Mirror of am_user.users. No FK: a different database owns the source row.
CREATE TABLE managed_users (
    id         INTEGER PRIMARY KEY,
    name       TEXT        NOT NULL,
    email      TEXT        NOT NULL,
    phone      TEXT,
    status     TEXT        NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Mirror of am_mech.mechanics, used for the approval queue.
CREATE TABLE managed_mechanics (
    id              INTEGER PRIMARY KEY,
    name            TEXT        NOT NULL,
    email           TEXT        NOT NULL,
    skills          TEXT,
    available       INTEGER     NOT NULL DEFAULT 1,
    rating          NUMERIC(2,1),
    status          TEXT        NOT NULL DEFAULT 'active',
    approval_status TEXT        DEFAULT 'pending',
    workshop_name   TEXT,
    location        TEXT,
    specialization  TEXT,
    price_from      NUMERIC(10,2),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Reconciliation mirror across both payment ledgers.
CREATE TABLE managed_payments (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id INTEGER,
    user_id            INTEGER,
    user_name          TEXT,
    mechanic_id        INTEGER,
    amount             NUMERIC(10,2),
    method             TEXT,
    status             TEXT,
    transaction_ref    TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE service_overview (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id INTEGER,
    user_id            INTEGER,
    mechanic_id        INTEGER,
    category           TEXT,
    status             TEXT,
    price              NUMERIC(10,2),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Append-only: a reassignment inserts a second row here and overwrites
-- service_overview.mechanic_id, so the assignment history is preserved.
CREATE TABLE job_assignments (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id INTEGER     NOT NULL,
    mechanic_id        INTEGER     NOT NULL,
    assigned_by        INTEGER     NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE system_logs (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_role TEXT        NOT NULL,
    actor_id   INTEGER,
    action     TEXT        NOT NULL,
    detail     TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_role TEXT        NOT NULL,
    recipient_id   INTEGER     NOT NULL,
    title          TEXT        NOT NULL,
    body           TEXT        NOT NULL,
    read           INTEGER     NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes (LLD section 7.2.4)
CREATE INDEX idx_managed_users_email     ON managed_users(email);
CREATE INDEX idx_managed_mechanics_email ON managed_mechanics(email);
CREATE INDEX idx_service_overview_status ON service_overview(status);
CREATE INDEX idx_service_overview_mechanic ON service_overview(mechanic_id);
CREATE INDEX idx_job_assignments_mechanic ON job_assignments(mechanic_id);
CREATE INDEX idx_system_logs_role         ON system_logs(actor_role);
CREATE INDEX idx_notifications_recipient  ON notifications(recipient_role, recipient_id);


-- ---------------------------------------------------------------------
-- 2. SEED DATA (30 rows per table)
-- ---------------------------------------------------------------------


-- admins -----------------------------------------------------------
INSERT INTO admins (id, name, email, password_hash, role, created_at) VALUES
  (1, 'Rohit Ahuja', 'admin@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'superadmin', '2025-08-10 09:13:00+05:30'),
  (2, 'Kavita Menon', 'ops@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'admin', '2025-08-11 09:26:00+05:30'),
  (3, 'Nitin Agarwal', 'nitin.ops@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'admin', '2025-08-12 09:39:00+05:30'),
  (4, 'Shalini Roy', 'shalini.ops@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'admin', '2025-08-13 09:52:00+05:30'),
  (5, 'Vivek Ranjan', 'vivek.support@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'support', '2025-08-14 09:05:00+05:30'),
  (6, 'Preeti Malhotra', 'preeti.support@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'support', '2025-08-15 09:18:00+05:30'),
  (7, 'Amitabh Sinha', 'amitabh.finance@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'finance', '2025-08-16 09:31:00+05:30'),
  (8, 'Renu Bhalla', 'renu.finance@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'finance', '2025-08-17 09:44:00+05:30'),
  (9, 'Sandeep Yadav', 'sandeep.ops@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'admin', '2025-08-18 09:57:00+05:30'),
  (10, 'Nandini Iyer', 'nandini.ops@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'admin', '2025-08-19 09:10:00+05:30'),
  (11, 'Kunal Sharma', 'kunal.support@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'support', '2025-08-20 09:23:00+05:30'),
  (12, 'Aparna Ghosh', 'aparna.support@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'support', '2025-08-21 09:36:00+05:30'),
  (13, 'Rajesh Pillai', 'rajesh.audit@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'auditor', '2025-08-22 09:49:00+05:30'),
  (14, 'Swati Deshmukh', 'swati.audit@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'auditor', '2025-08-23 09:02:00+05:30'),
  (15, 'Mohit Bansal', 'mohit.ops@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'admin', '2025-08-24 09:15:00+05:30'),
  (16, 'Leela Krishnan', 'leela.ops@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'admin', '2025-08-25 09:28:00+05:30'),
  (17, 'Tarun Gill', 'tarun.support@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'support', '2025-08-26 09:41:00+05:30'),
  (18, 'Bhavna Shah', 'bhavna.support@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'support', '2025-08-27 09:54:00+05:30'),
  (19, 'Devansh Rai', 'devansh.finance@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'finance', '2025-08-28 09:07:00+05:30'),
  (20, 'Sunita Rathi', 'sunita.finance@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'finance', '2025-08-29 09:20:00+05:30'),
  (21, 'Alok Nanda', 'alok.ops@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'admin', '2025-08-30 09:33:00+05:30'),
  (22, 'Ruchi Kalra', 'ruchi.ops@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'admin', '2025-08-31 09:46:00+05:30'),
  (23, 'Pranav Kulkarni', 'pranav.support@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'support', '2025-09-01 09:59:00+05:30'),
  (24, 'Madhuri Patil', 'madhuri.support@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'support', '2025-09-02 09:12:00+05:30'),
  (25, 'Sanjay Grover', 'sanjay.audit@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'auditor', '2025-09-03 09:25:00+05:30'),
  (26, 'Ekta Chopra', 'ekta.audit@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'auditor', '2025-09-04 09:38:00+05:30'),
  (27, 'Hemant Vora', 'hemant.ops@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'admin', '2025-09-05 09:51:00+05:30'),
  (28, 'Nisha Fernandes', 'nisha.ops@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'admin', '2025-09-06 09:04:00+05:30'),
  (29, 'Abhijit Sarkar', 'abhijit.support@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'support', '2025-09-07 09:17:00+05:30'),
  (30, 'Geeta Ramanathan', 'geeta.finance@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', 'finance', '2025-09-08 09:30:00+05:30');


-- managed_users (mirror of am_user.users) ---------------------------
INSERT INTO managed_users (id, name, email, phone, status, created_at) VALUES
  (1, 'Aarav Sharma', 'aarav@example.com', '+91 9820114455', 'active', '2025-10-10 11:17:00+05:30'),
  (2, 'Priya Nair', 'priya@example.com', '+91 9945228877', 'active', '2025-10-12 11:34:00+05:30'),
  (3, 'Rohan Mehta', 'rohan@example.com', '+91 9871304562', 'active', '2025-10-14 11:51:00+05:30'),
  (4, 'Sneha Iyer', 'sneha@example.com', '+91 9884451209', 'active', '2025-10-16 11:08:00+05:30'),
  (5, 'Vikas Gupta', 'vikas@example.com', '+91 9313778420', 'active', '2025-10-18 11:25:00+05:30'),
  (6, 'Ananya Rao', 'ananya@example.com', '+91 9848012765', 'active', '2025-10-20 11:42:00+05:30'),
  (7, 'Karthik Menon', 'karthik@example.com', '+91 9995567012', 'active', '2025-10-22 11:59:00+05:30'),
  (8, 'Divya Joshi', 'divya@example.com', '+91 9822045518', 'active', '2025-10-24 11:16:00+05:30'),
  (9, 'Rahul Verma', 'rahul@example.com', '+91 9829116374', 'active', '2025-10-26 11:33:00+05:30'),
  (10, 'Meera Pillai', 'meera@example.com', '+91 9846702233', 'active', '2025-10-28 11:50:00+05:30'),
  (11, 'Siddharth Bose', 'siddharth@example.com', '+91 9830559140', 'active', '2025-10-30 11:07:00+05:30'),
  (12, 'Neha Kulkarni', 'neha@example.com', '+91 9767881203', 'active', '2025-11-01 11:24:00+05:30'),
  (13, 'Arjun Desai', 'arjun@example.com', '+91 9825334671', 'suspended', '2025-11-03 11:41:00+05:30'),
  (14, 'Pooja Reddy', 'pooja@example.com', '+91 9701245538', 'active', '2025-11-05 11:58:00+05:30'),
  (15, 'Manish Tiwari', 'manish@example.com', '+91 9335067712', 'active', '2025-11-07 11:15:00+05:30'),
  (16, 'Ritu Chauhan', 'ritu@example.com', '+91 9812440096', 'active', '2025-11-09 11:32:00+05:30'),
  (17, 'Aditya Ghosh', 'aditya@example.com', '+91 9831762204', 'active', '2025-11-11 11:49:00+05:30'),
  (18, 'Kavya Krishnan', 'kavya@example.com', '+91 9880453317', 'active', '2025-11-13 11:06:00+05:30'),
  (19, 'Nikhil Bhatt', 'nikhil@example.com', '+91 9426110583', 'inactive', '2025-11-15 11:23:00+05:30'),
  (20, 'Shreya Sen', 'shreya@example.com', '+91 9836229140', 'active', '2025-11-17 11:40:00+05:30'),
  (21, 'Varun Malhotra', 'varun@example.com', '+91 9811337425', 'active', '2025-11-19 11:57:00+05:30'),
  (22, 'Ishita Banerjee', 'ishita@example.com', '+91 9007745612', 'active', '2025-11-21 11:14:00+05:30'),
  (23, 'Rajat Kapoor', 'rajat@example.com', '+91 9910228456', 'active', '2025-11-23 11:31:00+05:30'),
  (24, 'Tanvi Shetty', 'tanvi@example.com', '+91 9820667139', 'active', '2025-11-25 11:48:00+05:30'),
  (25, 'Harsh Vardhan', 'harsh@example.com', '+91 9450113378', 'active', '2025-11-27 11:05:00+05:30'),
  (26, 'Lakshmi Narayan', 'lakshmi@example.com', '+91 9840556728', 'suspended', '2025-11-29 11:22:00+05:30'),
  (27, 'Gaurav Saxena', 'gaurav@example.com', '+91 9755201194', 'active', '2025-12-01 11:39:00+05:30'),
  (28, 'Anjali Dubey', 'anjali@example.com', '+91 9822774510', 'active', '2025-12-03 11:56:00+05:30'),
  (29, 'Sameer Qureshi', 'sameer@example.com', '+91 9769334081', 'inactive', '2025-12-05 11:13:00+05:30'),
  (30, 'Deepa Chandran', 'deepa@example.com', '+91 9847220165', 'active', '2025-12-07 11:30:00+05:30');


-- managed_mechanics (approval queue mirror of am_mech.mechanics) ----
INSERT INTO managed_mechanics (id, name, email, skills, available, rating, status,
                               approval_status, workshop_name, location,
                               specialization, price_from, created_at) VALUES
  (1, 'Vikram Singh', 'vikram@example.com', 'Engine diagnostics, timing belt, head gasket', 1, 4.8, 'active', 'approved', 'Singh Auto Works', 'Andheri East, Mumbai', 'Engine Overhaul', 1800, '2025-09-10 10:31:00+05:30'),
  (2, 'Imran Khan', 'imran@example.com', 'Disc brakes, ABS, shock absorbers', 1, 4.6, 'active', 'approved', 'Khan Motor Garage', 'Koramangala, Bengaluru', 'Brake and Suspension', 1200, '2025-09-12 10:02:00+05:30'),
  (3, 'Suresh Yadav', 'suresh@example.com', 'Oil change, filters, general service', 1, 4.7, 'active', 'approved', 'Yadav Service Point', 'Lajpat Nagar, New Delhi', 'Periodic Service', 900, '2025-09-14 10:33:00+05:30'),
  (4, 'Ramesh Patel', 'ramesh@example.com', 'Clutch, gearbox, CVT service', 1, 4.5, 'active', 'approved', 'Patel Auto Care', 'Satellite, Ahmedabad', 'Transmission', 2200, '2025-09-16 10:04:00+05:30'),
  (5, 'Balaji Naidu', 'balaji@example.com', 'Wiring, alternator, ECU scan', 1, 4.4, 'active', 'approved', 'Naidu Electricals', 'Velachery, Chennai', 'Auto Electricals', 800, '2025-09-18 10:35:00+05:30'),
  (6, 'Farhan Sheikh', 'farhan@example.com', 'Compressor, gas refill, cooling coil', 1, 4.6, 'active', 'approved', 'Sheikh Cool Care', 'Kurla West, Mumbai', 'AC Service', 1100, '2025-09-20 10:06:00+05:30'),
  (7, 'Dinesh Kumar', 'dinesh@example.com', 'Tyre fitting, balancing, alignment', 1, 4.3, 'active', 'approved', 'Kumar Tyre House', 'Madhapur, Hyderabad', 'Tyres and Alignment', 700, '2025-09-22 10:37:00+05:30'),
  (8, 'Prakash Jha', 'prakash@example.com', 'Body repair, spray paint, polish', 0, 4.5, 'active', 'approved', 'Jha Body Shop', 'Behala, Kolkata', 'Denting and Painting', 2500, '2025-09-24 10:08:00+05:30'),
  (9, 'Ajay Thakur', 'ajay@example.com', 'Turbo repair, injector cleaning', 1, 4.7, 'active', 'approved', 'Thakur Motors', 'Hadapsar, Pune', 'Engine Overhaul', 1900, '2025-09-26 10:39:00+05:30'),
  (10, 'Mohan Das', 'mohan@example.com', 'Multi-brand service, inspection', 1, 4.4, 'active', 'approved', 'Das Auto Point', 'Edappally, Kochi', 'Periodic Service', 850, '2025-09-28 10:10:00+05:30'),
  (11, 'Irfan Ali', 'irfan@example.com', 'Brake pads, strut replacement', 1, 4.5, 'active', 'approved', 'Ali Auto Garage', 'Okhla, New Delhi', 'Brake and Suspension', 1150, '2025-09-30 10:41:00+05:30'),
  (12, 'Sunil Rawat', 'sunil@example.com', 'Battery, starter motor, jump start', 1, 4.2, 'active', 'approved', 'Rawat Power Works', 'Sector 63, Noida', 'Battery and Starter', 600, '2025-10-02 10:12:00+05:30'),
  (13, 'Kiran Kamble', 'kiran@example.com', 'Headlamps, sensors, fuse box', 1, 4.3, 'active', 'approved', 'Kamble Electricals', 'Kothrud, Pune', 'Auto Electricals', 750, '2025-10-04 10:43:00+05:30'),
  (14, 'Naveen Reddy', 'naveen@example.com', 'Automatic gearbox, clutch plate', 1, 4.8, 'active', 'approved', 'Reddy Transmission', 'Kondapur, Hyderabad', 'Transmission', 2300, '2025-10-06 10:14:00+05:30'),
  (15, 'Zubair Ahmed', 'zubair@example.com', 'Dent removal, full body paint', 0, 4.4, 'active', 'approved', 'Ahmed Auto Body', 'Park Circus, Kolkata', 'Denting and Painting', 2400, '2025-10-08 10:45:00+05:30'),
  (16, 'Santosh Pawar', 'santosh@example.com', 'Cylinder head, coolant system', 1, 4.6, 'active', 'approved', 'Pawar Engine Works', 'Wakad, Pune', 'Engine Overhaul', 2000, '2025-10-10 10:16:00+05:30'),
  (17, 'Rakesh Yadav', 'rakesh@example.com', 'Scheduled service, fluid top-up', 1, 4.5, 'active', 'approved', 'Yadav Car Care', 'Gomti Nagar, Lucknow', 'Periodic Service', 880, '2025-10-12 10:47:00+05:30'),
  (18, 'Vinod Chauhan', 'vinod@example.com', 'Wheel balancing, puncture repair', 1, 4.1, 'active', 'approved', 'Chauhan Tyres', 'Sector 22, Chandigarh', 'Tyres and Alignment', 680, '2025-10-14 10:18:00+05:30'),
  (19, 'Bhaskar Rao', 'bhaskar@example.com', 'Brake overhaul, suspension bush', 1, 4.7, 'active', 'approved', 'Rao Auto Service', 'HSR Layout, Bengaluru', 'Brake and Suspension', 1250, '2025-10-16 10:49:00+05:30'),
  (20, 'Jitendra Mishra', 'jitendra@example.com', 'AC servicing, blower repair', 1, 4.3, 'active', 'approved', 'Mishra Cool Point', 'MP Nagar, Bhopal', 'AC Service', 1050, '2025-10-18 10:20:00+05:30'),
  (21, 'Salim Ansari', 'salim@example.com', 'Central locking, power windows', 1, 4.4, 'active', 'approved', 'Ansari Auto Elec', 'Byculla, Mumbai', 'Auto Electricals', 720, '2025-10-20 10:51:00+05:30'),
  (22, 'Girish Hegde', 'girish@example.com', 'Preventive maintenance, diagnostics', 1, 4.9, 'active', 'approved', 'Hegde Auto Studio', 'Jayanagar, Bengaluru', 'Periodic Service', 920, '2025-10-22 10:22:00+05:30'),
  (23, 'Mahesh Solanki', 'mahesh@example.com', 'Battery swap, charging system', 0, 4.2, 'active', 'approved', 'Solanki Battery Hub', 'Maninagar, Ahmedabad', 'Battery and Starter', 620, '2025-10-24 10:53:00+05:30'),
  (24, 'Ravi Shankar', 'ravi@example.com', 'Piston rings, valve job', 1, 4.6, 'active', 'approved', 'Shankar Engine Care', 'Guindy, Chennai', 'Engine Overhaul', 2100, '2025-10-26 10:24:00+05:30'),
  (25, 'Tushar Gaikwad', 'tushar@example.com', 'Panel beating, alloy refurb', 1, 4.5, 'active', 'approved', 'Gaikwad Body Works', 'Pimpri, Pune', 'Denting and Painting', 2350, '2025-10-28 10:55:00+05:30'),
  (26, 'Pankaj Bisht', 'pankaj@example.com', 'Brake fluid, coil spring', 1, 4.4, 'active', 'approved', 'Bisht Auto Garage', 'Sector 45, Gurugram', 'Brake and Suspension', 1180, '2025-10-30 10:26:00+05:30'),
  (27, 'Arif Mansoor', 'arif@example.com', 'Condenser, evaporator cleaning', 1, 4.3, 'active', 'approved', 'Mansoor Auto Cool', 'Mira Road, Mumbai', 'AC Service', 1080, '2025-11-01 10:57:00+05:30'),
  (28, 'Yogesh Barot', 'yogesh@example.com', 'Alignment, camber correction', 0, 4.2, 'active', 'pending', 'Barot Wheel Care', 'Bopal, Ahmedabad', 'Tyres and Alignment', 690, '2025-11-03 10:28:00+05:30'),
  (29, 'Devendra Rathore', 'devendra@example.com', 'Manual gearbox, differential', 0, 4.5, 'active', 'pending', 'Rathore Gear Works', 'Vaishali Nagar, Jaipur', 'Transmission', 2150, '2025-11-05 10:59:00+05:30'),
  (30, 'Chetan Bhagwat', 'chetan@example.com', 'Full service, road-test check', 0, 4.6, 'suspended', 'rejected', 'Bhagwat Auto Point', 'Dharampeth, Nagpur', 'Periodic Service', 870, '2025-11-07 10:30:00+05:30');


-- managed_payments (reconciliation view over both ledgers) ----------
INSERT INTO managed_payments (id, service_request_id, user_id, user_name, mechanic_id,
                              amount, method, status, transaction_ref, created_at) VALUES
  (1, 1, 1, 'Aarav Sharma', 3, 8075.0, 'upi', 'paid', 'TXNUPI40007', '2026-01-09 16:11:00+05:30'),
  (2, 2, 2, 'Priya Nair', 7, 3136.0, 'card', 'paid', 'TXNCAR40014', '2026-01-16 16:22:00+05:30'),
  (3, 3, 3, 'Rohan Mehta', 1, 2424.0, 'netbanking', 'paid', 'TXNNET40021', '2026-01-23 16:33:00+05:30'),
  (4, 4, 4, 'Sneha Iyer', 12, 5824.0, 'cash', 'paid', 'TXNCAS40028', '2026-01-30 16:44:00+05:30'),
  (5, 5, 5, 'Vikas Gupta', 5, 4066.0, 'upi', 'paid', 'TXNUPI40035', '2026-02-06 16:55:00+05:30'),
  (6, 6, 6, 'Ananya Rao', 3, 9114.0, 'card', 'paid', 'TXNCAR40042', '2026-02-13 16:06:00+05:30'),
  (7, 7, 7, 'Karthik Menon', 18, 6144.0, 'upi', 'paid', 'TXNUPI40049', '2026-02-20 16:17:00+05:30'),
  (8, 8, 8, 'Divya Joshi', 9, 2871.0, 'netbanking', 'paid', 'TXNNET40056', '2026-02-27 16:28:00+05:30'),
  (9, 9, 9, 'Rahul Verma', 1, 11730.0, 'card', 'failed', 'TXNCAR40063', '2026-03-06 16:39:00+05:30'),
  (10, 10, 10, 'Meera Pillai', 22, 5460.0, 'upi', 'paid', 'TXNUPI40070', '2026-03-13 16:50:00+05:30'),
  (11, 11, 11, 'Siddharth Bose', 7, 7992.0, 'cash', 'paid', 'TXNCAS40077', '2026-03-20 16:01:00+05:30'),
  (12, 12, 12, 'Neha Kulkarni', 14, 1504.0, 'upi', 'paid', 'TXNUPI40084', '2026-03-27 16:12:00+05:30'),
  (13, 13, 13, 'Arjun Desai', 2, 8245.0, 'card', 'paid', 'TXNCAR40091', '2026-04-03 16:23:00+05:30'),
  (14, 14, 14, 'Pooja Reddy', 25, 3200.0, 'upi', 'paid', 'TXNUPI40098', '2026-04-10 16:34:00+05:30'),
  (15, 15, 15, 'Manish Tiwari', 11, 2472.0, 'netbanking', 'paid', 'TXNNET40105', '2026-04-17 16:45:00+05:30'),
  (16, 16, 16, 'Ritu Chauhan', 3, 5936.0, 'upi', 'paid', 'TXNUPI40112', '2026-04-24 16:56:00+05:30'),
  (17, 17, 17, 'Aditya Ghosh', 8, 3496.0, 'card', 'refunded', 'TXNCAR40119', '2026-05-01 16:07:00+05:30'),
  (18, 18, 18, 'Kavya Krishnan', 19, 9310.0, 'cash', 'paid', 'TXNCAS40126', '2026-05-08 16:18:00+05:30'),
  (19, 19, 19, 'Nikhil Bhatt', 5, 6272.0, 'upi', 'paid', 'TXNUPI40133', '2026-05-15 16:29:00+05:30'),
  (20, 20, 20, 'Shreya Sen', 27, 2929.0, 'card', 'paid', 'TXNCAR40140', '2026-05-22 16:40:00+05:30'),
  (21, 21, 21, 'Varun Malhotra', 13, 11960.0, 'netbanking', 'paid', 'TXNNET40147', '2026-05-29 16:51:00+05:30'),
  (22, 22, 22, 'Ishita Banerjee', 1, 5564.0, 'upi', 'paid', 'TXNUPI40154', '2026-06-05 16:02:00+05:30'),
  (23, 23, 23, 'Rajat Kapoor', 30, 6882.0, 'card', 'paid', 'TXNCAR40161', '2026-06-12 16:13:00+05:30'),
  (24, 24, 24, 'Tanvi Shetty', 16, 1536.0, 'upi', 'paid', 'TXNUPI40168', '2026-06-19 16:24:00+05:30'),
  (25, 25, 25, 'Harsh Vardhan', 7, 8415.0, 'cash', 'paid', 'TXNCAS40175', '2026-06-26 16:35:00+05:30'),
  (26, 26, 26, 'Lakshmi Narayan', 4, 3264.0, 'upi', 'pending', 'TXNUPI40182', '2026-07-03 16:46:00+05:30'),
  (27, 27, 27, 'Gaurav Saxena', 21, 2520.0, 'card', 'pending', 'TXNCAR40189', '2026-07-10 16:57:00+05:30'),
  (28, 28, 28, 'Anjali Dubey', 9, 6048.0, 'upi', 'pending', 'TXNUPI40196', '2026-07-17 16:08:00+05:30'),
  (29, 29, 29, 'Sameer Qureshi', 26, 3572.0, 'netbanking', 'pending', 'TXNNET40203', '2026-07-24 16:19:00+05:30'),
  (30, 30, 30, 'Deepa Chandran', 12, 9506.0, 'cash', 'pending', 'TXNCAS40210', '2026-07-31 16:30:00+05:30');


-- service_overview (mirror of am_user.service_requests) -------------
INSERT INTO service_overview (id, service_request_id, user_id, mechanic_id,
                              category, status, price, created_at) VALUES
  (1, 1, 1, 3, 'Engine Repair', 'completed', 8075.0, '2026-01-06 09:13:00+05:30'),
  (2, 2, 2, 7, 'Brake Service', 'completed', 3136.0, '2026-01-13 09:26:00+05:30'),
  (3, 3, 3, 1, 'Oil Change', 'completed', 2424.0, '2026-01-20 09:39:00+05:30'),
  (4, 4, 4, 12, 'Battery Replacement', 'completed', 5824.0, '2026-01-27 09:52:00+05:30'),
  (5, 5, 5, 5, 'AC Service', 'completed', 4066.0, '2026-02-03 09:05:00+05:30'),
  (6, 6, 6, 3, 'Tyre Replacement', 'completed', 9114.0, '2026-02-10 09:18:00+05:30'),
  (7, 7, 7, 18, 'Suspension Work', 'completed', 6144.0, '2026-02-17 09:31:00+05:30'),
  (8, 8, 8, 9, 'Electrical Diagnostics', 'completed', 2871.0, '2026-02-24 09:44:00+05:30'),
  (9, 9, 9, 1, 'Clutch Repair', 'completed', 11730.0, '2026-03-03 09:57:00+05:30'),
  (10, 10, 10, 22, 'Periodic Service', 'completed', 5460.0, '2026-03-10 09:10:00+05:30'),
  (11, 11, 11, 7, 'Denting and Painting', 'completed', 7992.0, '2026-03-17 09:23:00+05:30'),
  (12, 12, 12, 14, 'Wheel Alignment', 'completed', 1504.0, '2026-03-24 09:36:00+05:30'),
  (13, 13, 13, 2, 'Engine Repair', 'completed', 8245.0, '2026-03-31 09:49:00+05:30'),
  (14, 14, 14, 25, 'Brake Service', 'completed', 3200.0, '2026-04-07 09:02:00+05:30'),
  (15, 15, 15, 11, 'Oil Change', 'completed', 2472.0, '2026-04-14 09:15:00+05:30'),
  (16, 16, 16, 3, 'Battery Replacement', 'completed', 5936.0, '2026-04-21 09:28:00+05:30'),
  (17, 17, 17, 8, 'AC Service', 'completed', 3496.0, '2026-04-28 09:41:00+05:30'),
  (18, 18, 18, 19, 'Tyre Replacement', 'completed', 9310.0, '2026-05-05 09:54:00+05:30'),
  (19, 19, 19, 5, 'Suspension Work', 'completed', 6272.0, '2026-05-12 09:07:00+05:30'),
  (20, 20, 20, 27, 'Electrical Diagnostics', 'completed', 2929.0, '2026-05-19 09:20:00+05:30'),
  (21, 21, 21, 13, 'Clutch Repair', 'completed', 11960.0, '2026-05-26 09:33:00+05:30'),
  (22, 22, 22, 1, 'Periodic Service', 'completed', 5564.0, '2026-06-02 09:46:00+05:30'),
  (23, 23, 23, 30, 'Denting and Painting', 'completed', 6882.0, '2026-06-09 09:59:00+05:30'),
  (24, 24, 24, 16, 'Wheel Alignment', 'completed', 1536.0, '2026-06-16 09:12:00+05:30'),
  (25, 25, 25, 7, 'Engine Repair', 'completed', 8415.0, '2026-06-23 09:25:00+05:30'),
  (26, 26, 26, 4, 'Brake Service', 'in_progress', 3264.0, '2026-06-30 09:38:00+05:30'),
  (27, 27, 27, 21, 'Oil Change', 'in_progress', 2520.0, '2026-07-07 09:51:00+05:30'),
  (28, 28, 28, 9, 'Battery Replacement', 'accepted', 6048.0, '2026-07-14 09:04:00+05:30'),
  (29, 29, 29, 26, 'AC Service', 'assigned', 3572.0, '2026-07-21 09:17:00+05:30'),
  (30, 30, 30, 12, 'Tyre Replacement', 'pending', NULL, '2026-07-28 09:30:00+05:30');


-- job_assignments (append-only assignment history) ------------------
-- Requests 1-29 were dispatched; request 30 is still 'pending' so it has
-- no row yet. Request 11 was reassigned after the first workshop fell
-- through, so it carries two rows - the superseded dispatch and the one
-- that stuck. service_overview.mechanic_id for request 11 matches the
-- later row; the earlier row survives only here. That is the whole point
-- of keeping this table append-only.
INSERT INTO job_assignments (id, service_request_id, mechanic_id, assigned_by, created_at) VALUES
  (1, 1, 3, 1, '2026-01-06 10:19:00+05:30'),
  (2, 2, 7, 2, '2026-01-13 10:38:00+05:30'),
  (3, 3, 1, 3, '2026-01-20 10:57:00+05:30'),
  (4, 4, 12, 4, '2026-01-27 10:16:00+05:30'),
  (5, 5, 5, 5, '2026-02-03 10:35:00+05:30'),
  (6, 6, 3, 6, '2026-02-10 10:54:00+05:30'),
  (7, 7, 18, 7, '2026-02-17 10:13:00+05:30'),
  (8, 8, 9, 8, '2026-02-24 10:32:00+05:30'),
  (9, 9, 1, 9, '2026-03-03 10:51:00+05:30'),
  (10, 10, 22, 10, '2026-03-10 10:10:00+05:30'),
  (11, 11, 13, 1, '2026-03-17 10:29:00+05:30'),
  (12, 12, 14, 2, '2026-03-24 10:48:00+05:30'),
  (13, 13, 2, 3, '2026-03-31 10:07:00+05:30'),
  (14, 14, 25, 4, '2026-04-07 10:26:00+05:30'),
  (15, 15, 11, 5, '2026-04-14 10:45:00+05:30'),
  (16, 16, 3, 6, '2026-04-21 10:04:00+05:30'),
  (17, 17, 8, 7, '2026-04-28 10:23:00+05:30'),
  (18, 18, 19, 8, '2026-05-05 10:42:00+05:30'),
  (19, 19, 5, 9, '2026-05-12 10:01:00+05:30'),
  (20, 20, 27, 10, '2026-05-19 10:20:00+05:30'),
  (21, 21, 13, 1, '2026-05-26 10:39:00+05:30'),
  (22, 22, 1, 2, '2026-06-02 10:58:00+05:30'),
  (23, 23, 30, 3, '2026-06-09 10:17:00+05:30'),
  (24, 24, 16, 4, '2026-06-16 10:36:00+05:30'),
  (25, 25, 7, 5, '2026-06-23 10:55:00+05:30'),
  (26, 26, 4, 6, '2026-06-30 10:14:00+05:30'),
  (27, 27, 21, 7, '2026-07-07 10:33:00+05:30'),
  (28, 28, 9, 8, '2026-07-14 10:52:00+05:30'),
  (29, 29, 26, 9, '2026-07-21 10:11:00+05:30'),
  (30, 11, 7, 3, '2026-03-18 11:25:00+05:30');


-- system_logs ------------------------------------------------------
INSERT INTO system_logs (id, actor_role, actor_id, action, detail, created_at) VALUES
  (1, 'admin', 1, 'Approved mechanic profile', 'Workshop Yadav Service Point verified and approved for listing.', '2026-01-09 15:53:00+05:30'),
  (2, 'admin', 2, 'Assigned service request', 'Request FMR-2026-1002 dispatched to Dinesh Kumar.', '2026-01-16 15:46:00+05:30'),
  (3, 'admin', 3, 'Reassigned service request', 'Request FMR-2026-1003 moved to Vikram Singh after a delay.', '2026-01-23 15:39:00+05:30'),
  (4, 'admin', 4, 'Suspended user account', 'Account for Sneha Iyer suspended after repeated no-shows.', '2026-01-30 15:32:00+05:30'),
  (5, 'admin', 5, 'Resolved reported issue', 'Issue raised on FMR-2026-1005 closed after workshop response.', '2026-02-06 15:25:00+05:30'),
  (6, 'mechanic', 3, 'Updated job status', 'Suresh Yadav marked FMR-2026-1006 as complete.', '2026-02-13 15:18:00+05:30'),
  (7, 'user', 7, 'Raised service request', 'Karthik Menon booked FMR-2026-1007.', '2026-02-20 15:11:00+05:30'),
  (8, 'user', 8, 'Cancelled booking', 'Divya Joshi cancelled FMR-2026-1008 before dispatch.', '2026-02-27 15:04:00+05:30'),
  (9, 'admin', 9, 'Processed refund', 'Refund issued against FMR-2026-1009 after a service complaint.', '2026-03-06 15:57:00+05:30'),
  (10, 'admin', 10, 'Exported payment report', 'Monthly reconciliation report generated for finance.', '2026-03-13 15:50:00+05:30'),
  (11, 'admin', 1, 'Approved mechanic profile', 'Workshop Kumar Tyre House verified and approved for listing.', '2026-03-20 15:43:00+05:30'),
  (12, 'admin', 2, 'Assigned service request', 'Request FMR-2026-1012 dispatched to Naveen Reddy.', '2026-03-27 15:36:00+05:30'),
  (13, 'admin', 3, 'Reassigned service request', 'Request FMR-2026-1013 moved to Imran Khan after a delay.', '2026-04-03 15:29:00+05:30'),
  (14, 'admin', 4, 'Suspended user account', 'Account for Pooja Reddy suspended after repeated no-shows.', '2026-04-10 15:22:00+05:30'),
  (15, 'admin', 5, 'Resolved reported issue', 'Issue raised on FMR-2026-1015 closed after workshop response.', '2026-04-17 15:15:00+05:30'),
  (16, 'mechanic', 3, 'Updated job status', 'Suresh Yadav marked FMR-2026-1016 as complete.', '2026-04-24 15:08:00+05:30'),
  (17, 'user', 17, 'Raised service request', 'Aditya Ghosh booked FMR-2026-1017.', '2026-05-01 15:01:00+05:30'),
  (18, 'user', 18, 'Cancelled booking', 'Kavya Krishnan cancelled FMR-2026-1018 before dispatch.', '2026-05-08 15:54:00+05:30'),
  (19, 'admin', 9, 'Processed refund', 'Refund issued against FMR-2026-1019 after a service complaint.', '2026-05-15 15:47:00+05:30'),
  (20, 'admin', 10, 'Exported payment report', 'Monthly reconciliation report generated for finance.', '2026-05-22 15:40:00+05:30'),
  (21, 'admin', 1, 'Approved mechanic profile', 'Workshop Kamble Electricals verified and approved for listing.', '2026-05-29 15:33:00+05:30'),
  (22, 'admin', 2, 'Assigned service request', 'Request FMR-2026-1022 dispatched to Vikram Singh.', '2026-06-05 15:26:00+05:30'),
  (23, 'admin', 3, 'Reassigned service request', 'Request FMR-2026-1023 moved to Chetan Bhagwat after a delay.', '2026-06-12 15:19:00+05:30'),
  (24, 'admin', 4, 'Suspended user account', 'Account for Tanvi Shetty suspended after repeated no-shows.', '2026-06-19 15:12:00+05:30'),
  (25, 'admin', 5, 'Resolved reported issue', 'Issue raised on FMR-2026-1025 closed after workshop response.', '2026-06-26 15:05:00+05:30'),
  (26, 'mechanic', 4, 'Updated job status', 'Ramesh Patel marked FMR-2026-1026 as complete.', '2026-07-03 15:58:00+05:30'),
  (27, 'user', 27, 'Raised service request', 'Gaurav Saxena booked FMR-2026-1027.', '2026-07-10 15:51:00+05:30'),
  (28, 'user', 28, 'Cancelled booking', 'Anjali Dubey cancelled FMR-2026-1028 before dispatch.', '2026-07-17 15:44:00+05:30'),
  (29, 'admin', 9, 'Processed refund', 'Refund issued against FMR-2026-1029 after a service complaint.', '2026-07-24 15:37:00+05:30'),
  (30, 'admin', 10, 'Exported payment report', 'Monthly reconciliation report generated for finance.', '2026-07-31 15:30:00+05:30');


-- notifications ----------------------------------------------------
INSERT INTO notifications (id, recipient_role, recipient_id, title, body, read, created_at) VALUES
  (1, 'admin', 1, 'Mechanic awaiting approval', 'Yadav Service Point has submitted documents for verification.', 1, '2026-01-07 07:59:00+05:30'),
  (2, 'admin', 2, 'Payment failed', 'Payment for FMR-2026-1002 failed and needs manual follow-up.', 1, '2026-01-14 07:58:00+05:30'),
  (3, 'admin', 3, 'Refund requested', 'A refund has been requested against FMR-2026-1003.', 1, '2026-01-21 07:57:00+05:30'),
  (4, 'admin', 4, 'SLA breach', 'Job FMR-2026-1004 has exceeded its promised completion window.', 1, '2026-01-28 07:56:00+05:30'),
  (5, 'admin', 5, 'New issue reported', 'Vikas Gupta reported an issue on FMR-2026-1005.', 1, '2026-02-04 07:55:00+05:30'),
  (6, 'admin', 6, 'Low rated review', 'A 3-star review was left on FMR-2026-1006. Review recommended.', 1, '2026-02-11 07:54:00+05:30'),
  (7, 'admin', 7, 'Daily summary', '24 bookings, 19 completed and 3 escalations in the last day.', 1, '2026-02-18 07:53:00+05:30'),
  (8, 'admin', 8, 'Mechanic unavailable', 'Ajay Thakur has marked themselves unavailable this week.', 1, '2026-02-25 07:52:00+05:30'),
  (9, 'admin', 9, 'Reassignment done', 'FMR-2026-1009 was reassigned to keep the promised slot.', 1, '2026-03-04 07:51:00+05:30'),
  (10, 'admin', 10, 'Weekly reconciliation', 'The weekly payment reconciliation report is ready.', 1, '2026-03-11 07:50:00+05:30'),
  (11, 'admin', 1, 'Mechanic awaiting approval', 'Kumar Tyre House has submitted documents for verification.', 1, '2026-03-18 07:49:00+05:30'),
  (12, 'admin', 2, 'Payment failed', 'Payment for FMR-2026-1012 failed and needs manual follow-up.', 1, '2026-03-25 07:48:00+05:30'),
  (13, 'admin', 3, 'Refund requested', 'A refund has been requested against FMR-2026-1013.', 1, '2026-04-01 07:47:00+05:30'),
  (14, 'admin', 4, 'SLA breach', 'Job FMR-2026-1014 has exceeded its promised completion window.', 1, '2026-04-08 07:46:00+05:30'),
  (15, 'admin', 5, 'New issue reported', 'Manish Tiwari reported an issue on FMR-2026-1015.', 1, '2026-04-15 07:45:00+05:30'),
  (16, 'admin', 6, 'Low rated review', 'A 3-star review was left on FMR-2026-1016. Review recommended.', 1, '2026-04-22 07:44:00+05:30'),
  (17, 'admin', 7, 'Daily summary', '24 bookings, 19 completed and 3 escalations in the last day.', 1, '2026-04-29 07:43:00+05:30'),
  (18, 'admin', 8, 'Mechanic unavailable', 'Bhaskar Rao has marked themselves unavailable this week.', 1, '2026-05-06 07:42:00+05:30'),
  (19, 'admin', 9, 'Reassignment done', 'FMR-2026-1019 was reassigned to keep the promised slot.', 0, '2026-05-13 07:41:00+05:30'),
  (20, 'admin', 10, 'Weekly reconciliation', 'The weekly payment reconciliation report is ready.', 0, '2026-05-20 07:40:00+05:30'),
  (21, 'admin', 1, 'Mechanic awaiting approval', 'Kamble Electricals has submitted documents for verification.', 0, '2026-05-27 07:39:00+05:30'),
  (22, 'admin', 2, 'Payment failed', 'Payment for FMR-2026-1022 failed and needs manual follow-up.', 0, '2026-06-03 07:38:00+05:30'),
  (23, 'admin', 3, 'Refund requested', 'A refund has been requested against FMR-2026-1023.', 0, '2026-06-10 07:37:00+05:30'),
  (24, 'admin', 4, 'SLA breach', 'Job FMR-2026-1024 has exceeded its promised completion window.', 0, '2026-06-17 07:36:00+05:30'),
  (25, 'admin', 5, 'New issue reported', 'Harsh Vardhan reported an issue on FMR-2026-1025.', 0, '2026-06-24 07:35:00+05:30'),
  (26, 'admin', 6, 'Low rated review', 'A 3-star review was left on FMR-2026-1026. Review recommended.', 0, '2026-07-01 07:34:00+05:30'),
  (27, 'admin', 7, 'Daily summary', '24 bookings, 19 completed and 3 escalations in the last day.', 0, '2026-07-08 07:33:00+05:30'),
  (28, 'admin', 8, 'Mechanic unavailable', 'Ajay Thakur has marked themselves unavailable this week.', 0, '2026-07-15 07:32:00+05:30'),
  (29, 'admin', 9, 'Reassignment done', 'FMR-2026-1029 was reassigned to keep the promised slot.', 0, '2026-07-22 07:31:00+05:30'),
  (30, 'admin', 10, 'Weekly reconciliation', 'The weekly payment reconciliation report is ready.', 0, '2026-07-29 07:30:00+05:30');


-- ---------------------------------------------------------------------
-- 3. RESYNC IDENTITY SEQUENCES
-- ---------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('admins','id'),           (SELECT MAX(id) FROM admins));
SELECT setval(pg_get_serial_sequence('managed_payments','id'), (SELECT MAX(id) FROM managed_payments));
SELECT setval(pg_get_serial_sequence('service_overview','id'), (SELECT MAX(id) FROM service_overview));
SELECT setval(pg_get_serial_sequence('job_assignments','id'),  (SELECT MAX(id) FROM job_assignments));
SELECT setval(pg_get_serial_sequence('system_logs','id'),      (SELECT MAX(id) FROM system_logs));
SELECT setval(pg_get_serial_sequence('notifications','id'),    (SELECT MAX(id) FROM notifications));

COMMIT;
