-- =====================================================================
-- FixMyRide — "Find Mechanics Nearby" (roadside assistance)
-- Target database : am_mech
--
-- Dispatch mirror of am_user.nearby_requests. The user module owns the
-- request; this table is what the mechanic app polls and acts on. The
-- originating id travels with the row as `origin_request_id` so the
-- mechanic backend can report its decision back to the user backend.
--
-- Additive and idempotent.
--
--   psql -U postgres -h localhost -d am_mech -f docs/am_mech_nearby_requests.sql
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS nearby_requests (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- id of the row in am_user.nearby_requests. Unique so a retried dispatch
    -- updates the existing mirror instead of creating a second copy.
    origin_request_id  INTEGER     NOT NULL UNIQUE,
    reference          TEXT        NOT NULL,
    mechanic_id        INTEGER     NOT NULL REFERENCES mechanics(id) ON DELETE CASCADE,

    user_id            INTEGER     NOT NULL,       -- cross-module, no FK by design
    user_name          TEXT,
    user_phone         TEXT,

    vehicle_make       TEXT,
    vehicle_model      TEXT,
    vehicle_year       INTEGER,
    vehicle_reg_no     TEXT,

    issue_key          TEXT        NOT NULL,
    issue_label        TEXT        NOT NULL,
    description        TEXT,

    user_lat           NUMERIC(9,6) NOT NULL,
    user_lng           NUMERIC(9,6) NOT NULL,
    user_location_label TEXT,
    mechanic_lat       NUMERIC(9,6),
    mechanic_lng       NUMERIC(9,6),
    mechanic_location_label TEXT,

    distance_km        NUMERIC(6,1),
    eta_minutes        INTEGER,

    price_min          NUMERIC(10,2),
    price_max          NUMERIC(10,2),
    price_currency     TEXT        NOT NULL DEFAULT 'INR',
    price_requires_diagnosis INTEGER NOT NULL DEFAULT 0,

    status             TEXT        NOT NULL DEFAULT 'PENDING_MECHANIC_RESPONSE'
                       CHECK (status IN ('SEARCHING','PENDING_MECHANIC_RESPONSE','ACCEPTED',
                                         'REJECTED','MECHANIC_ON_THE_WAY','ARRIVED','IN_SERVICE',
                                         'COMPLETED','CANCELLED','NO_MECHANIC_FOUND')),
    rejection_reason   TEXT,
    -- Set once the mechanic app has played its alert for this request, so a
    -- re-render or a second browser tab cannot retrigger the sound.
    alerted            INTEGER     NOT NULL DEFAULT 0,

    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    responded_at       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_nearby_mech_mechanic ON nearby_requests(mechanic_id);
CREATE INDEX IF NOT EXISTS idx_nearby_mech_status   ON nearby_requests(status);

COMMIT;
