-- =====================================================================
-- FixMyRide - am_mech schema and seed data
-- Target database : am_mech   (PostgreSQL 18, server "automate")
-- Generated from  : docs/FixMyRide-SRS-HLD-LLD.pdf, section 7.2 (Data design)
--
-- Schema is a faithful port of the LLD tables. SQLite -> PostgreSQL mapping:
--   INTEGER PK AUTOINCREMENT -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--   TEXT                     -> TEXT
--   REAL (money)             -> NUMERIC(10,2)      REAL (rating) -> NUMERIC(2,1)
--   TEXT DEFAULT datetime()  -> TIMESTAMPTZ DEFAULT now()
--   INTEGER 0/1 flags        -> INTEGER (kept as in the LLD, not BOOLEAN)
-- Cross-module columns (mechanic_id in user db, service_request_id in mechanic
-- db, every mirror table in admin db) carry NO foreign key, exactly as the LLD
-- specifies - the three databases stay independently deployable.
--
-- IDs are aligned across all three databases: user #7 is user #7 everywhere,
-- mechanic #12 is mechanic #12 everywhere, and service request #5 is job #5
-- and service_overview #5. This makes the mirrors joinable by hand.
--
-- Contains: mechanics, services, jobs, job_updates, payments, reviews, notifications
-- Each table is seeded with 30 rows. Password for every seeded principal is
-- "password123" (stored as a real bcrypt hash).
--
-- Run with:
--   psql -U postgres -h localhost -d am_mech -f <this file>
-- The script is idempotent: it drops and recreates its own tables.
-- =====================================================================

BEGIN;


-- ---------------------------------------------------------------------
-- 1. SCHEMA
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS job_updates, jobs, services, payments, reviews,
                     notifications, mechanics CASCADE;

CREATE TABLE mechanics (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT        NOT NULL,
    email           TEXT        NOT NULL UNIQUE,
    password_hash   TEXT        NOT NULL,
    phone           TEXT,
    skills          TEXT,
    available       INTEGER     NOT NULL DEFAULT 1,
    rating          NUMERIC(2,1) NOT NULL DEFAULT 4.5,
    approval_status TEXT        DEFAULT 'pending',
    workshop_name   TEXT,
    address         TEXT,
    certifications  TEXT,
    pricing_model   TEXT,
    location        TEXT,
    specialization  TEXT,
    price_from      NUMERIC(10,2),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE services (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mechanic_id  INTEGER      NOT NULL REFERENCES mechanics(id) ON DELETE CASCADE,
    name         TEXT         NOT NULL,
    description  TEXT,
    price        NUMERIC(10,2) NOT NULL DEFAULT 0,
    duration     TEXT,
    available    INTEGER      NOT NULL DEFAULT 1,
    is_promotion INTEGER      NOT NULL DEFAULT 0,
    promo_label  TEXT,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- jobs.status defaults to 'assigned': a job only exists once it is dispatched,
-- unlike service_requests which start life as 'pending'.
CREATE TABLE jobs (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id INTEGER     NOT NULL,          -- user module SR, no FK by design
    user_id            INTEGER,
    mechanic_id        INTEGER     NOT NULL REFERENCES mechanics(id) ON DELETE CASCADE,
    category           TEXT,
    description        TEXT,
    status             TEXT        NOT NULL DEFAULT 'assigned'
                       CHECK (status IN ('pending','assigned','accepted',
                                         'in_progress','completed','cancelled')),
    notes              TEXT,
    price              NUMERIC(10,2),
    scheduled_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE job_updates (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id     INTEGER     NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    type       TEXT        NOT NULL CHECK (type IN ('note','status_change','image')),
    message    TEXT,
    image_path TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payments (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          INTEGER,
    mechanic_id     INTEGER      NOT NULL REFERENCES mechanics(id) ON DELETE CASCADE,
    customer_name   TEXT,
    amount          NUMERIC(10,2) NOT NULL DEFAULT 0,
    method          TEXT,
    status          TEXT         NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','paid','failed','refunded')),
    transaction_ref TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE reviews (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id INTEGER,
    mechanic_id        INTEGER     NOT NULL,
    user_id            INTEGER,
    user_name          TEXT,
    rating             INTEGER     NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment            TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_role TEXT        NOT NULL,
    recipient_id   INTEGER     NOT NULL,
    title          TEXT        NOT NULL,
    body           TEXT        NOT NULL,
    read           INTEGER     NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes (LLD section 7.2.4)
CREATE INDEX idx_jobs_mechanic          ON jobs(mechanic_id);
CREATE INDEX idx_services_mechanic      ON services(mechanic_id);
CREATE INDEX idx_payments_mechanic      ON payments(mechanic_id);
CREATE INDEX idx_reviews_mechanic       ON reviews(mechanic_id);
CREATE INDEX idx_jobs_service           ON jobs(service_request_id);
CREATE INDEX idx_job_updates_job        ON job_updates(job_id);
CREATE INDEX idx_notifications_recipient ON notifications(recipient_role, recipient_id);


-- ---------------------------------------------------------------------
-- 2. SEED DATA (30 rows per table)
-- ---------------------------------------------------------------------


-- mechanics --------------------------------------------------------
INSERT INTO mechanics (id, name, email, password_hash, phone, skills, available, rating,
                       approval_status, workshop_name, address, certifications,
                       pricing_model, location, specialization, price_from, created_at) VALUES
  (1, 'Vikram Singh', 'vikram@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9820556711', 'Engine diagnostics, timing belt, head gasket', 1, 4.8, 'approved', 'Singh Auto Works', 'Singh Auto Works, Andheri East, Mumbai', 'ASE Certified Master Technician', 'hourly', 'Andheri East, Mumbai', 'Engine Overhaul', 1800, '2025-09-10 10:31:00+05:30'),
  (2, 'Imran Khan', 'imran@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9945883021', 'Disc brakes, ABS, shock absorbers', 1, 4.6, 'approved', 'Khan Motor Garage', 'Khan Motor Garage, Koramangala, Bengaluru', 'Maruti Suzuki Authorised Trainee', 'fixed', 'Koramangala, Bengaluru', 'Brake and Suspension', 1200, '2025-09-12 10:02:00+05:30'),
  (3, 'Suresh Yadav', 'suresh@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9871220934', 'Oil change, filters, general service', 1, 4.7, 'approved', 'Yadav Service Point', 'Yadav Service Point, Lajpat Nagar, New Delhi', 'Bosch Car Service Certified', 'per_job', 'Lajpat Nagar, New Delhi', 'Periodic Service', 900, '2025-09-14 10:33:00+05:30'),
  (4, 'Ramesh Patel', 'ramesh@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9825441207', 'Clutch, gearbox, CVT service', 1, 4.5, 'approved', 'Patel Auto Care', 'Patel Auto Care, Satellite, Ahmedabad', 'Hyundai Service Level 2', 'hourly', 'Satellite, Ahmedabad', 'Transmission', 2200, '2025-09-16 10:04:00+05:30'),
  (5, 'Balaji Naidu', 'balaji@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9884330176', 'Wiring, alternator, ECU scan', 1, 4.4, 'approved', 'Naidu Electricals', 'Naidu Electricals, Velachery, Chennai', 'Tata Motors Certified Technician', 'fixed', 'Velachery, Chennai', 'Auto Electricals', 800, '2025-09-18 10:35:00+05:30'),
  (6, 'Farhan Sheikh', 'farhan@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9769112084', 'Compressor, gas refill, cooling coil', 1, 4.6, 'approved', 'Sheikh Cool Care', 'Sheikh Cool Care, Kurla West, Mumbai', 'ITI Diploma in Automobile Engineering', 'per_job', 'Kurla West, Mumbai', 'AC Service', 1100, '2025-09-20 10:06:00+05:30'),
  (7, 'Dinesh Kumar', 'dinesh@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9848225530', 'Tyre fitting, balancing, alignment', 1, 4.3, 'approved', 'Kumar Tyre House', 'Kumar Tyre House, Madhapur, Hyderabad', 'Mahindra First Choice Certified', 'hourly', 'Madhapur, Hyderabad', 'Tyres and Alignment', 700, '2025-09-22 10:37:00+05:30'),
  (8, 'Prakash Jha', 'prakash@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9830667214', 'Body repair, spray paint, polish', 0, 4.5, 'approved', 'Jha Body Shop', 'Jha Body Shop, Behala, Kolkata', 'Honda Service Grade A', 'fixed', 'Behala, Kolkata', 'Denting and Painting', 2500, '2025-09-24 10:08:00+05:30'),
  (9, 'Ajay Thakur', 'ajay@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9822009431', 'Turbo repair, injector cleaning', 1, 4.7, 'approved', 'Thakur Motors', 'Thakur Motors, Hadapsar, Pune', 'Denso AC Systems Certified', 'per_job', 'Hadapsar, Pune', 'Engine Overhaul', 1900, '2025-09-26 10:39:00+05:30'),
  (10, 'Mohan Das', 'mohan@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9995114876', 'Multi-brand service, inspection', 1, 4.4, 'approved', 'Das Auto Point', 'Das Auto Point, Edappally, Kochi', 'MAM Institute Level 3', 'hourly', 'Edappally, Kochi', 'Periodic Service', 850, '2025-09-28 10:10:00+05:30'),
  (11, 'Irfan Ali', 'irfan@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9871559023', 'Brake pads, strut replacement', 1, 4.5, 'approved', 'Ali Auto Garage', 'Ali Auto Garage, Okhla, New Delhi', 'ASE Certified Master Technician', 'fixed', 'Okhla, New Delhi', 'Brake and Suspension', 1150, '2025-09-30 10:41:00+05:30'),
  (12, 'Sunil Rawat', 'sunil@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9313770285', 'Battery, starter motor, jump start', 1, 4.2, 'approved', 'Rawat Power Works', 'Rawat Power Works, Sector 63, Noida', 'Maruti Suzuki Authorised Trainee', 'per_job', 'Sector 63, Noida', 'Battery and Starter', 600, '2025-10-02 10:12:00+05:30'),
  (13, 'Kiran Kamble', 'kiran@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9767442190', 'Headlamps, sensors, fuse box', 1, 4.3, 'approved', 'Kamble Electricals', 'Kamble Electricals, Kothrud, Pune', 'Bosch Car Service Certified', 'hourly', 'Kothrud, Pune', 'Auto Electricals', 750, '2025-10-04 10:43:00+05:30'),
  (14, 'Naveen Reddy', 'naveen@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9701338042', 'Automatic gearbox, clutch plate', 1, 4.8, 'approved', 'Reddy Transmission', 'Reddy Transmission, Kondapur, Hyderabad', 'Hyundai Service Level 2', 'fixed', 'Kondapur, Hyderabad', 'Transmission', 2300, '2025-10-06 10:14:00+05:30'),
  (15, 'Zubair Ahmed', 'zubair@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9836227015', 'Dent removal, full body paint', 0, 4.4, 'approved', 'Ahmed Auto Body', 'Ahmed Auto Body, Park Circus, Kolkata', 'Tata Motors Certified Technician', 'per_job', 'Park Circus, Kolkata', 'Denting and Painting', 2400, '2025-10-08 10:45:00+05:30'),
  (16, 'Santosh Pawar', 'santosh@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9822661370', 'Cylinder head, coolant system', 1, 4.6, 'approved', 'Pawar Engine Works', 'Pawar Engine Works, Wakad, Pune', 'ITI Diploma in Automobile Engineering', 'hourly', 'Wakad, Pune', 'Engine Overhaul', 2000, '2025-10-10 10:16:00+05:30'),
  (17, 'Rakesh Yadav', 'rakesh@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9450228116', 'Scheduled service, fluid top-up', 1, 4.5, 'approved', 'Yadav Car Care', 'Yadav Car Care, Gomti Nagar, Lucknow', 'Mahindra First Choice Certified', 'fixed', 'Gomti Nagar, Lucknow', 'Periodic Service', 880, '2025-10-12 10:47:00+05:30'),
  (18, 'Vinod Chauhan', 'vinod@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9812004573', 'Wheel balancing, puncture repair', 1, 4.1, 'approved', 'Chauhan Tyres', 'Chauhan Tyres, Sector 22, Chandigarh', 'Honda Service Grade A', 'per_job', 'Sector 22, Chandigarh', 'Tyres and Alignment', 680, '2025-10-14 10:18:00+05:30'),
  (19, 'Bhaskar Rao', 'bhaskar@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9880117642', 'Brake overhaul, suspension bush', 1, 4.7, 'approved', 'Rao Auto Service', 'Rao Auto Service, HSR Layout, Bengaluru', 'Denso AC Systems Certified', 'hourly', 'HSR Layout, Bengaluru', 'Brake and Suspension', 1250, '2025-10-16 10:49:00+05:30'),
  (20, 'Jitendra Mishra', 'jitendra@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9755330281', 'AC servicing, blower repair', 1, 4.3, 'approved', 'Mishra Cool Point', 'Mishra Cool Point, MP Nagar, Bhopal', 'MAM Institute Level 3', 'fixed', 'MP Nagar, Bhopal', 'AC Service', 1050, '2025-10-18 10:20:00+05:30'),
  (21, 'Salim Ansari', 'salim@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9820773401', 'Central locking, power windows', 1, 4.4, 'approved', 'Ansari Auto Elec', 'Ansari Auto Elec, Byculla, Mumbai', 'ASE Certified Master Technician', 'per_job', 'Byculla, Mumbai', 'Auto Electricals', 720, '2025-10-20 10:51:00+05:30'),
  (22, 'Girish Hegde', 'girish@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9945006618', 'Preventive maintenance, diagnostics', 1, 4.9, 'approved', 'Hegde Auto Studio', 'Hegde Auto Studio, Jayanagar, Bengaluru', 'Maruti Suzuki Authorised Trainee', 'hourly', 'Jayanagar, Bengaluru', 'Periodic Service', 920, '2025-10-22 10:22:00+05:30'),
  (23, 'Mahesh Solanki', 'mahesh@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9426881105', 'Battery swap, charging system', 0, 4.2, 'approved', 'Solanki Battery Hub', 'Solanki Battery Hub, Maninagar, Ahmedabad', 'Bosch Car Service Certified', 'fixed', 'Maninagar, Ahmedabad', 'Battery and Starter', 620, '2025-10-24 10:53:00+05:30'),
  (24, 'Ravi Shankar', 'ravi@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9840226794', 'Piston rings, valve job', 1, 4.6, 'approved', 'Shankar Engine Care', 'Shankar Engine Care, Guindy, Chennai', 'Hyundai Service Level 2', 'per_job', 'Guindy, Chennai', 'Engine Overhaul', 2100, '2025-10-26 10:24:00+05:30'),
  (25, 'Tushar Gaikwad', 'tushar@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9767118034', 'Panel beating, alloy refurb', 1, 4.5, 'approved', 'Gaikwad Body Works', 'Gaikwad Body Works, Pimpri, Pune', 'Tata Motors Certified Technician', 'hourly', 'Pimpri, Pune', 'Denting and Painting', 2350, '2025-10-28 10:55:00+05:30'),
  (26, 'Pankaj Bisht', 'pankaj@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9910447253', 'Brake fluid, coil spring', 1, 4.4, 'approved', 'Bisht Auto Garage', 'Bisht Auto Garage, Sector 45, Gurugram', 'ITI Diploma in Automobile Engineering', 'fixed', 'Sector 45, Gurugram', 'Brake and Suspension', 1180, '2025-10-30 10:26:00+05:30'),
  (27, 'Arif Mansoor', 'arif@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9769550218', 'Condenser, evaporator cleaning', 1, 4.3, 'approved', 'Mansoor Auto Cool', 'Mansoor Auto Cool, Mira Road, Mumbai', 'Mahindra First Choice Certified', 'per_job', 'Mira Road, Mumbai', 'AC Service', 1080, '2025-11-01 10:57:00+05:30'),
  (28, 'Yogesh Barot', 'yogesh@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9825117430', 'Alignment, camber correction', 0, 4.2, 'pending', 'Barot Wheel Care', 'Barot Wheel Care, Bopal, Ahmedabad', 'Honda Service Grade A', 'hourly', 'Bopal, Ahmedabad', 'Tyres and Alignment', 690, '2025-11-03 10:28:00+05:30'),
  (29, 'Devendra Rathore', 'devendra@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9829663017', 'Manual gearbox, differential', 0, 4.5, 'pending', 'Rathore Gear Works', 'Rathore Gear Works, Vaishali Nagar, Jaipur', 'Denso AC Systems Certified', 'fixed', 'Vaishali Nagar, Jaipur', 'Transmission', 2150, '2025-11-05 10:59:00+05:30'),
  (30, 'Chetan Bhagwat', 'chetan@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9822114509', 'Full service, road-test check', 0, 4.6, 'rejected', 'Bhagwat Auto Point', 'Bhagwat Auto Point, Dharampeth, Nagpur', 'MAM Institute Level 3', 'per_job', 'Dharampeth, Nagpur', 'Periodic Service', 870, '2025-11-07 10:30:00+05:30');


-- services ---------------------------------------------------------
-- One headline service package per mechanic, priced off their base rate.
INSERT INTO services (id, mechanic_id, name, description, price, duration,
                      available, is_promotion, promo_label, created_at) VALUES
  (1, 1, 'Engine Overhaul Package', 'Engine diagnostics, timing belt, head gasket carried out at Singh Auto Works by Vikram Singh. Includes inspection report and road test.', 4500.0, '45 minutes', 1, 0, NULL, '2025-09-15 11:41:00+05:30'),
  (2, 2, 'Brake and Suspension Package', 'Disc brakes, ABS, shock absorbers carried out at Khan Motor Garage by Imran Khan. Includes inspection report and road test.', 3000.0, '1 hour', 1, 0, NULL, '2025-09-17 11:22:00+05:30'),
  (3, 3, 'Periodic Service Package', 'Oil change, filters, general service carried out at Yadav Service Point by Suresh Yadav. Includes inspection report and road test.', 2250.0, '90 minutes', 1, 1, 'Monsoon Check-up 20% off', '2025-09-19 11:03:00+05:30'),
  (4, 4, 'Transmission Package', 'Clutch, gearbox, CVT service carried out at Patel Auto Care by Ramesh Patel. Includes inspection report and road test.', 5500.0, '2 hours', 1, 0, NULL, '2025-09-21 11:44:00+05:30'),
  (5, 5, 'Auto Electricals Package', 'Wiring, alternator, ECU scan carried out at Naidu Electricals by Balaji Naidu. Includes inspection report and road test.', 2000.0, '3 hours', 1, 0, NULL, '2025-09-23 11:25:00+05:30'),
  (6, 6, 'AC Service Package', 'Compressor, gas refill, cooling coil carried out at Sheikh Cool Care by Farhan Sheikh. Includes inspection report and road test.', 2750.0, '4 hours', 1, 0, NULL, '2025-09-25 11:06:00+05:30'),
  (7, 7, 'Tyres and Alignment Package', 'Tyre fitting, balancing, alignment carried out at Kumar Tyre House by Dinesh Kumar. Includes inspection report and road test.', 1750.0, '1 day', 1, 1, 'Buy 3 tyres get alignment free', '2025-09-27 11:47:00+05:30'),
  (8, 8, 'Denting and Painting Package', 'Body repair, spray paint, polish carried out at Jha Body Shop by Prakash Jha. Includes inspection report and road test.', 6250.0, '2 days', 1, 0, NULL, '2025-09-29 11:28:00+05:30'),
  (9, 9, 'Engine Overhaul Package', 'Turbo repair, injector cleaning carried out at Thakur Motors by Ajay Thakur. Includes inspection report and road test.', 4750.0, '45 minutes', 1, 0, NULL, '2025-10-01 11:09:00+05:30'),
  (10, 10, 'Periodic Service Package', 'Multi-brand service, inspection carried out at Das Auto Point by Mohan Das. Includes inspection report and road test.', 2125.0, '1 hour', 1, 0, NULL, '2025-10-03 11:50:00+05:30'),
  (11, 11, 'Brake and Suspension Package', 'Brake pads, strut replacement carried out at Ali Auto Garage by Irfan Ali. Includes inspection report and road test.', 2875.0, '90 minutes', 1, 1, 'Festive brake combo', '2025-10-05 11:31:00+05:30'),
  (12, 12, 'Battery and Starter Package', 'Battery, starter motor, jump start carried out at Rawat Power Works by Sunil Rawat. Includes inspection report and road test.', 1500.0, '2 hours', 1, 0, NULL, '2025-10-07 11:12:00+05:30'),
  (13, 13, 'Auto Electricals Package', 'Headlamps, sensors, fuse box carried out at Kamble Electricals by Kiran Kamble. Includes inspection report and road test.', 1875.0, '3 hours', 1, 0, NULL, '2025-10-09 11:53:00+05:30'),
  (14, 14, 'Transmission Package', 'Automatic gearbox, clutch plate carried out at Reddy Transmission by Naveen Reddy. Includes inspection report and road test.', 5750.0, '4 hours', 1, 0, NULL, '2025-10-11 11:34:00+05:30'),
  (15, 15, 'Denting and Painting Package', 'Dent removal, full body paint carried out at Ahmed Auto Body by Zubair Ahmed. Includes inspection report and road test.', 6000.0, '1 day', 1, 0, NULL, '2025-10-13 11:15:00+05:30'),
  (16, 16, 'Engine Overhaul Package', 'Cylinder head, coolant system carried out at Pawar Engine Works by Santosh Pawar. Includes inspection report and road test.', 5000.0, '2 days', 1, 1, 'Winter engine tune-up offer', '2025-10-15 11:56:00+05:30'),
  (17, 17, 'Periodic Service Package', 'Scheduled service, fluid top-up carried out at Yadav Car Care by Rakesh Yadav. Includes inspection report and road test.', 2200.0, '45 minutes', 1, 0, NULL, '2025-10-17 11:37:00+05:30'),
  (18, 18, 'Tyres and Alignment Package', 'Wheel balancing, puncture repair carried out at Chauhan Tyres by Vinod Chauhan. Includes inspection report and road test.', 1700.0, '1 hour', 1, 0, NULL, '2025-10-19 11:18:00+05:30'),
  (19, 19, 'Brake and Suspension Package', 'Brake overhaul, suspension bush carried out at Rao Auto Service by Bhaskar Rao. Includes inspection report and road test.', 3125.0, '90 minutes', 1, 0, NULL, '2025-10-21 11:59:00+05:30'),
  (20, 20, 'AC Service Package', 'AC servicing, blower repair carried out at Mishra Cool Point by Jitendra Mishra. Includes inspection report and road test.', 2625.0, '2 hours', 1, 0, NULL, '2025-10-23 11:40:00+05:30'),
  (21, 21, 'Auto Electricals Package', 'Central locking, power windows carried out at Ansari Auto Elec by Salim Ansari. Includes inspection report and road test.', 1800.0, '3 hours', 1, 0, NULL, '2025-10-25 11:21:00+05:30'),
  (22, 22, 'Periodic Service Package', 'Preventive maintenance, diagnostics carried out at Hegde Auto Studio by Girish Hegde. Includes inspection report and road test.', 2300.0, '4 hours', 1, 1, 'First service free inspection', '2025-10-27 11:02:00+05:30'),
  (23, 23, 'Battery and Starter Package', 'Battery swap, charging system carried out at Solanki Battery Hub by Mahesh Solanki. Includes inspection report and road test.', 1550.0, '1 day', 1, 0, NULL, '2025-10-29 11:43:00+05:30'),
  (24, 24, 'Engine Overhaul Package', 'Piston rings, valve job carried out at Shankar Engine Care by Ravi Shankar. Includes inspection report and road test.', 5250.0, '2 days', 1, 0, NULL, '2025-10-31 11:24:00+05:30'),
  (25, 25, 'Denting and Painting Package', 'Panel beating, alloy refurb carried out at Gaikwad Body Works by Tushar Gaikwad. Includes inspection report and road test.', 5875.0, '45 minutes', 1, 0, NULL, '2025-11-02 11:05:00+05:30'),
  (26, 26, 'Brake and Suspension Package', 'Brake fluid, coil spring carried out at Bisht Auto Garage by Pankaj Bisht. Includes inspection report and road test.', 2950.0, '1 hour', 1, 0, NULL, '2025-11-04 11:46:00+05:30'),
  (27, 27, 'AC Service Package', 'Condenser, evaporator cleaning carried out at Mansoor Auto Cool by Arif Mansoor. Includes inspection report and road test.', 2700.0, '90 minutes', 1, 1, 'Summer AC special', '2025-11-06 11:27:00+05:30'),
  (28, 28, 'Tyres and Alignment Package', 'Alignment, camber correction carried out at Barot Wheel Care by Yogesh Barot. Includes inspection report and road test.', 1725.0, '2 hours', 0, 0, NULL, '2025-11-08 11:08:00+05:30'),
  (29, 29, 'Transmission Package', 'Manual gearbox, differential carried out at Rathore Gear Works by Devendra Rathore. Includes inspection report and road test.', 5375.0, '3 hours', 0, 0, NULL, '2025-11-10 11:49:00+05:30'),
  (30, 30, 'Periodic Service Package', 'Full service, road-test check carried out at Bhagwat Auto Point by Chetan Bhagwat. Includes inspection report and road test.', 2175.0, '4 hours', 0, 0, NULL, '2025-11-12 11:30:00+05:30');


-- jobs -------------------------------------------------------------
-- Mirrors the user module: job N handles service request N.
-- SR #30 is still 'pending' on the user side; here it is 'assigned',
-- which is exactly what dispatch does to it.
INSERT INTO jobs (id, service_request_id, user_id, mechanic_id, category, description,
                  status, notes, price, scheduled_at, created_at, updated_at) VALUES
  (1, 1, 1, 3, 'Engine Repair', 'Rough idling and loss of power above 60 kmph', 'completed', 'Compression test done, replaced two ignition coils and cleaned injectors.', 8075.0, '2026-01-08 11:07:00+05:30', '2026-01-06 09:13:00+05:30', '2026-01-09 16:11:00+05:30'),
  (2, 2, 2, 7, 'Brake Service', 'Squealing noise from the front brakes while braking', 'completed', 'Front pads and discs replaced, brake fluid flushed.', 3136.0, '2026-01-15 12:14:00+05:30', '2026-01-13 09:26:00+05:30', '2026-01-16 16:22:00+05:30'),
  (3, 3, 3, 1, 'Oil Change', 'Due for scheduled engine oil and filter replacement', 'completed', 'Engine oil 5W-30 fully synthetic plus oil and air filter replaced.', 2424.0, '2026-01-22 13:21:00+05:30', '2026-01-20 09:39:00+05:30', '2026-01-23 16:33:00+05:30'),
  (4, 4, 4, 12, 'Battery Replacement', 'Car not cranking in the morning, battery is 4 years old', 'completed', 'Fitted a new 65Ah battery, checked alternator output at 14.2V.', 5824.0, '2026-01-29 14:28:00+05:30', '2026-01-27 09:52:00+05:30', '2026-01-30 16:44:00+05:30'),
  (5, 5, 5, 5, 'AC Service', 'AC blows warm air after 10 minutes of driving', 'completed', 'Regassed AC, replaced cabin filter and cleaned the evaporator.', 4066.0, '2026-02-05 15:35:00+05:30', '2026-02-03 09:05:00+05:30', '2026-02-06 16:55:00+05:30'),
  (6, 6, 6, 3, 'Tyre Replacement', 'Front two tyres worn below the tread wear indicator', 'completed', 'Two Michelin tyres fitted, balanced and old tyres disposed.', 9114.0, '2026-02-12 10:42:00+05:30', '2026-02-10 09:18:00+05:30', '2026-02-13 16:06:00+05:30'),
  (7, 7, 7, 18, 'Suspension Work', 'Knocking sound from rear suspension over speed breakers', 'completed', 'Rear shock absorbers and bush kit replaced, road tested for 12 km.', 6144.0, '2026-02-19 11:49:00+05:30', '2026-02-17 09:31:00+05:30', '2026-02-20 16:17:00+05:30'),
  (8, 8, 8, 9, 'Electrical Diagnostics', 'Dashboard warning lights flickering intermittently', 'completed', 'Scanned ECU, repaired a chafed harness behind the dashboard.', 2871.0, '2026-02-26 12:56:00+05:30', '2026-02-24 09:44:00+05:30', '2026-02-27 16:28:00+05:30'),
  (9, 9, 9, 1, 'Clutch Repair', 'Clutch slipping in third and fourth gear', 'completed', 'Clutch plate, pressure plate and release bearing replaced.', 11730.0, '2026-03-05 13:03:00+05:30', '2026-03-03 09:57:00+05:30', '2026-03-06 16:39:00+05:30'),
  (10, 10, 10, 22, 'Periodic Service', '40,000 km scheduled service with full inspection', 'completed', 'Full 40,000 km service completed, all fluids topped up.', 5460.0, '2026-03-12 14:10:00+05:30', '2026-03-10 09:10:00+05:30', '2026-03-13 16:50:00+05:30'),
  (11, 11, 11, 7, 'Denting and Painting', 'Rear left door dented in a parking incident', 'completed', 'Rear left door beaten out, primed, painted and polished.', 7992.0, '2026-03-19 15:17:00+05:30', '2026-03-17 09:23:00+05:30', '2026-03-20 16:01:00+05:30'),
  (12, 12, 12, 14, 'Wheel Alignment', 'Steering pulls to the left on straight roads', 'completed', 'Four wheel alignment and balancing done, camber corrected.', 1504.0, '2026-03-26 10:24:00+05:30', '2026-03-24 09:36:00+05:30', '2026-03-27 16:12:00+05:30'),
  (13, 13, 13, 2, 'Engine Repair', 'Rough idling and loss of power above 60 kmph', 'completed', 'Compression test done, replaced two ignition coils and cleaned injectors.', 8245.0, '2026-04-02 11:31:00+05:30', '2026-03-31 09:49:00+05:30', '2026-04-03 16:23:00+05:30'),
  (14, 14, 14, 25, 'Brake Service', 'Squealing noise from the front brakes while braking', 'completed', 'Front pads and discs replaced, brake fluid flushed.', 3200.0, '2026-04-09 12:38:00+05:30', '2026-04-07 09:02:00+05:30', '2026-04-10 16:34:00+05:30'),
  (15, 15, 15, 11, 'Oil Change', 'Due for scheduled engine oil and filter replacement', 'completed', 'Engine oil 5W-30 fully synthetic plus oil and air filter replaced.', 2472.0, '2026-04-16 13:45:00+05:30', '2026-04-14 09:15:00+05:30', '2026-04-17 16:45:00+05:30'),
  (16, 16, 16, 3, 'Battery Replacement', 'Car not cranking in the morning, battery is 4 years old', 'completed', 'Fitted a new 65Ah battery, checked alternator output at 14.2V.', 5936.0, '2026-04-23 14:52:00+05:30', '2026-04-21 09:28:00+05:30', '2026-04-24 16:56:00+05:30'),
  (17, 17, 17, 8, 'AC Service', 'AC blows warm air after 10 minutes of driving', 'completed', 'Regassed AC, replaced cabin filter and cleaned the evaporator.', 3496.0, '2026-04-30 15:59:00+05:30', '2026-04-28 09:41:00+05:30', '2026-05-01 16:07:00+05:30'),
  (18, 18, 18, 19, 'Tyre Replacement', 'Front two tyres worn below the tread wear indicator', 'completed', 'Two Michelin tyres fitted, balanced and old tyres disposed.', 9310.0, '2026-05-07 10:06:00+05:30', '2026-05-05 09:54:00+05:30', '2026-05-08 16:18:00+05:30'),
  (19, 19, 19, 5, 'Suspension Work', 'Knocking sound from rear suspension over speed breakers', 'completed', 'Rear shock absorbers and bush kit replaced, road tested for 12 km.', 6272.0, '2026-05-14 11:13:00+05:30', '2026-05-12 09:07:00+05:30', '2026-05-15 16:29:00+05:30'),
  (20, 20, 20, 27, 'Electrical Diagnostics', 'Dashboard warning lights flickering intermittently', 'completed', 'Scanned ECU, repaired a chafed harness behind the dashboard.', 2929.0, '2026-05-21 12:20:00+05:30', '2026-05-19 09:20:00+05:30', '2026-05-22 16:40:00+05:30'),
  (21, 21, 21, 13, 'Clutch Repair', 'Clutch slipping in third and fourth gear', 'completed', 'Clutch plate, pressure plate and release bearing replaced.', 11960.0, '2026-05-28 13:27:00+05:30', '2026-05-26 09:33:00+05:30', '2026-05-29 16:51:00+05:30'),
  (22, 22, 22, 1, 'Periodic Service', '40,000 km scheduled service with full inspection', 'completed', 'Full 40,000 km service completed, all fluids topped up.', 5564.0, '2026-06-04 14:34:00+05:30', '2026-06-02 09:46:00+05:30', '2026-06-05 16:02:00+05:30'),
  (23, 23, 23, 30, 'Denting and Painting', 'Rear left door dented in a parking incident', 'completed', 'Rear left door beaten out, primed, painted and polished.', 6882.0, '2026-06-11 15:41:00+05:30', '2026-06-09 09:59:00+05:30', '2026-06-12 16:13:00+05:30'),
  (24, 24, 24, 16, 'Wheel Alignment', 'Steering pulls to the left on straight roads', 'completed', 'Four wheel alignment and balancing done, camber corrected.', 1536.0, '2026-06-18 10:48:00+05:30', '2026-06-16 09:12:00+05:30', '2026-06-19 16:24:00+05:30'),
  (25, 25, 25, 7, 'Engine Repair', 'Rough idling and loss of power above 60 kmph', 'completed', 'Compression test done, replaced two ignition coils and cleaned injectors.', 8415.0, '2026-06-25 11:55:00+05:30', '2026-06-23 09:25:00+05:30', '2026-06-26 16:35:00+05:30'),
  (26, 26, 26, 4, 'Brake Service', 'Squealing noise from the front brakes while braking', 'in_progress', 'Front pads and discs replaced, brake fluid flushed.', 3264.0, '2026-07-02 12:02:00+05:30', '2026-06-30 09:38:00+05:30', '2026-07-03 16:46:00+05:30'),
  (27, 27, 27, 21, 'Oil Change', 'Due for scheduled engine oil and filter replacement', 'in_progress', 'Engine oil 5W-30 fully synthetic plus oil and air filter replaced.', 2520.0, '2026-07-09 13:09:00+05:30', '2026-07-07 09:51:00+05:30', '2026-07-10 16:57:00+05:30'),
  (28, 28, 28, 9, 'Battery Replacement', 'Car not cranking in the morning, battery is 4 years old', 'accepted', 'Awaiting customer confirmation of the estimate.', 6048.0, '2026-07-16 14:16:00+05:30', '2026-07-14 09:04:00+05:30', '2026-07-17 16:08:00+05:30'),
  (29, 29, 29, 26, 'AC Service', 'AC blows warm air after 10 minutes of driving', 'assigned', 'Awaiting customer confirmation of the estimate.', 3572.0, '2026-07-23 15:23:00+05:30', '2026-07-21 09:17:00+05:30', '2026-07-24 16:19:00+05:30'),
  (30, 30, 30, 12, 'Tyre Replacement', 'Front two tyres worn below the tread wear indicator', 'assigned', 'Awaiting customer confirmation of the estimate.', 9506.0, '2026-07-30 10:30:00+05:30', '2026-07-28 09:30:00+05:30', '2026-07-31 16:30:00+05:30');


-- job_updates ------------------------------------------------------
-- The running timeline the customer sees on the tracking screen.
INSERT INTO job_updates (id, job_id, type, message, image_path, created_at) VALUES
  (1, 1, 'status_change', 'Job accepted by the workshop and slot confirmed.', NULL, '2026-01-08 14:43:00+05:30'),
  (2, 2, 'note', 'Vehicle received at the workshop, initial inspection started.', NULL, '2026-01-15 14:26:00+05:30'),
  (3, 3, 'image', 'Photo of the worn part shared with the customer.', '/uploads/jobs/job_003_part.jpg', '2026-01-22 14:09:00+05:30'),
  (4, 4, 'note', 'Estimate revised after inspection and sent for approval.', NULL, '2026-01-29 14:52:00+05:30'),
  (5, 5, 'status_change', 'Work in progress, spare parts collected from the store.', NULL, '2026-02-05 14:35:00+05:30'),
  (6, 6, 'image', 'Progress photo uploaded after dismantling.', '/uploads/jobs/job_006_progress.jpg', '2026-02-12 14:18:00+05:30'),
  (7, 7, 'note', 'Road test completed, no abnormal noise observed.', NULL, '2026-02-19 14:01:00+05:30'),
  (8, 8, 'status_change', 'Job marked complete and the vehicle is ready for pickup.', NULL, '2026-02-26 14:44:00+05:30'),
  (9, 9, 'image', 'Final photo of the repaired area shared.', '/uploads/jobs/job_009_final.jpg', '2026-03-05 14:27:00+05:30'),
  (10, 10, 'note', 'Customer informed about the next service due date.', NULL, '2026-03-12 14:10:00+05:30'),
  (11, 11, 'status_change', 'Job accepted by the workshop and slot confirmed.', NULL, '2026-03-19 14:53:00+05:30'),
  (12, 12, 'note', 'Vehicle received at the workshop, initial inspection started.', NULL, '2026-03-26 14:36:00+05:30'),
  (13, 13, 'image', 'Photo of the worn part shared with the customer.', '/uploads/jobs/job_013_part.jpg', '2026-04-02 14:19:00+05:30'),
  (14, 14, 'note', 'Estimate revised after inspection and sent for approval.', NULL, '2026-04-09 14:02:00+05:30'),
  (15, 15, 'status_change', 'Work in progress, spare parts collected from the store.', NULL, '2026-04-16 14:45:00+05:30'),
  (16, 16, 'image', 'Progress photo uploaded after dismantling.', '/uploads/jobs/job_016_progress.jpg', '2026-04-23 14:28:00+05:30'),
  (17, 17, 'note', 'Road test completed, no abnormal noise observed.', NULL, '2026-04-30 14:11:00+05:30'),
  (18, 18, 'status_change', 'Job marked complete and the vehicle is ready for pickup.', NULL, '2026-05-07 14:54:00+05:30'),
  (19, 19, 'image', 'Final photo of the repaired area shared.', '/uploads/jobs/job_019_final.jpg', '2026-05-14 14:37:00+05:30'),
  (20, 20, 'note', 'Customer informed about the next service due date.', NULL, '2026-05-21 14:20:00+05:30'),
  (21, 21, 'status_change', 'Job accepted by the workshop and slot confirmed.', NULL, '2026-05-28 14:03:00+05:30'),
  (22, 22, 'note', 'Vehicle received at the workshop, initial inspection started.', NULL, '2026-06-04 14:46:00+05:30'),
  (23, 23, 'image', 'Photo of the worn part shared with the customer.', '/uploads/jobs/job_023_part.jpg', '2026-06-11 14:29:00+05:30'),
  (24, 24, 'note', 'Estimate revised after inspection and sent for approval.', NULL, '2026-06-18 14:12:00+05:30'),
  (25, 25, 'status_change', 'Work in progress, spare parts collected from the store.', NULL, '2026-06-25 14:55:00+05:30'),
  (26, 26, 'image', 'Progress photo uploaded after dismantling.', '/uploads/jobs/job_026_progress.jpg', '2026-07-02 14:38:00+05:30'),
  (27, 27, 'note', 'Road test completed, no abnormal noise observed.', NULL, '2026-07-09 14:21:00+05:30'),
  (28, 28, 'status_change', 'Job marked complete and the vehicle is ready for pickup.', NULL, '2026-07-16 14:04:00+05:30'),
  (29, 29, 'image', 'Final photo of the repaired area shared.', '/uploads/jobs/job_029_final.jpg', '2026-07-23 14:47:00+05:30'),
  (30, 30, 'note', 'Customer informed about the next service due date.', NULL, '2026-07-30 14:30:00+05:30');


-- payments ---------------------------------------------------------
-- The mechanic side of the same ledger as am_user.payments.
INSERT INTO payments (id, job_id, mechanic_id, customer_name, amount, method,
                      status, transaction_ref, created_at) VALUES
  (1, 1, 3, 'Aarav Sharma', 8075.0, 'upi', 'paid', 'TXNUPI40007', '2026-01-09 16:11:00+05:30'),
  (2, 2, 7, 'Priya Nair', 3136.0, 'card', 'paid', 'TXNCAR40014', '2026-01-16 16:22:00+05:30'),
  (3, 3, 1, 'Rohan Mehta', 2424.0, 'netbanking', 'paid', 'TXNNET40021', '2026-01-23 16:33:00+05:30'),
  (4, 4, 12, 'Sneha Iyer', 5824.0, 'cash', 'paid', 'TXNCAS40028', '2026-01-30 16:44:00+05:30'),
  (5, 5, 5, 'Vikas Gupta', 4066.0, 'upi', 'paid', 'TXNUPI40035', '2026-02-06 16:55:00+05:30'),
  (6, 6, 3, 'Ananya Rao', 9114.0, 'card', 'paid', 'TXNCAR40042', '2026-02-13 16:06:00+05:30'),
  (7, 7, 18, 'Karthik Menon', 6144.0, 'upi', 'paid', 'TXNUPI40049', '2026-02-20 16:17:00+05:30'),
  (8, 8, 9, 'Divya Joshi', 2871.0, 'netbanking', 'paid', 'TXNNET40056', '2026-02-27 16:28:00+05:30'),
  (9, 9, 1, 'Rahul Verma', 11730.0, 'card', 'failed', 'TXNCAR40063', '2026-03-06 16:39:00+05:30'),
  (10, 10, 22, 'Meera Pillai', 5460.0, 'upi', 'paid', 'TXNUPI40070', '2026-03-13 16:50:00+05:30'),
  (11, 11, 7, 'Siddharth Bose', 7992.0, 'cash', 'paid', 'TXNCAS40077', '2026-03-20 16:01:00+05:30'),
  (12, 12, 14, 'Neha Kulkarni', 1504.0, 'upi', 'paid', 'TXNUPI40084', '2026-03-27 16:12:00+05:30'),
  (13, 13, 2, 'Arjun Desai', 8245.0, 'card', 'paid', 'TXNCAR40091', '2026-04-03 16:23:00+05:30'),
  (14, 14, 25, 'Pooja Reddy', 3200.0, 'upi', 'paid', 'TXNUPI40098', '2026-04-10 16:34:00+05:30'),
  (15, 15, 11, 'Manish Tiwari', 2472.0, 'netbanking', 'paid', 'TXNNET40105', '2026-04-17 16:45:00+05:30'),
  (16, 16, 3, 'Ritu Chauhan', 5936.0, 'upi', 'paid', 'TXNUPI40112', '2026-04-24 16:56:00+05:30'),
  (17, 17, 8, 'Aditya Ghosh', 3496.0, 'card', 'refunded', 'TXNCAR40119', '2026-05-01 16:07:00+05:30'),
  (18, 18, 19, 'Kavya Krishnan', 9310.0, 'cash', 'paid', 'TXNCAS40126', '2026-05-08 16:18:00+05:30'),
  (19, 19, 5, 'Nikhil Bhatt', 6272.0, 'upi', 'paid', 'TXNUPI40133', '2026-05-15 16:29:00+05:30'),
  (20, 20, 27, 'Shreya Sen', 2929.0, 'card', 'paid', 'TXNCAR40140', '2026-05-22 16:40:00+05:30'),
  (21, 21, 13, 'Varun Malhotra', 11960.0, 'netbanking', 'paid', 'TXNNET40147', '2026-05-29 16:51:00+05:30'),
  (22, 22, 1, 'Ishita Banerjee', 5564.0, 'upi', 'paid', 'TXNUPI40154', '2026-06-05 16:02:00+05:30'),
  (23, 23, 30, 'Rajat Kapoor', 6882.0, 'card', 'paid', 'TXNCAR40161', '2026-06-12 16:13:00+05:30'),
  (24, 24, 16, 'Tanvi Shetty', 1536.0, 'upi', 'paid', 'TXNUPI40168', '2026-06-19 16:24:00+05:30'),
  (25, 25, 7, 'Harsh Vardhan', 8415.0, 'cash', 'paid', 'TXNCAS40175', '2026-06-26 16:35:00+05:30'),
  (26, 26, 4, 'Lakshmi Narayan', 3264.0, 'upi', 'pending', 'TXNUPI40182', '2026-07-03 16:46:00+05:30'),
  (27, 27, 21, 'Gaurav Saxena', 2520.0, 'card', 'pending', 'TXNCAR40189', '2026-07-10 16:57:00+05:30'),
  (28, 28, 9, 'Anjali Dubey', 6048.0, 'upi', 'pending', 'TXNUPI40196', '2026-07-17 16:08:00+05:30'),
  (29, 29, 26, 'Sameer Qureshi', 3572.0, 'netbanking', 'pending', 'TXNNET40203', '2026-07-24 16:19:00+05:30'),
  (30, 30, 12, 'Deepa Chandran', 9506.0, 'cash', 'pending', 'TXNCAS40210', '2026-07-31 16:30:00+05:30');


-- reviews ----------------------------------------------------------
-- Identical rows to am_user.reviews so both sides show the same feedback.
INSERT INTO reviews (id, service_request_id, mechanic_id, user_id, user_name,
                     rating, comment, created_at) VALUES
  (1, 1, 3, 1, 'Aarav Sharma', 5, 'Picked up the car on time and explained every line of the bill. Very satisfied.', '2026-01-10 20:37:00+05:30'),
  (2, 2, 7, 2, 'Priya Nair', 4, 'Brake noise is completely gone. Fair pricing and quick turnaround.', '2026-01-17 20:14:00+05:30'),
  (3, 3, 1, 3, 'Rohan Mehta', 3, 'Good work overall, but the car was delivered two hours later than promised.', '2026-01-24 20:51:00+05:30'),
  (4, 4, 12, 4, 'Sneha Iyer', 5, 'Excellent diagnostics. Found a wiring fault two other garages had missed.', '2026-01-31 20:28:00+05:30'),
  (5, 5, 5, 5, 'Vikas Gupta', 5, 'AC is cooling like new again. Would definitely book this mechanic again.', '2026-02-07 20:05:00+05:30'),
  (6, 6, 3, 6, 'Ananya Rao', 4, 'Tyres fitted and balanced properly. Ride quality has improved a lot.', '2026-02-14 20:42:00+05:30'),
  (7, 7, 18, 7, 'Karthik Menon', 5, 'Suspension knock fixed on the first attempt. Clean and professional job.', '2026-02-21 20:19:00+05:30'),
  (8, 8, 9, 8, 'Divya Joshi', 4, 'Reasonable rates and honest advice. Did not push unnecessary replacements.', '2026-02-28 20:56:00+05:30'),
  (9, 9, 1, 9, 'Rahul Verma', 4, 'Clutch feels brand new. Slightly expensive but the quality justifies it.', '2026-03-07 20:33:00+05:30'),
  (10, 10, 22, 10, 'Meera Pillai', 5, 'Service was thorough and the car was returned washed. Great experience.', '2026-03-14 20:10:00+05:30'),
  (11, 11, 7, 11, 'Siddharth Bose', 4, 'Paint match is near perfect. Took an extra day but worth the wait.', '2026-03-21 20:47:00+05:30'),
  (12, 12, 14, 12, 'Neha Kulkarni', 5, 'Alignment sorted the steering pull immediately. Very happy with the result.', '2026-03-28 20:24:00+05:30'),
  (13, 13, 2, 13, 'Arjun Desai', 5, 'Prompt response and transparent estimate shared before starting work.', '2026-04-04 20:01:00+05:30'),
  (14, 14, 25, 14, 'Pooja Reddy', 4, 'Engine runs much smoother now. Mileage has also improved noticeably.', '2026-04-11 20:38:00+05:30'),
  (15, 15, 11, 15, 'Manish Tiwari', 5, 'Battery replaced under warranty without any argument. Smooth process.', '2026-04-18 20:15:00+05:30'),
  (16, 16, 3, 16, 'Ritu Chauhan', 5, 'Courteous staff and a tidy workshop. Kept me updated through the app.', '2026-04-25 20:52:00+05:30'),
  (17, 17, 8, 17, 'Aditya Ghosh', 3, 'Minor oil leak reappeared after a week but they rectified it free of cost.', '2026-05-02 20:29:00+05:30'),
  (18, 18, 19, 18, 'Kavya Krishnan', 5, 'Very knowledgeable mechanic. Walked me through the worn parts personally.', '2026-05-09 20:06:00+05:30'),
  (19, 19, 5, 19, 'Nikhil Bhatt', 4, 'Booking to delivery was seamless. The tracking updates were accurate.', '2026-05-16 20:43:00+05:30'),
  (20, 20, 27, 20, 'Shreya Sen', 5, 'Fixed the flickering dashboard lights that had troubled me for months.', '2026-05-23 20:20:00+05:30'),
  (21, 21, 13, 21, 'Varun Malhotra', 4, 'Fair estimate, no hidden charges, and the invoice matched the quote exactly.', '2026-05-30 20:57:00+05:30'),
  (22, 22, 1, 22, 'Ishita Banerjee', 5, 'Quick periodic service done within the promised three hours. Recommended.', '2026-06-06 20:34:00+05:30'),
  (23, 23, 30, 23, 'Rajat Kapoor', 4, 'Gearbox is much quieter now. Good value for a fairly major repair.', '2026-06-13 20:11:00+05:30'),
  (24, 24, 16, 24, 'Tanvi Shetty', 5, 'Helpful and patient with all my questions. Will use FixMyRide again.', '2026-06-20 20:48:00+05:30'),
  (25, 25, 7, 25, 'Harsh Vardhan', 5, 'Solid workmanship. The car has been running trouble free since the service.', '2026-06-27 20:25:00+05:30'),
  (26, 1, 3, 1, 'Aarav Sharma', 5, 'Second visit for the same car and the quality has stayed consistent.', '2026-07-04 20:02:00+05:30'),
  (27, 2, 7, 2, 'Priya Nair', 4, 'Follow-up service after six months, still very happy with the standard.', '2026-07-11 20:39:00+05:30'),
  (28, 3, 1, 3, 'Rohan Mehta', 5, 'Repeat customer now. Same mechanic, same reliable turnaround.', '2026-07-18 20:16:00+05:30'),
  (29, 4, 12, 4, 'Sneha Iyer', 4, 'Came back for a re-check and they inspected it without charging extra.', '2026-07-25 20:53:00+05:30'),
  (30, 5, 5, 5, 'Vikas Gupta', 5, 'Long term feedback after 5,000 km of driving. The repair has held up well.', '2026-08-01 20:30:00+05:30');


-- notifications ----------------------------------------------------
INSERT INTO notifications (id, recipient_role, recipient_id, title, body, read, created_at) VALUES
  (1, 'mechanic', 3, 'New job assigned', 'Service request FMR-2026-1001 from Aarav Sharma has been assigned to you.', 1, '2026-01-07 09:47:00+05:30'),
  (2, 'mechanic', 7, 'Customer confirmed slot', 'Priya Nair confirmed the 10:00 AM slot for FMR-2026-1002.', 1, '2026-01-14 09:34:00+05:30'),
  (3, 'mechanic', 1, 'Estimate approved', 'Rohan Mehta approved your estimate for FMR-2026-1003.', 1, '2026-01-21 09:21:00+05:30'),
  (4, 'mechanic', 12, 'Job overdue', 'Job FMR-2026-1004 has crossed its estimated completion time.', 1, '2026-01-28 09:08:00+05:30'),
  (5, 'mechanic', 5, 'Payment settled', 'Payout for FMR-2026-1005 has been credited to your account.', 1, '2026-02-04 09:55:00+05:30'),
  (6, 'mechanic', 3, 'New review received', 'Ananya Rao left a review on FMR-2026-1006.', 1, '2026-02-11 09:42:00+05:30'),
  (7, 'mechanic', 18, 'Profile approved', 'Your workshop profile has been approved by the admin team.', 1, '2026-02-18 09:29:00+05:30'),
  (8, 'mechanic', 9, 'Document expiring', 'Your workshop certification is due for renewal next month.', 1, '2026-02-25 09:16:00+05:30'),
  (9, 'mechanic', 1, 'Customer cancelled', 'Rahul Verma cancelled the booking FMR-2026-1009.', 1, '2026-03-04 09:03:00+05:30'),
  (10, 'mechanic', 22, 'Weekly summary', 'Your earnings summary for the week is ready to view.', 1, '2026-03-11 09:50:00+05:30'),
  (11, 'mechanic', 7, 'New job assigned', 'Service request FMR-2026-1011 from Siddharth Bose has been assigned to you.', 1, '2026-03-18 09:37:00+05:30'),
  (12, 'mechanic', 14, 'Customer confirmed slot', 'Neha Kulkarni confirmed the 10:00 AM slot for FMR-2026-1012.', 1, '2026-03-25 09:24:00+05:30'),
  (13, 'mechanic', 2, 'Estimate approved', 'Arjun Desai approved your estimate for FMR-2026-1013.', 1, '2026-04-01 09:11:00+05:30'),
  (14, 'mechanic', 25, 'Job overdue', 'Job FMR-2026-1014 has crossed its estimated completion time.', 1, '2026-04-08 09:58:00+05:30'),
  (15, 'mechanic', 11, 'Payment settled', 'Payout for FMR-2026-1015 has been credited to your account.', 1, '2026-04-15 09:45:00+05:30'),
  (16, 'mechanic', 3, 'New review received', 'Ritu Chauhan left a review on FMR-2026-1016.', 1, '2026-04-22 09:32:00+05:30'),
  (17, 'mechanic', 8, 'Profile approved', 'Your workshop profile has been approved by the admin team.', 1, '2026-04-29 09:19:00+05:30'),
  (18, 'mechanic', 19, 'Document expiring', 'Your workshop certification is due for renewal next month.', 1, '2026-05-06 09:06:00+05:30'),
  (19, 'mechanic', 5, 'Customer cancelled', 'Nikhil Bhatt cancelled the booking FMR-2026-1019.', 1, '2026-05-13 09:53:00+05:30'),
  (20, 'mechanic', 27, 'Weekly summary', 'Your earnings summary for the week is ready to view.', 1, '2026-05-20 09:40:00+05:30'),
  (21, 'mechanic', 13, 'New job assigned', 'Service request FMR-2026-1021 from Varun Malhotra has been assigned to you.', 0, '2026-05-27 09:27:00+05:30'),
  (22, 'mechanic', 1, 'Customer confirmed slot', 'Ishita Banerjee confirmed the 10:00 AM slot for FMR-2026-1022.', 0, '2026-06-03 09:14:00+05:30'),
  (23, 'mechanic', 30, 'Estimate approved', 'Rajat Kapoor approved your estimate for FMR-2026-1023.', 0, '2026-06-10 09:01:00+05:30'),
  (24, 'mechanic', 16, 'Job overdue', 'Job FMR-2026-1024 has crossed its estimated completion time.', 0, '2026-06-17 09:48:00+05:30'),
  (25, 'mechanic', 7, 'Payment settled', 'Payout for FMR-2026-1025 has been credited to your account.', 0, '2026-06-24 09:35:00+05:30'),
  (26, 'mechanic', 4, 'New review received', 'Lakshmi Narayan left a review on FMR-2026-1026.', 0, '2026-07-01 09:22:00+05:30'),
  (27, 'mechanic', 21, 'Profile approved', 'Your workshop profile has been approved by the admin team.', 0, '2026-07-08 09:09:00+05:30'),
  (28, 'mechanic', 9, 'Document expiring', 'Your workshop certification is due for renewal next month.', 0, '2026-07-15 09:56:00+05:30'),
  (29, 'mechanic', 26, 'Customer cancelled', 'Sameer Qureshi cancelled the booking FMR-2026-1029.', 0, '2026-07-22 09:43:00+05:30'),
  (30, 'mechanic', 12, 'Weekly summary', 'Your earnings summary for the week is ready to view.', 0, '2026-07-29 09:30:00+05:30');


-- ---------------------------------------------------------------------
-- 3. RESYNC IDENTITY SEQUENCES
-- ---------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('mechanics','id'),     (SELECT MAX(id) FROM mechanics));
SELECT setval(pg_get_serial_sequence('services','id'),      (SELECT MAX(id) FROM services));
SELECT setval(pg_get_serial_sequence('jobs','id'),          (SELECT MAX(id) FROM jobs));
SELECT setval(pg_get_serial_sequence('job_updates','id'),   (SELECT MAX(id) FROM job_updates));
SELECT setval(pg_get_serial_sequence('payments','id'),      (SELECT MAX(id) FROM payments));
SELECT setval(pg_get_serial_sequence('reviews','id'),       (SELECT MAX(id) FROM reviews));
SELECT setval(pg_get_serial_sequence('notifications','id'), (SELECT MAX(id) FROM notifications));

COMMIT;
