-- =====================================================================
-- FixMyRide - am_user schema and seed data
-- Target database : am_user   (PostgreSQL 18, server "automate")
-- Generated from  : docs/FixMyRide-SRS-HLD-LLD.pdf, section 7.2 (Data design)
--
-- Schema is a faithful port of the LLD tables. SQLite -> PostgreSQL mapping:
--   INTEGER PK AUTOINCREMENT -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--   TEXT                     -> TEXT
--   REAL (money)             -> NUMERIC(10,2)      REAL (rating) -> NUMERIC(2,1)
--   TEXT DEFAULT datetime()  -> TIMESTAMPTZ DEFAULT now()
--   INTEGER 0/1 flags        -> INTEGER (kept as in the LLD, not BOOLEAN)
-- Cross-module columns (mechanic_id in user db, service_request_id in mechanic
-- db, every mirror table in admin db) carry NO foreign key, exactly as the LLD
-- specifies - the three databases stay independently deployable.
--
-- IDs are aligned across all three databases: user #7 is user #7 everywhere,
-- mechanic #12 is mechanic #12 everywhere, and service request #5 is job #5
-- and service_overview #5. This makes the mirrors joinable by hand.
--
-- Contains: users, vehicles, service_requests, payments, issues, notifications, mechanics, reviews
-- Each table is seeded with 30 rows. Password for every seeded principal is
-- "password123" (stored as a real bcrypt hash).
--
-- Run with:
--   psql -U postgres -h localhost -d am_user -f <this file>
-- The script is idempotent: it drops and recreates its own tables.
-- =====================================================================

BEGIN;


-- ---------------------------------------------------------------------
-- 1. SCHEMA
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS reviews, issues, payments, service_requests,
                     vehicles, notifications, mechanics, users CASCADE;

CREATE TABLE users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT        NOT NULL,
    email           TEXT        NOT NULL UNIQUE,
    password_hash   TEXT        NOT NULL,
    phone           TEXT,
    address         TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE vehicles (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    make            TEXT        NOT NULL,
    model           TEXT        NOT NULL,
    year            INTEGER     NOT NULL,
    registration_no TEXT        NOT NULL UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE service_requests (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            INTEGER     NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    vehicle_id         INTEGER     NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    mechanic_id        INTEGER,                     -- cross-module, no FK by design
    category           TEXT        NOT NULL,
    description        TEXT        NOT NULL,
    status             TEXT        NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending','assigned','accepted',
                                         'in_progress','completed','cancelled')),
    scheduled_at       TIMESTAMPTZ,
    price              NUMERIC(10,2),
    booking_ref        TEXT,
    estimated_duration TEXT,
    rated              INTEGER     NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payments (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id INTEGER     NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE,
    user_id            INTEGER     NOT NULL REFERENCES users(id)            ON DELETE CASCADE,
    amount             NUMERIC(10,2) NOT NULL,
    method             TEXT        NOT NULL,
    status             TEXT        NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending','paid','failed','refunded')),
    transaction_ref    TEXT        NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE issues (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            INTEGER     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    service_request_id INTEGER     REFERENCES service_requests(id) ON DELETE SET NULL,
    title              TEXT        NOT NULL,
    description        TEXT        NOT NULL,
    image_path         TEXT,
    status             TEXT        NOT NULL DEFAULT 'open'
                       CHECK (status IN ('open','investigating','resolved','closed')),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_role TEXT        NOT NULL,
    recipient_id   INTEGER     NOT NULL,
    title          TEXT        NOT NULL,
    body           TEXT        NOT NULL,
    read           INTEGER     NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Discovery mirror. id is a plain INTEGER PK (no identity) because the values
-- are assigned by the mechanic module, not generated here.
CREATE TABLE mechanics (
    id              INTEGER PRIMARY KEY,
    name            TEXT,
    specialization  TEXT,
    skills          TEXT,
    workshop_name   TEXT,
    location        TEXT,
    price_from      NUMERIC(10,2),
    rating          NUMERIC(2,1),
    reviews_count   INTEGER     DEFAULT 0,
    available       INTEGER     DEFAULT 1,
    approval_status TEXT        DEFAULT 'approved',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE reviews (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id INTEGER     NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE,
    mechanic_id        INTEGER,
    user_id            INTEGER     NOT NULL,
    user_name          TEXT,
    rating             INTEGER     NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment            TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes (LLD section 7.2.4)
CREATE INDEX idx_vehicles_user     ON vehicles(user_id);
CREATE INDEX idx_services_user     ON service_requests(user_id);
CREATE INDEX idx_payments_user     ON payments(user_id);
CREATE INDEX idx_issues_user       ON issues(user_id);
CREATE INDEX idx_reviews_mechanic  ON reviews(mechanic_id);


-- ---------------------------------------------------------------------
-- 2. SEED DATA (30 rows per table)
-- ---------------------------------------------------------------------

-- users -----------------------------------------------------------
INSERT INTO users (id, name, email, password_hash, phone, address, created_at) VALUES
  (1, 'Aarav Sharma', 'aarav@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9820114455', 'Flat 402, Sunrise Residency, Andheri West, Mumbai 400058', '2025-10-10 11:17:00+05:30'),
  (2, 'Priya Nair', 'priya@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9945228877', '12/A Brigade Gardens, Koramangala, Bengaluru 560034', '2025-10-12 11:34:00+05:30'),
  (3, 'Rohan Mehta', 'rohan@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9871304562', 'B-91 Greater Kailash Part 1, New Delhi 110048', '2025-10-14 11:51:00+05:30'),
  (4, 'Sneha Iyer', 'sneha@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9884451209', 'No. 7 Thiruvalluvar Street, Adyar, Chennai 600020', '2025-10-16 11:08:00+05:30'),
  (5, 'Vikas Gupta', 'vikas@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9313778420', 'H-14 Sector 62, Noida 201309', '2025-10-18 11:25:00+05:30'),
  (6, 'Ananya Rao', 'ananya@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9848012765', 'Plot 33, Jubilee Hills, Hyderabad 500033', '2025-10-20 11:42:00+05:30'),
  (7, 'Karthik Menon', 'karthik@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9995567012', 'Panampilly Nagar, Kochi 682036', '2025-10-22 11:59:00+05:30'),
  (8, 'Divya Joshi', 'divya@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9822045518', 'Lane 5, Koregaon Park, Pune 411001', '2025-10-24 11:16:00+05:30'),
  (9, 'Rahul Verma', 'rahul@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9829116374', 'C-22 Malviya Nagar, Jaipur 302017', '2025-10-26 11:33:00+05:30'),
  (10, 'Meera Pillai', 'meera@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9846702233', 'TC 9/1204 Sasthamangalam, Thiruvananthapuram 695010', '2025-10-28 11:50:00+05:30'),
  (11, 'Siddharth Bose', 'siddharth@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9830559140', '45 Southern Avenue, Kolkata 700029', '2025-10-30 11:07:00+05:30'),
  (12, 'Neha Kulkarni', 'neha@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9767881203', 'Aundh Road, Shivaji Nagar, Pune 411005', '2025-11-01 11:24:00+05:30'),
  (13, 'Arjun Desai', 'arjun@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9825334671', 'Satellite Road, Ahmedabad 380015', '2025-11-03 11:41:00+05:30'),
  (14, 'Pooja Reddy', 'pooja@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9701245538', 'Gachibowli, Hyderabad 500032', '2025-11-05 11:58:00+05:30'),
  (15, 'Manish Tiwari', 'manish@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9335067712', 'Gomti Nagar, Lucknow 226010', '2025-11-07 11:15:00+05:30'),
  (16, 'Ritu Chauhan', 'ritu@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9812440096', 'Sector 17-C, Chandigarh 160017', '2025-11-09 11:32:00+05:30'),
  (17, 'Aditya Ghosh', 'aditya@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9831762204', 'Salt Lake Sector V, Kolkata 700091', '2025-11-11 11:49:00+05:30'),
  (18, 'Kavya Krishnan', 'kavya@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9880453317', 'HSR Layout Sector 2, Bengaluru 560102', '2025-11-13 11:06:00+05:30'),
  (19, 'Nikhil Bhatt', 'nikhil@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9426110583', 'Vastrapur, Ahmedabad 380054', '2025-11-15 11:23:00+05:30'),
  (20, 'Shreya Sen', 'shreya@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9836229140', 'New Town Action Area 1, Kolkata 700156', '2025-11-17 11:40:00+05:30'),
  (21, 'Varun Malhotra', 'varun@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9811337425', 'Vasant Kunj, New Delhi 110070', '2025-11-19 11:57:00+05:30'),
  (22, 'Ishita Banerjee', 'ishita@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9007745612', 'Ballygunge Place, Kolkata 700019', '2025-11-21 11:14:00+05:30'),
  (23, 'Rajat Kapoor', 'rajat@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9910228456', 'DLF Phase 3, Gurugram 122010', '2025-11-23 11:31:00+05:30'),
  (24, 'Tanvi Shetty', 'tanvi@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9820667139', 'Powai, Mumbai 400076', '2025-11-25 11:48:00+05:30'),
  (25, 'Harsh Vardhan', 'harsh@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9450113378', 'Hazratganj, Lucknow 226001', '2025-11-27 11:05:00+05:30'),
  (26, 'Lakshmi Narayan', 'lakshmi@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9840556728', 'T. Nagar, Chennai 600017', '2025-11-29 11:22:00+05:30'),
  (27, 'Gaurav Saxena', 'gaurav@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9755201194', 'Arera Colony, Bhopal 462016', '2025-12-01 11:39:00+05:30'),
  (28, 'Anjali Dubey', 'anjali@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9822774510', 'Civil Lines, Nagpur 440001', '2025-12-03 11:56:00+05:30'),
  (29, 'Sameer Qureshi', 'sameer@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9769334081', 'Bandra East, Mumbai 400051', '2025-12-05 11:13:00+05:30'),
  (30, 'Deepa Chandran', 'deepa@example.com', '$2a$10$32aRxeh3w6zn.ZOzbAIP0O8OU9jPrsTP6xjHhkJqZj3GXxQSjGNZ6', '+91 9847220165', 'Kadavanthra, Kochi 682020', '2025-12-07 11:30:00+05:30');


-- vehicles --------------------------------------------------------
INSERT INTO vehicles (id, user_id, make, model, year, registration_no, created_at) VALUES
  (1, 1, 'Maruti Suzuki', 'Swift', 2019, 'MH12AB1234', '2025-10-12 12:19:00+05:30'),
  (2, 2, 'Hyundai', 'i20', 2021, 'KA05CJ7788', '2025-10-14 12:38:00+05:30'),
  (3, 3, 'Honda', 'City', 2018, 'DL8CAF4501', '2025-10-16 12:57:00+05:30'),
  (4, 4, 'Tata', 'Nexon', 2022, 'TN09BQ3390', '2025-10-18 12:16:00+05:30'),
  (5, 5, 'Mahindra', 'XUV700', 2023, 'UP16DR9012', '2025-10-20 12:35:00+05:30'),
  (6, 6, 'Toyota', 'Innova Crysta', 2020, 'TS08EH5567', '2025-10-22 12:54:00+05:30'),
  (7, 7, 'Kia', 'Seltos', 2021, 'KL07AL2234', '2025-10-24 12:13:00+05:30'),
  (8, 8, 'Renault', 'Kwid', 2017, 'MH14GT8891', '2025-10-26 12:32:00+05:30'),
  (9, 9, 'Volkswagen', 'Polo', 2016, 'RJ14CV6620', '2025-10-28 12:51:00+05:30'),
  (10, 10, 'Skoda', 'Rapid', 2019, 'KL01BM4478', '2025-10-30 12:10:00+05:30'),
  (11, 11, 'MG', 'Hector', 2022, 'WB02AF1150', '2025-11-01 12:29:00+05:30'),
  (12, 12, 'Nissan', 'Magnite', 2021, 'MH12KL3345', '2025-11-03 12:48:00+05:30'),
  (13, 13, 'Jeep', 'Compass', 2020, 'GJ01RN7702', '2025-11-05 12:07:00+05:30'),
  (14, 14, 'Maruti Suzuki', 'Baleno', 2019, 'TS09FA8813', '2025-11-07 12:26:00+05:30'),
  (15, 15, 'Hyundai', 'Creta', 2022, 'UP32EW2298', '2025-11-09 12:45:00+05:30'),
  (16, 16, 'Tata', 'Altroz', 2021, 'CH01BD5540', '2025-11-11 12:04:00+05:30'),
  (17, 17, 'Honda', 'Amaze', 2018, 'WB06GH9931', '2025-11-13 12:23:00+05:30'),
  (18, 18, 'Toyota', 'Glanza', 2020, 'KA51MJ6674', '2025-11-15 12:42:00+05:30'),
  (19, 19, 'Mahindra', 'Thar', 2023, 'GJ05KP1187', '2025-11-17 12:01:00+05:30'),
  (20, 20, 'Kia', 'Sonet', 2021, 'WB24CN4406', '2025-11-19 12:20:00+05:30'),
  (21, 21, 'Maruti Suzuki', 'Ertiga', 2018, 'DL3CBQ7719', '2025-11-21 12:39:00+05:30'),
  (22, 22, 'Hyundai', 'Venue', 2020, 'WB20AR3362', '2025-11-23 12:58:00+05:30'),
  (23, 23, 'Tata', 'Tiago', 2019, 'HR26DK8845', '2025-11-25 12:17:00+05:30'),
  (24, 24, 'Mahindra', 'Scorpio N', 2023, 'MH04FL2270', '2025-11-27 12:36:00+05:30'),
  (25, 25, 'Honda', 'WR-V', 2018, 'UP78GN9903', '2025-11-29 12:55:00+05:30'),
  (26, 26, 'Toyota', 'Fortuner', 2021, 'TN10BZ5528', '2025-12-01 12:14:00+05:30'),
  (27, 27, 'Skoda', 'Slavia', 2022, 'MP04CH1146', '2025-12-03 12:33:00+05:30'),
  (28, 28, 'MG', 'Astor', 2022, 'MH31DV6683', '2025-12-05 12:52:00+05:30'),
  (29, 29, 'Maruti Suzuki', 'Dzire', 2017, 'MH02EJ3307', '2025-12-07 12:11:00+05:30'),
  (30, 30, 'Renault', 'Triber', 2020, 'KL39AT7761', '2025-12-09 12:30:00+05:30');


-- service_requests ------------------------------------------------
-- 25 completed jobs of service history, then 5 still in flight.
INSERT INTO service_requests (id, user_id, vehicle_id, mechanic_id, category, description,
                              status, scheduled_at, price, booking_ref, estimated_duration,
                              rated, created_at, updated_at) VALUES
  (1, 1, 1, 3, 'Engine Repair', 'Rough idling and loss of power above 60 kmph', 'completed', '2026-01-08 11:07:00+05:30', 8075.0, 'FMR-2026-1001', '4 hours', 1, '2026-01-06 09:13:00+05:30', '2026-01-09 16:11:00+05:30'),
  (2, 2, 2, 7, 'Brake Service', 'Squealing noise from the front brakes while braking', 'completed', '2026-01-15 12:14:00+05:30', 3136.0, 'FMR-2026-1002', '2 hours', 1, '2026-01-13 09:26:00+05:30', '2026-01-16 16:22:00+05:30'),
  (3, 3, 3, 1, 'Oil Change', 'Due for scheduled engine oil and filter replacement', 'completed', '2026-01-22 13:21:00+05:30', 2424.0, 'FMR-2026-1003', '1 hour', 1, '2026-01-20 09:39:00+05:30', '2026-01-23 16:33:00+05:30'),
  (4, 4, 4, 12, 'Battery Replacement', 'Car not cranking in the morning, battery is 4 years old', 'completed', '2026-01-29 14:28:00+05:30', 5824.0, 'FMR-2026-1004', '45 minutes', 1, '2026-01-27 09:52:00+05:30', '2026-01-30 16:44:00+05:30'),
  (5, 5, 5, 5, 'AC Service', 'AC blows warm air after 10 minutes of driving', 'completed', '2026-02-05 15:35:00+05:30', 4066.0, 'FMR-2026-1005', '2 hours', 1, '2026-02-03 09:05:00+05:30', '2026-02-06 16:55:00+05:30'),
  (6, 6, 6, 3, 'Tyre Replacement', 'Front two tyres worn below the tread wear indicator', 'completed', '2026-02-12 10:42:00+05:30', 9114.0, 'FMR-2026-1006', '1 hour', 1, '2026-02-10 09:18:00+05:30', '2026-02-13 16:06:00+05:30'),
  (7, 7, 7, 18, 'Suspension Work', 'Knocking sound from rear suspension over speed breakers', 'completed', '2026-02-19 11:49:00+05:30', 6144.0, 'FMR-2026-1007', '3 hours', 1, '2026-02-17 09:31:00+05:30', '2026-02-20 16:17:00+05:30'),
  (8, 8, 8, 9, 'Electrical Diagnostics', 'Dashboard warning lights flickering intermittently', 'completed', '2026-02-26 12:56:00+05:30', 2871.0, 'FMR-2026-1008', '2 hours', 1, '2026-02-24 09:44:00+05:30', '2026-02-27 16:28:00+05:30'),
  (9, 9, 9, 1, 'Clutch Repair', 'Clutch slipping in third and fourth gear', 'completed', '2026-03-05 13:03:00+05:30', 11730.0, 'FMR-2026-1009', '5 hours', 1, '2026-03-03 09:57:00+05:30', '2026-03-06 16:39:00+05:30'),
  (10, 10, 10, 22, 'Periodic Service', '40,000 km scheduled service with full inspection', 'completed', '2026-03-12 14:10:00+05:30', 5460.0, 'FMR-2026-1010', '3 hours', 1, '2026-03-10 09:10:00+05:30', '2026-03-13 16:50:00+05:30'),
  (11, 11, 11, 7, 'Denting and Painting', 'Rear left door dented in a parking incident', 'completed', '2026-03-19 15:17:00+05:30', 7992.0, 'FMR-2026-1011', '2 days', 1, '2026-03-17 09:23:00+05:30', '2026-03-20 16:01:00+05:30'),
  (12, 12, 12, 14, 'Wheel Alignment', 'Steering pulls to the left on straight roads', 'completed', '2026-03-26 10:24:00+05:30', 1504.0, 'FMR-2026-1012', '1 hour', 1, '2026-03-24 09:36:00+05:30', '2026-03-27 16:12:00+05:30'),
  (13, 13, 13, 2, 'Engine Repair', 'Rough idling and loss of power above 60 kmph', 'completed', '2026-04-02 11:31:00+05:30', 8245.0, 'FMR-2026-1013', '4 hours', 1, '2026-03-31 09:49:00+05:30', '2026-04-03 16:23:00+05:30'),
  (14, 14, 14, 25, 'Brake Service', 'Squealing noise from the front brakes while braking', 'completed', '2026-04-09 12:38:00+05:30', 3200.0, 'FMR-2026-1014', '2 hours', 1, '2026-04-07 09:02:00+05:30', '2026-04-10 16:34:00+05:30'),
  (15, 15, 15, 11, 'Oil Change', 'Due for scheduled engine oil and filter replacement', 'completed', '2026-04-16 13:45:00+05:30', 2472.0, 'FMR-2026-1015', '1 hour', 1, '2026-04-14 09:15:00+05:30', '2026-04-17 16:45:00+05:30'),
  (16, 16, 16, 3, 'Battery Replacement', 'Car not cranking in the morning, battery is 4 years old', 'completed', '2026-04-23 14:52:00+05:30', 5936.0, 'FMR-2026-1016', '45 minutes', 1, '2026-04-21 09:28:00+05:30', '2026-04-24 16:56:00+05:30'),
  (17, 17, 17, 8, 'AC Service', 'AC blows warm air after 10 minutes of driving', 'completed', '2026-04-30 15:59:00+05:30', 3496.0, 'FMR-2026-1017', '2 hours', 1, '2026-04-28 09:41:00+05:30', '2026-05-01 16:07:00+05:30'),
  (18, 18, 18, 19, 'Tyre Replacement', 'Front two tyres worn below the tread wear indicator', 'completed', '2026-05-07 10:06:00+05:30', 9310.0, 'FMR-2026-1018', '1 hour', 1, '2026-05-05 09:54:00+05:30', '2026-05-08 16:18:00+05:30'),
  (19, 19, 19, 5, 'Suspension Work', 'Knocking sound from rear suspension over speed breakers', 'completed', '2026-05-14 11:13:00+05:30', 6272.0, 'FMR-2026-1019', '3 hours', 1, '2026-05-12 09:07:00+05:30', '2026-05-15 16:29:00+05:30'),
  (20, 20, 20, 27, 'Electrical Diagnostics', 'Dashboard warning lights flickering intermittently', 'completed', '2026-05-21 12:20:00+05:30', 2929.0, 'FMR-2026-1020', '2 hours', 1, '2026-05-19 09:20:00+05:30', '2026-05-22 16:40:00+05:30'),
  (21, 21, 21, 13, 'Clutch Repair', 'Clutch slipping in third and fourth gear', 'completed', '2026-05-28 13:27:00+05:30', 11960.0, 'FMR-2026-1021', '5 hours', 1, '2026-05-26 09:33:00+05:30', '2026-05-29 16:51:00+05:30'),
  (22, 22, 22, 1, 'Periodic Service', '40,000 km scheduled service with full inspection', 'completed', '2026-06-04 14:34:00+05:30', 5564.0, 'FMR-2026-1022', '3 hours', 1, '2026-06-02 09:46:00+05:30', '2026-06-05 16:02:00+05:30'),
  (23, 23, 23, 30, 'Denting and Painting', 'Rear left door dented in a parking incident', 'completed', '2026-06-11 15:41:00+05:30', 6882.0, 'FMR-2026-1023', '2 days', 1, '2026-06-09 09:59:00+05:30', '2026-06-12 16:13:00+05:30'),
  (24, 24, 24, 16, 'Wheel Alignment', 'Steering pulls to the left on straight roads', 'completed', '2026-06-18 10:48:00+05:30', 1536.0, 'FMR-2026-1024', '1 hour', 1, '2026-06-16 09:12:00+05:30', '2026-06-19 16:24:00+05:30'),
  (25, 25, 25, 7, 'Engine Repair', 'Rough idling and loss of power above 60 kmph', 'completed', '2026-06-25 11:55:00+05:30', 8415.0, 'FMR-2026-1025', '4 hours', 1, '2026-06-23 09:25:00+05:30', '2026-06-26 16:35:00+05:30'),
  (26, 26, 26, 4, 'Brake Service', 'Squealing noise from the front brakes while braking', 'in_progress', '2026-07-02 12:02:00+05:30', 3264.0, 'FMR-2026-1026', '2 hours', 0, '2026-06-30 09:38:00+05:30', '2026-07-03 16:46:00+05:30'),
  (27, 27, 27, 21, 'Oil Change', 'Due for scheduled engine oil and filter replacement', 'in_progress', '2026-07-09 13:09:00+05:30', 2520.0, 'FMR-2026-1027', '1 hour', 0, '2026-07-07 09:51:00+05:30', '2026-07-10 16:57:00+05:30'),
  (28, 28, 28, 9, 'Battery Replacement', 'Car not cranking in the morning, battery is 4 years old', 'accepted', '2026-07-16 14:16:00+05:30', 6048.0, 'FMR-2026-1028', '45 minutes', 0, '2026-07-14 09:04:00+05:30', '2026-07-17 16:08:00+05:30'),
  (29, 29, 29, 26, 'AC Service', 'AC blows warm air after 10 minutes of driving', 'assigned', '2026-07-23 15:23:00+05:30', 3572.0, 'FMR-2026-1029', '2 hours', 0, '2026-07-21 09:17:00+05:30', '2026-07-24 16:19:00+05:30'),
  (30, 30, 30, 12, 'Tyre Replacement', 'Front two tyres worn below the tread wear indicator', 'pending', '2026-07-30 10:30:00+05:30', NULL, 'FMR-2026-1030', '1 hour', 0, '2026-07-28 09:30:00+05:30', '2026-07-31 16:30:00+05:30');


-- payments --------------------------------------------------------
-- Completed requests are paid; the in-flight ones are still pending,
-- and two historical ones show the failed / refunded paths.
INSERT INTO payments (id, service_request_id, user_id, amount, method, status,
                      transaction_ref, created_at) VALUES
  (1, 1, 1, 8075.0, 'upi', 'paid', 'TXNUPI40007', '2026-01-09 16:11:00+05:30'),
  (2, 2, 2, 3136.0, 'card', 'paid', 'TXNCAR40014', '2026-01-16 16:22:00+05:30'),
  (3, 3, 3, 2424.0, 'netbanking', 'paid', 'TXNNET40021', '2026-01-23 16:33:00+05:30'),
  (4, 4, 4, 5824.0, 'cash', 'paid', 'TXNCAS40028', '2026-01-30 16:44:00+05:30'),
  (5, 5, 5, 4066.0, 'upi', 'paid', 'TXNUPI40035', '2026-02-06 16:55:00+05:30'),
  (6, 6, 6, 9114.0, 'card', 'paid', 'TXNCAR40042', '2026-02-13 16:06:00+05:30'),
  (7, 7, 7, 6144.0, 'upi', 'paid', 'TXNUPI40049', '2026-02-20 16:17:00+05:30'),
  (8, 8, 8, 2871.0, 'netbanking', 'paid', 'TXNNET40056', '2026-02-27 16:28:00+05:30'),
  (9, 9, 9, 11730.0, 'card', 'failed', 'TXNCAR40063', '2026-03-06 16:39:00+05:30'),
  (10, 10, 10, 5460.0, 'upi', 'paid', 'TXNUPI40070', '2026-03-13 16:50:00+05:30'),
  (11, 11, 11, 7992.0, 'cash', 'paid', 'TXNCAS40077', '2026-03-20 16:01:00+05:30'),
  (12, 12, 12, 1504.0, 'upi', 'paid', 'TXNUPI40084', '2026-03-27 16:12:00+05:30'),
  (13, 13, 13, 8245.0, 'card', 'paid', 'TXNCAR40091', '2026-04-03 16:23:00+05:30'),
  (14, 14, 14, 3200.0, 'upi', 'paid', 'TXNUPI40098', '2026-04-10 16:34:00+05:30'),
  (15, 15, 15, 2472.0, 'netbanking', 'paid', 'TXNNET40105', '2026-04-17 16:45:00+05:30'),
  (16, 16, 16, 5936.0, 'upi', 'paid', 'TXNUPI40112', '2026-04-24 16:56:00+05:30'),
  (17, 17, 17, 3496.0, 'card', 'refunded', 'TXNCAR40119', '2026-05-01 16:07:00+05:30'),
  (18, 18, 18, 9310.0, 'cash', 'paid', 'TXNCAS40126', '2026-05-08 16:18:00+05:30'),
  (19, 19, 19, 6272.0, 'upi', 'paid', 'TXNUPI40133', '2026-05-15 16:29:00+05:30'),
  (20, 20, 20, 2929.0, 'card', 'paid', 'TXNCAR40140', '2026-05-22 16:40:00+05:30'),
  (21, 21, 21, 11960.0, 'netbanking', 'paid', 'TXNNET40147', '2026-05-29 16:51:00+05:30'),
  (22, 22, 22, 5564.0, 'upi', 'paid', 'TXNUPI40154', '2026-06-05 16:02:00+05:30'),
  (23, 23, 23, 6882.0, 'card', 'paid', 'TXNCAR40161', '2026-06-12 16:13:00+05:30'),
  (24, 24, 24, 1536.0, 'upi', 'paid', 'TXNUPI40168', '2026-06-19 16:24:00+05:30'),
  (25, 25, 25, 8415.0, 'cash', 'paid', 'TXNCAS40175', '2026-06-26 16:35:00+05:30'),
  (26, 26, 26, 3264.0, 'upi', 'pending', 'TXNUPI40182', '2026-07-03 16:46:00+05:30'),
  (27, 27, 27, 2520.0, 'card', 'pending', 'TXNCAR40189', '2026-07-10 16:57:00+05:30'),
  (28, 28, 28, 6048.0, 'upi', 'pending', 'TXNUPI40196', '2026-07-17 16:08:00+05:30'),
  (29, 29, 29, 3572.0, 'netbanking', 'pending', 'TXNNET40203', '2026-07-24 16:19:00+05:30'),
  (30, 30, 30, 9506.0, 'cash', 'pending', 'TXNCAS40210', '2026-07-31 16:30:00+05:30');


-- issues ----------------------------------------------------------
INSERT INTO issues (id, user_id, service_request_id, title, description,
                    image_path, status, created_at) VALUES
  (1, 1, 1, 'Invoice amount higher than the quote', 'The final invoice is 1,200 more than the estimate shared at booking.', '/uploads/issues/issue_001.jpg', 'resolved', '2026-01-11 18:23:00+05:30'),
  (2, 2, 2, 'Mechanic arrived late', 'Scheduled slot was 10:00 but work started only at 12:30.', '/uploads/issues/issue_002.jpg', 'closed', '2026-01-18 18:46:00+05:30'),
  (3, 3, 3, 'Noise returned after service', 'The rattling sound came back three days after the repair.', NULL, 'investigating', '2026-01-25 18:09:00+05:30'),
  (4, 4, 4, 'Wrong part fitted', 'An aftermarket filter was used instead of the OEM part I paid for.', '/uploads/issues/issue_004.jpg', 'resolved', '2026-02-01 18:32:00+05:30'),
  (5, 5, 5, 'Car returned unwashed', 'Complimentary wash mentioned in the package was not done.', '/uploads/issues/issue_005.jpg', 'closed', '2026-02-08 18:55:00+05:30'),
  (6, 6, 6, 'Payment deducted twice', 'UPI was debited twice for the same booking reference.', NULL, 'resolved', '2026-02-15 18:18:00+05:30'),
  (7, 7, 7, 'Scratch on the bonnet', 'A fresh scratch appeared on the bonnet after the workshop visit.', '/uploads/issues/issue_007.jpg', 'investigating', '2026-02-22 18:41:00+05:30'),
  (8, 8, 8, 'AC still not cooling', 'Cooling dropped again within a week of the gas refill.', '/uploads/issues/issue_008.jpg', 'open', '2026-03-01 18:04:00+05:30'),
  (9, 9, 9, 'Delay in delivery', 'Car was promised by Friday evening but delivered on Sunday.', NULL, 'closed', '2026-03-08 18:27:00+05:30'),
  (10, 10, 10, 'Missing floor mat', 'One of the rear floor mats was not returned with the car.', '/uploads/issues/issue_010.jpg', 'resolved', '2026-03-15 18:50:00+05:30'),
  (11, 11, 11, 'Brake noise persists', 'Squealing continues at low speed after the brake job.', '/uploads/issues/issue_011.jpg', 'investigating', '2026-03-22 18:13:00+05:30'),
  (12, 12, 12, 'Estimate not shared', 'Work was started before any written estimate was sent.', NULL, 'closed', '2026-03-29 18:36:00+05:30'),
  (13, 13, 13, 'Battery warranty query', 'Need the warranty card for the battery replaced last month.', '/uploads/issues/issue_013.jpg', 'resolved', '2026-04-05 18:59:00+05:30'),
  (14, 14, 14, 'Rude behaviour at pickup', 'The pickup executive was uncooperative about the delay.', '/uploads/issues/issue_014.jpg', 'closed', '2026-04-12 18:22:00+05:30'),
  (15, 15, 15, 'Oil leak after service', 'A small oil patch appears under the car overnight.', NULL, 'investigating', '2026-04-19 18:45:00+05:30'),
  (16, 16, 16, 'App status not updating', 'Tracking showed in progress even after delivery.', '/uploads/issues/issue_016.jpg', 'resolved', '2026-04-26 18:08:00+05:30'),
  (17, 17, 17, 'Refund not received', 'Refund for the cancelled booking has not been credited.', '/uploads/issues/issue_017.jpg', 'open', '2026-05-03 18:31:00+05:30'),
  (18, 18, 18, 'Alignment still off', 'Steering continues to pull left after the alignment.', NULL, 'investigating', '2026-05-10 18:54:00+05:30'),
  (19, 19, 19, 'Extra labour charge', 'A labour line item was added that was never discussed.', '/uploads/issues/issue_019.jpg', 'resolved', '2026-05-17 18:17:00+05:30'),
  (20, 20, 20, 'Paint shade mismatch', 'The repainted door is a slightly different shade.', '/uploads/issues/issue_020.jpg', 'open', '2026-05-24 18:40:00+05:30'),
  (21, 21, 21, 'Wrong tyre size fitted', 'Fitted tyres are one size narrower than requested.', NULL, 'resolved', '2026-05-31 18:03:00+05:30'),
  (22, 22, 22, 'Service reminder not received', 'No reminder came for the scheduled periodic service.', '/uploads/issues/issue_022.jpg', 'closed', '2026-06-07 18:26:00+05:30'),
  (23, 23, 23, 'Gearbox noise after repair', 'A whining sound appears in second gear after the repair.', '/uploads/issues/issue_023.jpg', 'investigating', '2026-06-14 18:49:00+05:30'),
  (24, 24, 24, 'Interior left dirty', 'Grease marks on the steering wheel and gear knob.', NULL, 'closed', '2026-06-21 18:12:00+05:30'),
  (25, 25, 25, 'Warning light back on', 'The engine check light reappeared after two days.', '/uploads/issues/issue_025.jpg', 'open', '2026-06-28 18:35:00+05:30'),
  (26, 26, 26, 'Duplicate booking created', 'The app created two bookings for the same slot.', '/uploads/issues/issue_026.jpg', 'resolved', '2026-07-05 18:58:00+05:30'),
  (27, 27, 27, 'Spare wheel missing', 'Spare wheel was not put back in the boot after service.', NULL, 'resolved', '2026-07-12 18:21:00+05:30'),
  (28, 28, 28, 'Fuel level dropped', 'Fuel gauge reads noticeably lower than at handover.', '/uploads/issues/issue_028.jpg', 'investigating', '2026-07-19 18:44:00+05:30'),
  (29, 29, 29, 'Invoice not emailed', 'Tax invoice was never delivered to my registered email.', '/uploads/issues/issue_029.jpg', 'closed', '2026-07-26 18:07:00+05:30'),
  (30, 30, 30, 'Follow-up check refused', 'Workshop declined a free re-check within the warranty period.', NULL, 'open', '2026-08-02 18:30:00+05:30');


-- notifications ---------------------------------------------------
INSERT INTO notifications (id, recipient_role, recipient_id, title, body, read, created_at) VALUES
  (1, 'user', 1, 'Booking confirmed', 'Your Engine Repair booking FMR-2026-1001 has been confirmed.', 1, '2026-01-07 08:29:00+05:30'),
  (2, 'user', 2, 'Mechanic assigned', 'Dinesh Kumar has been assigned to booking FMR-2026-1002.', 1, '2026-01-14 08:58:00+05:30'),
  (3, 'user', 3, 'Mechanic on the way', 'Vikram Singh is heading to your location for booking FMR-2026-1003.', 1, '2026-01-21 08:27:00+05:30'),
  (4, 'user', 4, 'Work started', 'Work has started on your vehicle for booking FMR-2026-1004.', 1, '2026-01-28 08:56:00+05:30'),
  (5, 'user', 5, 'Estimate ready', 'The estimate for booking FMR-2026-1005 is ready for your approval.', 1, '2026-02-04 08:25:00+05:30'),
  (6, 'user', 6, 'Job completed', 'Your Tyre Replacement job FMR-2026-1006 is complete. Please collect your vehicle.', 1, '2026-02-11 08:54:00+05:30'),
  (7, 'user', 7, 'Payment received', 'We have received your payment for booking FMR-2026-1007.', 1, '2026-02-18 08:23:00+05:30'),
  (8, 'user', 8, 'Rate your service', 'How was your experience with Ajay Thakur on booking FMR-2026-1008?', 1, '2026-02-25 08:52:00+05:30'),
  (9, 'user', 9, 'Service reminder', 'Your vehicle is due for a periodic service this month.', 1, '2026-03-04 08:21:00+05:30'),
  (10, 'user', 10, 'Issue update', 'Your reported issue for booking FMR-2026-1010 is being investigated.', 1, '2026-03-11 08:50:00+05:30'),
  (11, 'user', 11, 'Booking confirmed', 'Your Denting and Painting booking FMR-2026-1011 has been confirmed.', 1, '2026-03-18 08:19:00+05:30'),
  (12, 'user', 12, 'Mechanic assigned', 'Naveen Reddy has been assigned to booking FMR-2026-1012.', 1, '2026-03-25 08:48:00+05:30'),
  (13, 'user', 13, 'Mechanic on the way', 'Imran Khan is heading to your location for booking FMR-2026-1013.', 1, '2026-04-01 08:17:00+05:30'),
  (14, 'user', 14, 'Work started', 'Work has started on your vehicle for booking FMR-2026-1014.', 1, '2026-04-08 08:46:00+05:30'),
  (15, 'user', 15, 'Estimate ready', 'The estimate for booking FMR-2026-1015 is ready for your approval.', 1, '2026-04-15 08:15:00+05:30'),
  (16, 'user', 16, 'Job completed', 'Your Battery Replacement job FMR-2026-1016 is complete. Please collect your vehicle.', 1, '2026-04-22 08:44:00+05:30'),
  (17, 'user', 17, 'Payment received', 'We have received your payment for booking FMR-2026-1017.', 1, '2026-04-29 08:13:00+05:30'),
  (18, 'user', 18, 'Rate your service', 'How was your experience with Bhaskar Rao on booking FMR-2026-1018?', 1, '2026-05-06 08:42:00+05:30'),
  (19, 'user', 19, 'Service reminder', 'Your vehicle is due for a periodic service this month.', 1, '2026-05-13 08:11:00+05:30'),
  (20, 'user', 20, 'Issue update', 'Your reported issue for booking FMR-2026-1020 is being investigated.', 1, '2026-05-20 08:40:00+05:30'),
  (21, 'user', 21, 'Booking confirmed', 'Your Clutch Repair booking FMR-2026-1021 has been confirmed.', 1, '2026-05-27 08:09:00+05:30'),
  (22, 'user', 22, 'Mechanic assigned', 'Vikram Singh has been assigned to booking FMR-2026-1022.', 1, '2026-06-03 08:38:00+05:30'),
  (23, 'user', 23, 'Mechanic on the way', 'Chetan Bhagwat is heading to your location for booking FMR-2026-1023.', 0, '2026-06-10 08:07:00+05:30'),
  (24, 'user', 24, 'Work started', 'Work has started on your vehicle for booking FMR-2026-1024.', 0, '2026-06-17 08:36:00+05:30'),
  (25, 'user', 25, 'Estimate ready', 'The estimate for booking FMR-2026-1025 is ready for your approval.', 0, '2026-06-24 08:05:00+05:30'),
  (26, 'user', 26, 'Job completed', 'Your Brake Service job FMR-2026-1026 is complete. Please collect your vehicle.', 0, '2026-07-01 08:34:00+05:30'),
  (27, 'user', 27, 'Payment received', 'We have received your payment for booking FMR-2026-1027.', 0, '2026-07-08 08:03:00+05:30'),
  (28, 'user', 28, 'Rate your service', 'How was your experience with Ajay Thakur on booking FMR-2026-1028?', 0, '2026-07-15 08:32:00+05:30'),
  (29, 'user', 29, 'Service reminder', 'Your vehicle is due for a periodic service this month.', 0, '2026-07-22 08:01:00+05:30'),
  (30, 'user', 30, 'Issue update', 'Your reported issue for booking FMR-2026-1030 is being investigated.', 0, '2026-07-29 08:30:00+05:30');


-- mechanics (discovery mirror of the mechanic module) --------------
INSERT INTO mechanics (id, name, specialization, skills, workshop_name, location,
                       price_from, rating, reviews_count, available,
                       approval_status, created_at) VALUES
  (1, 'Vikram Singh', 'Engine Overhaul', 'Engine diagnostics, timing belt, head gasket', 'Singh Auto Works', 'Andheri East, Mumbai', 1800, 4.8, 4, 1, 'approved', '2025-09-10 10:31:00+05:30'),
  (2, 'Imran Khan', 'Brake and Suspension', 'Disc brakes, ABS, shock absorbers', 'Khan Motor Garage', 'Koramangala, Bengaluru', 1200, 4.6, 1, 1, 'approved', '2025-09-12 10:02:00+05:30'),
  (3, 'Suresh Yadav', 'Periodic Service', 'Oil change, filters, general service', 'Yadav Service Point', 'Lajpat Nagar, New Delhi', 900, 4.7, 4, 1, 'approved', '2025-09-14 10:33:00+05:30'),
  (4, 'Ramesh Patel', 'Transmission', 'Clutch, gearbox, CVT service', 'Patel Auto Care', 'Satellite, Ahmedabad', 2200, 4.5, 0, 1, 'approved', '2025-09-16 10:04:00+05:30'),
  (5, 'Balaji Naidu', 'Auto Electricals', 'Wiring, alternator, ECU scan', 'Naidu Electricals', 'Velachery, Chennai', 800, 4.4, 3, 1, 'approved', '2025-09-18 10:35:00+05:30'),
  (6, 'Farhan Sheikh', 'AC Service', 'Compressor, gas refill, cooling coil', 'Sheikh Cool Care', 'Kurla West, Mumbai', 1100, 4.6, 0, 1, 'approved', '2025-09-20 10:06:00+05:30'),
  (7, 'Dinesh Kumar', 'Tyres and Alignment', 'Tyre fitting, balancing, alignment', 'Kumar Tyre House', 'Madhapur, Hyderabad', 700, 4.3, 4, 1, 'approved', '2025-09-22 10:37:00+05:30'),
  (8, 'Prakash Jha', 'Denting and Painting', 'Body repair, spray paint, polish', 'Jha Body Shop', 'Behala, Kolkata', 2500, 4.5, 1, 0, 'approved', '2025-09-24 10:08:00+05:30'),
  (9, 'Ajay Thakur', 'Engine Overhaul', 'Turbo repair, injector cleaning', 'Thakur Motors', 'Hadapsar, Pune', 1900, 4.7, 1, 1, 'approved', '2025-09-26 10:39:00+05:30'),
  (10, 'Mohan Das', 'Periodic Service', 'Multi-brand service, inspection', 'Das Auto Point', 'Edappally, Kochi', 850, 4.4, 0, 1, 'approved', '2025-09-28 10:10:00+05:30'),
  (11, 'Irfan Ali', 'Brake and Suspension', 'Brake pads, strut replacement', 'Ali Auto Garage', 'Okhla, New Delhi', 1150, 4.5, 1, 1, 'approved', '2025-09-30 10:41:00+05:30'),
  (12, 'Sunil Rawat', 'Battery and Starter', 'Battery, starter motor, jump start', 'Rawat Power Works', 'Sector 63, Noida', 600, 4.2, 2, 1, 'approved', '2025-10-02 10:12:00+05:30'),
  (13, 'Kiran Kamble', 'Auto Electricals', 'Headlamps, sensors, fuse box', 'Kamble Electricals', 'Kothrud, Pune', 750, 4.3, 1, 1, 'approved', '2025-10-04 10:43:00+05:30'),
  (14, 'Naveen Reddy', 'Transmission', 'Automatic gearbox, clutch plate', 'Reddy Transmission', 'Kondapur, Hyderabad', 2300, 4.8, 1, 1, 'approved', '2025-10-06 10:14:00+05:30'),
  (15, 'Zubair Ahmed', 'Denting and Painting', 'Dent removal, full body paint', 'Ahmed Auto Body', 'Park Circus, Kolkata', 2400, 4.4, 0, 0, 'approved', '2025-10-08 10:45:00+05:30'),
  (16, 'Santosh Pawar', 'Engine Overhaul', 'Cylinder head, coolant system', 'Pawar Engine Works', 'Wakad, Pune', 2000, 4.6, 1, 1, 'approved', '2025-10-10 10:16:00+05:30'),
  (17, 'Rakesh Yadav', 'Periodic Service', 'Scheduled service, fluid top-up', 'Yadav Car Care', 'Gomti Nagar, Lucknow', 880, 4.5, 0, 1, 'approved', '2025-10-12 10:47:00+05:30'),
  (18, 'Vinod Chauhan', 'Tyres and Alignment', 'Wheel balancing, puncture repair', 'Chauhan Tyres', 'Sector 22, Chandigarh', 680, 4.1, 1, 1, 'approved', '2025-10-14 10:18:00+05:30'),
  (19, 'Bhaskar Rao', 'Brake and Suspension', 'Brake overhaul, suspension bush', 'Rao Auto Service', 'HSR Layout, Bengaluru', 1250, 4.7, 1, 1, 'approved', '2025-10-16 10:49:00+05:30'),
  (20, 'Jitendra Mishra', 'AC Service', 'AC servicing, blower repair', 'Mishra Cool Point', 'MP Nagar, Bhopal', 1050, 4.3, 0, 1, 'approved', '2025-10-18 10:20:00+05:30'),
  (21, 'Salim Ansari', 'Auto Electricals', 'Central locking, power windows', 'Ansari Auto Elec', 'Byculla, Mumbai', 720, 4.4, 0, 1, 'approved', '2025-10-20 10:51:00+05:30'),
  (22, 'Girish Hegde', 'Periodic Service', 'Preventive maintenance, diagnostics', 'Hegde Auto Studio', 'Jayanagar, Bengaluru', 920, 4.9, 1, 1, 'approved', '2025-10-22 10:22:00+05:30'),
  (23, 'Mahesh Solanki', 'Battery and Starter', 'Battery swap, charging system', 'Solanki Battery Hub', 'Maninagar, Ahmedabad', 620, 4.2, 0, 0, 'approved', '2025-10-24 10:53:00+05:30'),
  (24, 'Ravi Shankar', 'Engine Overhaul', 'Piston rings, valve job', 'Shankar Engine Care', 'Guindy, Chennai', 2100, 4.6, 0, 1, 'approved', '2025-10-26 10:24:00+05:30'),
  (25, 'Tushar Gaikwad', 'Denting and Painting', 'Panel beating, alloy refurb', 'Gaikwad Body Works', 'Pimpri, Pune', 2350, 4.5, 1, 1, 'approved', '2025-10-28 10:55:00+05:30'),
  (26, 'Pankaj Bisht', 'Brake and Suspension', 'Brake fluid, coil spring', 'Bisht Auto Garage', 'Sector 45, Gurugram', 1180, 4.4, 0, 1, 'approved', '2025-10-30 10:26:00+05:30'),
  (27, 'Arif Mansoor', 'AC Service', 'Condenser, evaporator cleaning', 'Mansoor Auto Cool', 'Mira Road, Mumbai', 1080, 4.3, 1, 1, 'approved', '2025-11-01 10:57:00+05:30'),
  (28, 'Yogesh Barot', 'Tyres and Alignment', 'Alignment, camber correction', 'Barot Wheel Care', 'Bopal, Ahmedabad', 690, 4.2, 0, 0, 'pending', '2025-11-03 10:28:00+05:30'),
  (29, 'Devendra Rathore', 'Transmission', 'Manual gearbox, differential', 'Rathore Gear Works', 'Vaishali Nagar, Jaipur', 2150, 4.5, 0, 0, 'pending', '2025-11-05 10:59:00+05:30'),
  (30, 'Chetan Bhagwat', 'Periodic Service', 'Full service, road-test check', 'Bhagwat Auto Point', 'Dharampeth, Nagpur', 870, 4.6, 1, 0, 'rejected', '2025-11-07 10:30:00+05:30');


-- reviews ---------------------------------------------------------
-- One review per completed request (25), plus 5 follow-up reviews left
-- by the same customers on their earlier requests after a repeat visit.
INSERT INTO reviews (id, service_request_id, mechanic_id, user_id, user_name,
                     rating, comment, created_at) VALUES
  (1, 1, 3, 1, 'Aarav Sharma', 5, 'Picked up the car on time and explained every line of the bill. Very satisfied.', '2026-01-10 20:37:00+05:30'),
  (2, 2, 7, 2, 'Priya Nair', 4, 'Brake noise is completely gone. Fair pricing and quick turnaround.', '2026-01-17 20:14:00+05:30'),
  (3, 3, 1, 3, 'Rohan Mehta', 3, 'Good work overall, but the car was delivered two hours later than promised.', '2026-01-24 20:51:00+05:30'),
  (4, 4, 12, 4, 'Sneha Iyer', 5, 'Excellent diagnostics. Found a wiring fault two other garages had missed.', '2026-01-31 20:28:00+05:30'),
  (5, 5, 5, 5, 'Vikas Gupta', 5, 'AC is cooling like new again. Would definitely book this mechanic again.', '2026-02-07 20:05:00+05:30'),
  (6, 6, 3, 6, 'Ananya Rao', 4, 'Tyres fitted and balanced properly. Ride quality has improved a lot.', '2026-02-14 20:42:00+05:30'),
  (7, 7, 18, 7, 'Karthik Menon', 5, 'Suspension knock fixed on the first attempt. Clean and professional job.', '2026-02-21 20:19:00+05:30'),
  (8, 8, 9, 8, 'Divya Joshi', 4, 'Reasonable rates and honest advice. Did not push unnecessary replacements.', '2026-02-28 20:56:00+05:30'),
  (9, 9, 1, 9, 'Rahul Verma', 4, 'Clutch feels brand new. Slightly expensive but the quality justifies it.', '2026-03-07 20:33:00+05:30'),
  (10, 10, 22, 10, 'Meera Pillai', 5, 'Service was thorough and the car was returned washed. Great experience.', '2026-03-14 20:10:00+05:30'),
  (11, 11, 7, 11, 'Siddharth Bose', 4, 'Paint match is near perfect. Took an extra day but worth the wait.', '2026-03-21 20:47:00+05:30'),
  (12, 12, 14, 12, 'Neha Kulkarni', 5, 'Alignment sorted the steering pull immediately. Very happy with the result.', '2026-03-28 20:24:00+05:30'),
  (13, 13, 2, 13, 'Arjun Desai', 5, 'Prompt response and transparent estimate shared before starting work.', '2026-04-04 20:01:00+05:30'),
  (14, 14, 25, 14, 'Pooja Reddy', 4, 'Engine runs much smoother now. Mileage has also improved noticeably.', '2026-04-11 20:38:00+05:30'),
  (15, 15, 11, 15, 'Manish Tiwari', 5, 'Battery replaced under warranty without any argument. Smooth process.', '2026-04-18 20:15:00+05:30'),
  (16, 16, 3, 16, 'Ritu Chauhan', 5, 'Courteous staff and a tidy workshop. Kept me updated through the app.', '2026-04-25 20:52:00+05:30'),
  (17, 17, 8, 17, 'Aditya Ghosh', 3, 'Minor oil leak reappeared after a week but they rectified it free of cost.', '2026-05-02 20:29:00+05:30'),
  (18, 18, 19, 18, 'Kavya Krishnan', 5, 'Very knowledgeable mechanic. Walked me through the worn parts personally.', '2026-05-09 20:06:00+05:30'),
  (19, 19, 5, 19, 'Nikhil Bhatt', 4, 'Booking to delivery was seamless. The tracking updates were accurate.', '2026-05-16 20:43:00+05:30'),
  (20, 20, 27, 20, 'Shreya Sen', 5, 'Fixed the flickering dashboard lights that had troubled me for months.', '2026-05-23 20:20:00+05:30'),
  (21, 21, 13, 21, 'Varun Malhotra', 4, 'Fair estimate, no hidden charges, and the invoice matched the quote exactly.', '2026-05-30 20:57:00+05:30'),
  (22, 22, 1, 22, 'Ishita Banerjee', 5, 'Quick periodic service done within the promised three hours. Recommended.', '2026-06-06 20:34:00+05:30'),
  (23, 23, 30, 23, 'Rajat Kapoor', 4, 'Gearbox is much quieter now. Good value for a fairly major repair.', '2026-06-13 20:11:00+05:30'),
  (24, 24, 16, 24, 'Tanvi Shetty', 5, 'Helpful and patient with all my questions. Will use FixMyRide again.', '2026-06-20 20:48:00+05:30'),
  (25, 25, 7, 25, 'Harsh Vardhan', 5, 'Solid workmanship. The car has been running trouble free since the service.', '2026-06-27 20:25:00+05:30'),
  (26, 1, 3, 1, 'Aarav Sharma', 5, 'Second visit for the same car and the quality has stayed consistent.', '2026-07-04 20:02:00+05:30'),
  (27, 2, 7, 2, 'Priya Nair', 4, 'Follow-up service after six months, still very happy with the standard.', '2026-07-11 20:39:00+05:30'),
  (28, 3, 1, 3, 'Rohan Mehta', 5, 'Repeat customer now. Same mechanic, same reliable turnaround.', '2026-07-18 20:16:00+05:30'),
  (29, 4, 12, 4, 'Sneha Iyer', 4, 'Came back for a re-check and they inspected it without charging extra.', '2026-07-25 20:53:00+05:30'),
  (30, 5, 5, 5, 'Vikas Gupta', 5, 'Long term feedback after 5,000 km of driving. The repair has held up well.', '2026-08-01 20:30:00+05:30');


-- ---------------------------------------------------------------------
-- 3. RESYNC IDENTITY SEQUENCES (rows above were inserted with explicit ids)
-- ---------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('users','id'),             (SELECT MAX(id) FROM users));
SELECT setval(pg_get_serial_sequence('vehicles','id'),          (SELECT MAX(id) FROM vehicles));
SELECT setval(pg_get_serial_sequence('service_requests','id'),  (SELECT MAX(id) FROM service_requests));
SELECT setval(pg_get_serial_sequence('payments','id'),          (SELECT MAX(id) FROM payments));
SELECT setval(pg_get_serial_sequence('issues','id'),            (SELECT MAX(id) FROM issues));
SELECT setval(pg_get_serial_sequence('notifications','id'),     (SELECT MAX(id) FROM notifications));
SELECT setval(pg_get_serial_sequence('reviews','id'),           (SELECT MAX(id) FROM reviews));

COMMIT;
