-- =====================================================================
-- FixMyRide - am_user : dynamic multi-vehicle master data
-- Target database : am_user   (PostgreSQL 18, server "automate")
--
-- Purpose
--   Replace the car-only assumption in `vehicles` with a normalized,
--   database-driven taxonomy:
--
--     VEHICLE_TYPE -> VEHICLE_CATEGORY -> VEHICLE_MANUFACTURER
--                  -> VEHICLE_MODEL -> VEHICLE_VARIANT -> VEHICLE_FUEL_TYPE
--
--   Adding a vehicle type, manufacturer, model or variant after this runs is a
--   pure INSERT: both the user web app and the user mobile app pick it up on
--   the next request, with no frontend deployment.
--
-- Safety
--   * ADDITIVE ONLY. Nothing is dropped, nothing existing is renamed.
--   * `vehicles.make` / `.model` are KEPT and stay populated, so the roadside
--     snapshot, service requests, and the mechanic + admin modules are
--     untouched by this change.
--   * Idempotent: safe to run repeatedly (IF NOT EXISTS + ON CONFLICT).
--   * Section 4 back-fills every pre-existing vehicle row onto master records.
--
-- Run with:
--   psql -U postgres -h localhost -d am_user -f docs/am_user_vehicle_master.sql
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. MASTER TABLES
-- ---------------------------------------------------------------------

-- Top of the hierarchy: Two Wheeler, Four Wheeler, Heavy Vehicle, ...
CREATE TABLE IF NOT EXISTS vehicle_types (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL,
    code          TEXT        NOT NULL UNIQUE,
    description   TEXT,
    icon          TEXT,
    display_order INTEGER     NOT NULL DEFAULT 0,
    is_active     INTEGER     NOT NULL DEFAULT 1,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Motorcycle, Scooter, Car, Truck, Tractor, Ambulance, ...
CREATE TABLE IF NOT EXISTS vehicle_categories (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_type_id INTEGER     NOT NULL REFERENCES vehicle_types(id) ON DELETE CASCADE,
    name            TEXT        NOT NULL,
    code            TEXT        NOT NULL UNIQUE,
    description     TEXT,
    icon            TEXT,
    -- True for categories that are electric by definition (E-Rickshaw, E-Bus).
    is_electric     INTEGER     NOT NULL DEFAULT 0,
    display_order   INTEGER     NOT NULL DEFAULT 0,
    is_active       INTEGER     NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Honda, Tata Motors, Royal Enfield, JCB, ... One brand serves many
-- categories, so the category link lives in a join table rather than a column.
CREATE TABLE IF NOT EXISTS vehicle_manufacturers (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL,
    code          TEXT        NOT NULL UNIQUE,
    description   TEXT,
    logo_url      TEXT,
    display_order INTEGER     NOT NULL DEFAULT 0,
    is_active     INTEGER     NOT NULL DEFAULT 1,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vehicle_category_manufacturers (
    vehicle_category_id     INTEGER NOT NULL REFERENCES vehicle_categories(id)    ON DELETE CASCADE,
    vehicle_manufacturer_id INTEGER NOT NULL REFERENCES vehicle_manufacturers(id) ON DELETE CASCADE,
    display_order           INTEGER NOT NULL DEFAULT 0,
    is_active               INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (vehicle_category_id, vehicle_manufacturer_id)
);

-- A model belongs to exactly one brand within one category: "Honda Activa"
-- is a Scooter, "Honda City" is a Car.
CREATE TABLE IF NOT EXISTS vehicle_models (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_manufacturer_id INTEGER     NOT NULL REFERENCES vehicle_manufacturers(id) ON DELETE CASCADE,
    vehicle_category_id     INTEGER     NOT NULL REFERENCES vehicle_categories(id)    ON DELETE CASCADE,
    name                    TEXT        NOT NULL,
    code                    TEXT        NOT NULL,
    description             TEXT,
    icon                    TEXT,
    display_order           INTEGER     NOT NULL DEFAULT 0,
    is_active               INTEGER     NOT NULL DEFAULT 1,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (vehicle_manufacturer_id, vehicle_category_id, code)
);

CREATE TABLE IF NOT EXISTS vehicle_variants (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_model_id INTEGER     NOT NULL REFERENCES vehicle_models(id) ON DELETE CASCADE,
    name             TEXT        NOT NULL,
    code             TEXT        NOT NULL,
    description      TEXT,
    display_order    INTEGER     NOT NULL DEFAULT 0,
    is_active        INTEGER     NOT NULL DEFAULT 1,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (vehicle_model_id, code)
);

-- Fuel / power type. Electric is a first-class row here, not a car flavour.
CREATE TABLE IF NOT EXISTS vehicle_fuel_types (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL,
    code          TEXT        NOT NULL UNIQUE,
    description   TEXT,
    icon          TEXT,
    is_electric   INTEGER     NOT NULL DEFAULT 0,
    display_order INTEGER     NOT NULL DEFAULT 0,
    is_active     INTEGER     NOT NULL DEFAULT 1,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Optional narrowing: which power types a given model is actually sold with.
-- When a model has no rows here the API falls back to every active fuel type,
-- so seeding this table is never a prerequisite for adding a model.
CREATE TABLE IF NOT EXISTS vehicle_model_fuel_types (
    vehicle_model_id     INTEGER NOT NULL REFERENCES vehicle_models(id)     ON DELETE CASCADE,
    vehicle_fuel_type_id INTEGER NOT NULL REFERENCES vehicle_fuel_types(id) ON DELETE CASCADE,
    display_order        INTEGER NOT NULL DEFAULT 0,
    is_active            INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (vehicle_model_id, vehicle_fuel_type_id)
);

-- Registration-number format, configurable per type or per category, so a
-- tractor or an earthmover is never forced through a car-shaped validator.
-- Most specific wins: category rule > type rule > global rule.
CREATE TABLE IF NOT EXISTS vehicle_registration_rules (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_type_id     INTEGER     REFERENCES vehicle_types(id)      ON DELETE CASCADE,
    vehicle_category_id INTEGER     REFERENCES vehicle_categories(id) ON DELETE CASCADE,
    code                TEXT        NOT NULL UNIQUE,
    -- JavaScript/POSIX-compatible regex source, matched case-insensitively.
    pattern             TEXT,
    placeholder         TEXT,
    help_text           TEXT,
    min_length          INTEGER     NOT NULL DEFAULT 4,
    max_length          INTEGER     NOT NULL DEFAULT 20,
    is_required         INTEGER     NOT NULL DEFAULT 1,
    display_order       INTEGER     NOT NULL DEFAULT 0,
    is_active           INTEGER     NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for the dependent-dropdown queries.
CREATE INDEX IF NOT EXISTS idx_vehicle_categories_type   ON vehicle_categories(vehicle_type_id) WHERE is_active = 1;
CREATE INDEX IF NOT EXISTS idx_vehicle_models_mfr        ON vehicle_models(vehicle_manufacturer_id) WHERE is_active = 1;
CREATE INDEX IF NOT EXISTS idx_vehicle_models_category   ON vehicle_models(vehicle_category_id) WHERE is_active = 1;
CREATE INDEX IF NOT EXISTS idx_vehicle_variants_model    ON vehicle_variants(vehicle_model_id) WHERE is_active = 1;
CREATE INDEX IF NOT EXISTS idx_vehicle_cat_mfr_category  ON vehicle_category_manufacturers(vehicle_category_id);
-- Case-insensitive prefix/substring search over the two large tables.
CREATE INDEX IF NOT EXISTS idx_vehicle_models_name_lower ON vehicle_models(lower(name));
CREATE INDEX IF NOT EXISTS idx_vehicle_mfr_name_lower    ON vehicle_manufacturers(lower(name));


-- ---------------------------------------------------------------------
-- 2. EXTEND `vehicles` (additive — existing columns untouched)
-- ---------------------------------------------------------------------
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS vehicle_type_id         INTEGER REFERENCES vehicle_types(id)         ON DELETE SET NULL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS vehicle_category_id     INTEGER REFERENCES vehicle_categories(id)    ON DELETE SET NULL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS vehicle_manufacturer_id INTEGER REFERENCES vehicle_manufacturers(id) ON DELETE SET NULL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS vehicle_model_id        INTEGER REFERENCES vehicle_models(id)        ON DELETE SET NULL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS vehicle_variant_id      INTEGER REFERENCES vehicle_variants(id)      ON DELETE SET NULL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS vehicle_fuel_type_id    INTEGER REFERENCES vehicle_fuel_types(id)    ON DELETE SET NULL;
-- Free text captured only when the user picks the "Other / Not listed" option.
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS custom_manufacturer TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS custom_model        TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS custom_variant      TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS nickname            TEXT;
-- Soft delete. service_requests.vehicle_id cascades, so a vehicle with history
-- is archived rather than removed; the user's bookings survive either way.
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS is_active  INTEGER     NOT NULL DEFAULT 1;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_vehicles_user_active ON vehicles(user_id) WHERE is_active = 1;


-- ---------------------------------------------------------------------
-- 3. SEED MASTER DATA
--    Every insert is keyed on `code`, so re-running refreshes labels and
--    ordering without creating duplicates or disturbing user references.
-- ---------------------------------------------------------------------

-- 3.1 Vehicle types --------------------------------------------------
INSERT INTO vehicle_types (name, code, description, icon, display_order) VALUES
  ('Two Wheeler',              'two_wheeler',   'Motorcycles, scooters and their electric equivalents', '🏍️', 10),
  ('Three Wheeler',            'three_wheeler', 'Auto rickshaws and three-wheeled goods carriers',      '🛺', 20),
  ('Four Wheeler',             'four_wheeler',  'Cars, SUVs, vans and pickups',                          '🚗', 30),
  ('Commercial Vehicle',       'commercial',    'Light commercial vehicles used to move goods',          '🚐', 40),
  ('Heavy Vehicle',            'heavy',         'Trucks, buses and other heavy commercial vehicles',     '🚚', 50),
  ('Agricultural & Off-Road',  'agricultural',  'Tractors, harvesters and construction machinery',       '🚜', 60),
  ('Emergency & Special',      'emergency',     'Ambulances, fire trucks and special-purpose vehicles',  '🚑', 70),
  ('Other',                    'other_type',    'Anything not covered by the categories above',          '➕', 999)
ON CONFLICT (code) DO UPDATE
  SET name = EXCLUDED.name, description = EXCLUDED.description,
      icon = EXCLUDED.icon, display_order = EXCLUDED.display_order,
      is_active = 1, updated_at = now();

-- 3.2 Vehicle categories ---------------------------------------------
INSERT INTO vehicle_categories (vehicle_type_id, name, code, description, icon, is_electric, display_order)
SELECT t.id, c.name, c.code, c.description, c.icon, c.is_electric, c.display_order
FROM (VALUES
  -- Two wheeler
  ('two_wheeler',  'Motorcycle',                 'motorcycle',         'Geared and non-geared bikes',              '🏍️', 0, 10),
  ('two_wheeler',  'Scooter',                    'scooter',            'Automatic scooters and mopeds',            '🛵', 0, 20),
  ('two_wheeler',  'Electric Bike',              'electric_bike',      'Battery-powered motorcycles',              '⚡', 1, 30),
  ('two_wheeler',  'Electric Scooter',           'electric_scooter',   'Battery-powered scooters',                 '⚡', 1, 40),
  ('two_wheeler',  'Moped',                      'moped',              'Low-capacity utility two wheelers',        '🛵', 0, 50),
  -- Three wheeler
  ('three_wheeler','Auto Rickshaw',              'auto_rickshaw',      'Passenger three wheelers',                 '🛺', 0, 10),
  ('three_wheeler','Electric Three Wheeler',     'electric_3w',        'E-rickshaws and electric loaders',         '⚡', 1, 20),
  ('three_wheeler','Three Wheeler Goods Carrier','three_wheeler_goods','Cargo three wheelers',                     '🛺', 0, 30),
  -- Four wheeler
  ('four_wheeler', 'Car',                        'car',                'Hatchbacks and sedans',                    '🚗', 0, 10),
  ('four_wheeler', 'SUV',                        'suv',                'Sport utility and crossover vehicles',     '🚙', 0, 20),
  ('four_wheeler', 'Electric Car',               'electric_car',       'Battery-electric cars and SUVs',           '⚡', 1, 30),
  ('four_wheeler', 'Taxi / Commercial Car',      'taxi',               'Cars registered for commercial use',       '🚕', 0, 40),
  ('four_wheeler', 'Van',                        'van',                'Passenger and cargo vans',                 '🚐', 0, 50),
  ('four_wheeler', 'Pickup Truck',               'pickup',             'Open-bed light utility trucks',            '🛻', 0, 60),
  -- Commercial
  ('commercial',   'Mini Truck',                 'mini_truck',         'Sub-2 tonne goods carriers',               '🚚', 0, 10),
  ('commercial',   'Tempo / Mini Van',           'tempo',              'Tempo travellers and mini vans',           '🚐', 0, 20),
  ('commercial',   'Electric Commercial Vehicle','electric_lcv',       'Battery-electric goods and people movers', '⚡', 1, 30),
  -- Heavy
  ('heavy',        'Truck / HCV',                'truck',              'Heavy goods trucks and trailers',          '🚛', 0, 10),
  ('heavy',        'Bus',                        'bus',                'Passenger buses and coaches',              '🚌', 0, 20),
  ('heavy',        'School Bus',                 'school_bus',         'Buses registered for school transport',    '🚌', 0, 30),
  ('heavy',        'Electric Bus',               'electric_bus',       'Battery-electric buses',                   '⚡', 1, 40),
  -- Agricultural & off-road
  ('agricultural', 'Tractor',                    'tractor',            'Farm tractors',                            '🚜', 0, 10),
  ('agricultural', 'Tractor with Trailer',       'tractor_trailer',    'Tractor and trailer combinations',         '🚜', 0, 20),
  ('agricultural', 'Agricultural Vehicle',       'agri_vehicle',       'Harvesters, tillers and farm machinery',   '🌾', 0, 30),
  ('agricultural', 'Construction Vehicle',       'construction',       'Concrete mixers, cranes and site vehicles','🏗️', 0, 40),
  ('agricultural', 'Earthmoving Vehicle',        'earthmoving',        'Excavators, loaders and backhoes',         '🏗️', 0, 50),
  -- Emergency & special
  ('emergency',    'Ambulance',                  'ambulance',          'Patient transport and ICU vehicles',       '🚑', 0, 10),
  ('emergency',    'Fire Truck',                 'fire_truck',         'Fire tenders and rescue vehicles',         '🚒', 0, 20),
  -- Other
  ('other_type',   'Other Vehicle',              'other_category',     'Tell us about it while adding the vehicle','➕', 0, 999)
) AS c(type_code, name, code, description, icon, is_electric, display_order)
JOIN vehicle_types t ON t.code = c.type_code
ON CONFLICT (code) DO UPDATE
  SET vehicle_type_id = EXCLUDED.vehicle_type_id, name = EXCLUDED.name,
      description = EXCLUDED.description, icon = EXCLUDED.icon,
      is_electric = EXCLUDED.is_electric, display_order = EXCLUDED.display_order,
      is_active = 1, updated_at = now();

-- 3.3 Fuel / power types ---------------------------------------------
INSERT INTO vehicle_fuel_types (name, code, description, icon, is_electric, display_order) VALUES
  ('Petrol',         'petrol',    'Standard petrol engine',                  '⛽', 0, 10),
  ('Diesel',         'diesel',    'Standard diesel engine',                  '⛽', 0, 20),
  ('CNG',            'cng',       'Compressed natural gas',                  '💨', 0, 30),
  ('LPG',            'lpg',       'Liquefied petroleum gas',                 '💨', 0, 40),
  ('Electric',       'electric',  'Fully battery-electric',                  '⚡', 1, 50),
  ('Hybrid',         'hybrid',    'Self-charging petrol/electric hybrid',    '🔋', 0, 60),
  ('Plug-in Hybrid', 'phev',      'Externally charged hybrid',               '🔌', 1, 70),
  ('Hydrogen',       'hydrogen',  'Hydrogen fuel cell',                      '🧪', 0, 80),
  ('Other',          'other_fuel','Anything else — tell us in the notes',    '➕', 0, 999)
ON CONFLICT (code) DO UPDATE
  SET name = EXCLUDED.name, description = EXCLUDED.description, icon = EXCLUDED.icon,
      is_electric = EXCLUDED.is_electric, display_order = EXCLUDED.display_order,
      is_active = 1, updated_at = now();

-- 3.4 Manufacturers ---------------------------------------------------
INSERT INTO vehicle_manufacturers (name, code, display_order) VALUES
  -- Cars / SUVs
  ('Maruti Suzuki',   'maruti_suzuki',  10),
  ('Hyundai',         'hyundai',        20),
  ('Tata Motors',     'tata_motors',    30),
  ('Mahindra',        'mahindra',       40),
  ('Toyota',          'toyota',         50),
  ('Honda',           'honda',          60),
  ('Kia',             'kia',            70),
  ('Renault',         'renault',        80),
  ('Volkswagen',      'volkswagen',     90),
  ('Skoda',           'skoda',         100),
  ('MG Motor',        'mg_motor',      110),
  ('Nissan',          'nissan',        120),
  ('Jeep',            'jeep',          130),
  ('Ford',            'ford',          140),
  ('BMW',             'bmw',           150),
  ('Mercedes-Benz',   'mercedes_benz', 160),
  ('Audi',            'audi',          170),
  ('Tesla',           'tesla',         180),
  ('BYD',             'byd',           190),
  -- Two wheelers
  ('Hero MotoCorp',   'hero',          200),
  ('Bajaj',           'bajaj',         210),
  ('TVS',             'tvs',           220),
  ('Royal Enfield',   'royal_enfield', 230),
  ('Yamaha',          'yamaha',        240),
  ('Suzuki',          'suzuki',        250),
  ('KTM',             'ktm',           260),
  ('Jawa',            'jawa',          270),
  ('Ola Electric',    'ola_electric',  280),
  ('Ather Energy',    'ather',         290),
  ('Ampere',          'ampere',        300),
  ('Revolt Motors',   'revolt',        310),
  -- Three wheelers
  ('Piaggio',         'piaggio',       320),
  ('Atul Auto',       'atul_auto',     330),
  ('YC Electric',     'yc_electric',   340),
  -- Heavy / commercial
  ('Ashok Leyland',   'ashok_leyland', 350),
  ('Eicher',          'eicher',        360),
  ('BharatBenz',      'bharatbenz',    370),
  ('Volvo',           'volvo',         380),
  ('Force Motors',    'force_motors',  390),
  ('SML Isuzu',       'sml_isuzu',     400),
  ('Isuzu',           'isuzu',         410),
  -- Agricultural
  ('Sonalika',        'sonalika',      420),
  ('John Deere',      'john_deere',    430),
  ('Massey Ferguson', 'massey',        440),
  ('New Holland',     'new_holland',   450),
  ('Escorts Kubota',  'escorts',       460),
  ('Swaraj',          'swaraj',        470),
  ('Kubota',          'kubota',        480),
  -- Construction / earthmoving
  ('JCB',             'jcb',           490),
  ('Caterpillar',     'caterpillar',   500),
  ('Komatsu',         'komatsu',       510),
  ('Tata Hitachi',    'tata_hitachi',  520),
  ('ACE',             'ace',           530)
ON CONFLICT (code) DO UPDATE
  SET name = EXCLUDED.name, display_order = EXCLUDED.display_order,
      is_active = 1, updated_at = now();

-- 3.5 Models ----------------------------------------------------------
-- (manufacturer_code, category_code, model name). `code` is derived from the
-- name so a later insert only needs the three human-readable values.
INSERT INTO vehicle_models (vehicle_manufacturer_id, vehicle_category_id, name, code, display_order)
SELECT mf.id, ct.id, m.name,
       regexp_replace(lower(m.name), '[^a-z0-9]+', '_', 'g'),
       row_number() OVER (PARTITION BY mf.id, ct.id ORDER BY m.name) * 10
FROM (VALUES
  -- ── Cars ──
  ('maruti_suzuki','car','Swift'), ('maruti_suzuki','car','Baleno'), ('maruti_suzuki','car','Dzire'),
  ('maruti_suzuki','car','Alto K10'), ('maruti_suzuki','car','WagonR'), ('maruti_suzuki','car','Celerio'),
  ('maruti_suzuki','car','Ciaz'), ('maruti_suzuki','car','Ignis'),
  ('maruti_suzuki','suv','Ertiga'), ('maruti_suzuki','suv','Brezza'), ('maruti_suzuki','suv','Grand Vitara'),
  ('maruti_suzuki','suv','Fronx'), ('maruti_suzuki','suv','Jimny'), ('maruti_suzuki','suv','XL6'),
  ('hyundai','car','i20'), ('hyundai','car','Grand i10 Nios'), ('hyundai','car','Aura'),
  ('hyundai','car','Verna'), ('hyundai','car','Elantra'),
  ('hyundai','suv','Creta'), ('hyundai','suv','Venue'), ('hyundai','suv','Alcazar'),
  ('hyundai','suv','Tucson'), ('hyundai','suv','Exter'),
  ('hyundai','electric_car','Ioniq 5'), ('hyundai','electric_car','Kona Electric'),
  ('tata_motors','car','Tiago'), ('tata_motors','car','Altroz'), ('tata_motors','car','Tigor'),
  ('tata_motors','suv','Nexon'), ('tata_motors','suv','Punch'), ('tata_motors','suv','Harrier'),
  ('tata_motors','suv','Safari'), ('tata_motors','suv','Curvv'),
  ('tata_motors','electric_car','Nexon EV'), ('tata_motors','electric_car','Tiago EV'),
  ('tata_motors','electric_car','Punch EV'), ('tata_motors','electric_car','Tigor EV'),
  ('mahindra','suv','XUV700'), ('mahindra','suv','Scorpio N'), ('mahindra','suv','Scorpio Classic'),
  ('mahindra','suv','Thar'), ('mahindra','suv','Bolero'), ('mahindra','suv','XUV300'), ('mahindra','suv','Marazzo'),
  ('mahindra','electric_car','XUV400 EV'), ('mahindra','electric_car','BE 6'), ('mahindra','electric_car','XEV 9e'),
  ('toyota','car','Glanza'), ('toyota','car','Camry'),
  ('toyota','suv','Innova Crysta'), ('toyota','suv','Innova Hycross'), ('toyota','suv','Fortuner'),
  ('toyota','suv','Urban Cruiser Hyryder'), ('toyota','suv','Rumion'),
  ('honda','car','City'), ('honda','car','Amaze'), ('honda','car','Jazz'),
  ('honda','suv','WR-V'), ('honda','suv','Elevate'),
  ('kia','suv','Seltos'), ('kia','suv','Sonet'), ('kia','suv','Carens'), ('kia','suv','Syros'),
  ('kia','electric_car','EV6'), ('kia','electric_car','EV9'),
  ('renault','car','Kwid'), ('renault','suv','Triber'), ('renault','suv','Kiger'), ('renault','suv','Duster'),
  ('volkswagen','car','Polo'), ('volkswagen','car','Virtus'), ('volkswagen','suv','Taigun'), ('volkswagen','suv','Tiguan'),
  ('skoda','car','Rapid'), ('skoda','car','Slavia'), ('skoda','car','Octavia'),
  ('skoda','suv','Kushaq'), ('skoda','suv','Kodiaq'),
  ('mg_motor','suv','Hector'), ('mg_motor','suv','Astor'), ('mg_motor','suv','Gloster'),
  ('mg_motor','electric_car','ZS EV'), ('mg_motor','electric_car','Comet EV'), ('mg_motor','electric_car','Windsor EV'),
  ('nissan','suv','Magnite'), ('nissan','suv','Kicks'),
  ('jeep','suv','Compass'), ('jeep','suv','Meridian'), ('jeep','suv','Wrangler'),
  ('ford','car','Figo'), ('ford','suv','EcoSport'), ('ford','suv','Endeavour'),
  ('bmw','car','3 Series'), ('bmw','car','5 Series'), ('bmw','suv','X1'), ('bmw','suv','X5'), ('bmw','electric_car','i4'),
  ('mercedes_benz','car','C-Class'), ('mercedes_benz','car','E-Class'), ('mercedes_benz','suv','GLC'), ('mercedes_benz','electric_car','EQS'),
  ('audi','car','A4'), ('audi','suv','Q3'), ('audi','suv','Q5'), ('audi','electric_car','e-tron'),
  ('tesla','electric_car','Model 3'), ('tesla','electric_car','Model Y'),
  ('byd','electric_car','Atto 3'), ('byd','electric_car','Seal'), ('byd','electric_car','e6'),
  -- ── Motorcycles ──
  ('hero','motorcycle','Splendor Plus'), ('hero','motorcycle','HF Deluxe'), ('hero','motorcycle','Passion Pro'),
  ('hero','motorcycle','Glamour'), ('hero','motorcycle','Xtreme 125R'), ('hero','motorcycle','Xpulse 200'),
  ('honda','motorcycle','Shine'), ('honda','motorcycle','SP 125'), ('honda','motorcycle','Unicorn'),
  ('honda','motorcycle','Hornet 2.0'), ('honda','motorcycle','CB350'),
  ('bajaj','motorcycle','Pulsar 150'), ('bajaj','motorcycle','Pulsar NS200'), ('bajaj','motorcycle','Platina'),
  ('bajaj','motorcycle','CT 100'), ('bajaj','motorcycle','Dominar 400'), ('bajaj','motorcycle','Avenger 220'),
  ('tvs','motorcycle','Apache RTR 160'), ('tvs','motorcycle','Apache RTR 200 4V'), ('tvs','motorcycle','Raider 125'),
  ('tvs','motorcycle','Star City Plus'), ('tvs','motorcycle','Ronin'),
  ('royal_enfield','motorcycle','Classic 350'), ('royal_enfield','motorcycle','Hunter 350'),
  ('royal_enfield','motorcycle','Bullet 350'), ('royal_enfield','motorcycle','Meteor 350'),
  ('royal_enfield','motorcycle','Himalayan'), ('royal_enfield','motorcycle','Continental GT 650'),
  ('yamaha','motorcycle','FZ-S'), ('yamaha','motorcycle','MT-15'), ('yamaha','motorcycle','R15'),
  ('suzuki','motorcycle','Gixxer'), ('suzuki','motorcycle','Gixxer SF 250'),
  ('ktm','motorcycle','Duke 200'), ('ktm','motorcycle','Duke 390'), ('ktm','motorcycle','RC 390'),
  ('jawa','motorcycle','Jawa 42'), ('jawa','motorcycle','Perak'),
  -- ── Scooters ──
  ('honda','scooter','Activa 6G'), ('honda','scooter','Activa 125'), ('honda','scooter','Dio'),
  ('tvs','scooter','Jupiter'), ('tvs','scooter','Ntorq 125'), ('tvs','scooter','Pep Plus'),
  ('suzuki','scooter','Access 125'), ('suzuki','scooter','Burgman Street'),
  ('hero','scooter','Pleasure Plus'), ('hero','scooter','Destini 125'), ('hero','scooter','Maestro Edge'),
  ('yamaha','scooter','Fascino 125'), ('yamaha','scooter','RayZR 125'),
  ('bajaj','scooter','Chetak Classic'),
  -- ── Mopeds ──
  ('tvs','moped','XL100'), ('tvs','moped','XL100 Heavy Duty'),
  -- ── Electric two wheelers ──
  ('ola_electric','electric_scooter','S1 Pro'), ('ola_electric','electric_scooter','S1 Air'), ('ola_electric','electric_scooter','S1 X'),
  ('ather','electric_scooter','450X'), ('ather','electric_scooter','450S'), ('ather','electric_scooter','Rizta'),
  ('tvs','electric_scooter','iQube'), ('bajaj','electric_scooter','Chetak Electric'),
  ('ampere','electric_scooter','Magnus EX'), ('ampere','electric_scooter','Primus'),
  ('hero','electric_scooter','Vida V1'),
  ('revolt','electric_bike','RV400'), ('revolt','electric_bike','RV1'),
  ('ola_electric','electric_bike','Roadster X'),
  -- ── Three wheelers ──
  ('bajaj','auto_rickshaw','RE Compact'), ('bajaj','auto_rickshaw','Maxima C'),
  ('piaggio','auto_rickshaw','Ape City'), ('piaggio','auto_rickshaw','Ape Xtra'),
  ('atul_auto','auto_rickshaw','Rik'), ('atul_auto','auto_rickshaw','Gem Paxx'),
  ('tvs','auto_rickshaw','King Duramax'),
  ('mahindra','auto_rickshaw','Alfa Passenger'),
  ('yc_electric','electric_3w','Yatri Super'), ('yc_electric','electric_3w','Deluxe'),
  ('mahindra','electric_3w','Treo'), ('mahindra','electric_3w','e-Alfa Mini'),
  ('piaggio','electric_3w','Ape E-City'),
  ('bajaj','three_wheeler_goods','Maxima Cargo'), ('piaggio','three_wheeler_goods','Ape Xtra LDX'),
  ('mahindra','three_wheeler_goods','Jeeto'), ('atul_auto','three_wheeler_goods','Shakti Cargo'),
  -- ── Vans / pickups ──
  ('maruti_suzuki','van','Eeco'), ('maruti_suzuki','van','Omni'),
  ('force_motors','van','Traveller'), ('force_motors','van','Urbania'),
  ('toyota','van','HiAce'),
  ('mahindra','pickup','Bolero Pik-Up'), ('mahindra','pickup','Supro Maxitruck'),
  ('tata_motors','pickup','Intra V30'), ('tata_motors','pickup','Yodha'),
  ('isuzu','pickup','D-Max'), ('toyota','pickup','Hilux'),
  -- ── Commercial ──
  ('tata_motors','mini_truck','Ace Gold'), ('tata_motors','mini_truck','Intra V10'),
  ('mahindra','mini_truck','Jeeto Plus'), ('mahindra','mini_truck','Supro Profit Truck'),
  ('ashok_leyland','mini_truck','Dost'), ('ashok_leyland','mini_truck','Bada Dost'),
  ('force_motors','tempo','Traveller 3350'), ('tata_motors','tempo','Winger'),
  ('mahindra','tempo','Supro Van'),
  ('tata_motors','electric_lcv','Ace EV'), ('mahindra','electric_lcv','Zor Grand'),
  ('ashok_leyland','electric_lcv','Dost EV'),
  -- ── Heavy ──
  ('tata_motors','truck','LPT 1613'), ('tata_motors','truck','Signa 4825'), ('tata_motors','truck','Prima 5530'),
  ('ashok_leyland','truck','Ecomet 1215'), ('ashok_leyland','truck','AVTR 4825'),
  ('eicher','truck','Pro 2049'), ('eicher','truck','Pro 6055'),
  ('bharatbenz','truck','1617R'), ('bharatbenz','truck','2823C'),
  ('volvo','truck','FM 420'), ('sml_isuzu','truck','Sartaj GS'),
  ('tata_motors','bus','Starbus'), ('tata_motors','bus','Magna'),
  ('ashok_leyland','bus','Viking'), ('ashok_leyland','bus','Sunshine'),
  ('eicher','bus','Skyline Pro'), ('volvo','bus','9600'),
  ('tata_motors','school_bus','Starbus School'), ('ashok_leyland','school_bus','Sunshine School'),
  ('eicher','school_bus','Skyline School'), ('force_motors','school_bus','Traveller School'),
  ('tata_motors','electric_bus','Starbus EV'), ('ashok_leyland','electric_bus','Circuit S'),
  ('byd','electric_bus','K9'),
  -- ── Agricultural ──
  ('mahindra','tractor','575 DI'), ('mahindra','tractor','JIVO 245 DI'), ('mahindra','tractor','Arjun Novo 605'),
  ('sonalika','tractor','DI 745 III'), ('sonalika','tractor','Tiger DI 55'),
  ('john_deere','tractor','5050 D'), ('john_deere','tractor','5310'),
  ('massey','tractor','1035 DI'), ('massey','tractor','241 DI'),
  ('new_holland','tractor','3600-2 TX'), ('new_holland','tractor','Excel 4710'),
  ('escorts','tractor','Powertrac Euro 50'), ('swaraj','tractor','744 FE'), ('swaraj','tractor','963 FE'),
  ('eicher','tractor','380'), ('kubota','tractor','MU4501'),
  ('mahindra','tractor_trailer','575 DI with Trailer'), ('swaraj','tractor_trailer','744 FE with Trailer'),
  ('john_deere','agri_vehicle','W70 Harvester'), ('new_holland','agri_vehicle','TC5.30 Harvester'),
  ('kubota','agri_vehicle','Harvester DC-68G'), ('mahindra','agri_vehicle','Arjun Harvester'),
  -- ── Construction / earthmoving ──
  ('jcb','construction','3DX Backhoe Loader'), ('jcb','construction','430ZX Wheeled Loader'),
  ('ace','construction','NX 100 Crane'), ('caterpillar','construction','424B Backhoe'),
  ('jcb','earthmoving','JS 205 Excavator'), ('jcb','earthmoving','NXT 140 Excavator'),
  ('tata_hitachi','earthmoving','EX 210LC'), ('tata_hitachi','earthmoving','Shinrai Backhoe'),
  ('komatsu','earthmoving','PC210 Excavator'), ('caterpillar','earthmoving','320 Excavator'),
  -- ── Emergency ──
  ('force_motors','ambulance','Traveller Ambulance'), ('mahindra','ambulance','Bolero Ambulance'),
  ('tata_motors','ambulance','Winger Ambulance'), ('maruti_suzuki','ambulance','Eeco Ambulance'),
  ('tata_motors','fire_truck','LPT 1613 Fire Tender'), ('ashok_leyland','fire_truck','Ecomet Fire Tender'),
  -- ── Taxi ──
  ('maruti_suzuki','taxi','Dzire Tour S'), ('maruti_suzuki','taxi','Ertiga Tour M'),
  ('toyota','taxi','Innova Crysta Taxi'), ('tata_motors','taxi','Tigor Taxi'),
  ('hyundai','taxi','Aura Taxi'), ('tata_motors','taxi','Xpres-T EV')
) AS m(manufacturer_code, category_code, name)
JOIN vehicle_manufacturers mf ON mf.code = m.manufacturer_code
JOIN vehicle_categories    ct ON ct.code = m.category_code
ON CONFLICT (vehicle_manufacturer_id, vehicle_category_id, code) DO UPDATE
  SET name = EXCLUDED.name, is_active = 1, updated_at = now();

-- 3.6 Category ↔ manufacturer links, derived from the models above so the two
--     can never drift apart. Every brand that makes a model in a category is
--     offered for that category.
INSERT INTO vehicle_category_manufacturers (vehicle_category_id, vehicle_manufacturer_id)
SELECT DISTINCT vehicle_category_id, vehicle_manufacturer_id FROM vehicle_models WHERE is_active = 1
ON CONFLICT DO NOTHING;

-- 3.7 Variants — seeded for the highest-traffic models. Variant stays optional
--     everywhere, so a model without rows here is perfectly usable.
INSERT INTO vehicle_variants (vehicle_model_id, name, code, display_order)
SELECT vm.id, v.name, regexp_replace(lower(v.name), '[^a-z0-9]+', '_', 'g'),
       row_number() OVER (PARTITION BY vm.id ORDER BY v.name) * 10
FROM (VALUES
  ('maruti_suzuki','Swift','LXi'), ('maruti_suzuki','Swift','VXi'), ('maruti_suzuki','Swift','ZXi'), ('maruti_suzuki','Swift','ZXi+'),
  ('maruti_suzuki','Baleno','Sigma'), ('maruti_suzuki','Baleno','Delta'), ('maruti_suzuki','Baleno','Zeta'), ('maruti_suzuki','Baleno','Alpha'),
  ('maruti_suzuki','Dzire','LXi'), ('maruti_suzuki','Dzire','VXi'), ('maruti_suzuki','Dzire','ZXi+'),
  ('maruti_suzuki','Ertiga','LXi'), ('maruti_suzuki','Ertiga','VXi'), ('maruti_suzuki','Ertiga','ZXi+'),
  ('hyundai','i20','Era'), ('hyundai','i20','Magna'), ('hyundai','i20','Sportz'), ('hyundai','i20','Asta'),
  ('hyundai','Creta','E'), ('hyundai','Creta','EX'), ('hyundai','Creta','S'), ('hyundai','Creta','SX'), ('hyundai','Creta','SX(O)'),
  ('hyundai','Venue','E'), ('hyundai','Venue','S'), ('hyundai','Venue','SX'),
  ('tata_motors','Nexon','Smart'), ('tata_motors','Nexon','Pure'), ('tata_motors','Nexon','Creative'), ('tata_motors','Nexon','Fearless'),
  ('tata_motors','Tiago','XE'), ('tata_motors','Tiago','XM'), ('tata_motors','Tiago','XZ+'),
  ('tata_motors','Altroz','XE'), ('tata_motors','Altroz','XM+'), ('tata_motors','Altroz','XZ+'),
  ('mahindra','XUV700','MX'), ('mahindra','XUV700','AX3'), ('mahindra','XUV700','AX5'), ('mahindra','XUV700','AX7'),
  ('mahindra','Thar','AX Opt'), ('mahindra','Thar','LX'),
  ('mahindra','Scorpio N','Z2'), ('mahindra','Scorpio N','Z4'), ('mahindra','Scorpio N','Z8L'),
  ('honda','City','SV'), ('honda','City','V'), ('honda','City','VX'), ('honda','City','ZX'),
  ('honda','Amaze','E'), ('honda','Amaze','S'), ('honda','Amaze','VX'),
  ('toyota','Innova Crysta','GX'), ('toyota','Innova Crysta','VX'), ('toyota','Innova Crysta','ZX'),
  ('toyota','Fortuner','4x2 AT'), ('toyota','Fortuner','Legender'),
  ('kia','Seltos','HTE'), ('kia','Seltos','HTK+'), ('kia','Seltos','HTX'), ('kia','Seltos','GTX+'),
  ('kia','Sonet','HTE'), ('kia','Sonet','HTK+'), ('kia','Sonet','GTX+'),
  ('royal_enfield','Classic 350','Redditch'), ('royal_enfield','Classic 350','Halcyon'),
  ('royal_enfield','Classic 350','Signals'), ('royal_enfield','Classic 350','Chrome'),
  ('royal_enfield','Hunter 350','Retro'), ('royal_enfield','Hunter 350','Metro'), ('royal_enfield','Hunter 350','Metro Rebel'),
  ('honda','Activa 6G','Standard'), ('honda','Activa 6G','Deluxe'), ('honda','Activa 6G','Smart'),
  ('honda','Shine','Drum'), ('honda','Shine','Disc'),
  ('tvs','Jupiter','Sheet Metal'), ('tvs','Jupiter','Drum Alloy'), ('tvs','Jupiter','Disc'), ('tvs','Jupiter','ZX'),
  ('bajaj','Pulsar 150','Neon'), ('bajaj','Pulsar 150','Twin Disc'),
  ('ola_electric','S1 Pro','Gen 2'), ('ola_electric','S1 Pro','Gen 3'),
  ('ather','450X','2.9 kWh'), ('ather','450X','3.7 kWh'),
  ('mahindra','575 DI','XP Plus'), ('mahindra','575 DI','Sarpanch Plus'),
  ('swaraj','744 FE','Standard'), ('swaraj','744 FE','Power Steering'),
  ('tata_motors','Ace Gold','Petrol CX'), ('tata_motors','Ace Gold','Diesel Plus'), ('tata_motors','Ace Gold','CNG Plus'),
  ('jcb','3DX Backhoe Loader','Super'), ('jcb','3DX Backhoe Loader','Xtra'),
  ('tata_motors','Starbus','Skool'), ('tata_motors','Starbus','Ultra')
) AS v(manufacturer_code, model_name, name)
JOIN vehicle_manufacturers mf ON mf.code = v.manufacturer_code
JOIN vehicle_models vm ON vm.vehicle_manufacturer_id = mf.id AND vm.name = v.model_name
ON CONFLICT (vehicle_model_id, code) DO UPDATE
  SET name = EXCLUDED.name, is_active = 1, updated_at = now();

-- 3.8 Model ↔ fuel-type narrowing. Only the unambiguous cases are declared:
--     every electric category is electric-only, and everything else falls back
--     to the full active fuel list at query time.
INSERT INTO vehicle_model_fuel_types (vehicle_model_id, vehicle_fuel_type_id)
SELECT vm.id, ft.id
FROM vehicle_models vm
JOIN vehicle_categories ct ON ct.id = vm.vehicle_category_id AND ct.is_electric = 1
JOIN vehicle_fuel_types ft ON ft.code = 'electric'
ON CONFLICT DO NOTHING;

-- Diesel-only for the heavy/agricultural machines that have no petrol variant.
INSERT INTO vehicle_model_fuel_types (vehicle_model_id, vehicle_fuel_type_id)
SELECT vm.id, ft.id
FROM vehicle_models vm
JOIN vehicle_categories ct ON ct.id = vm.vehicle_category_id
JOIN vehicle_fuel_types ft ON ft.code IN ('diesel', 'cng')
WHERE ct.code IN ('tractor', 'tractor_trailer', 'agri_vehicle', 'construction', 'earthmoving', 'truck')
ON CONFLICT DO NOTHING;

-- 3.9 Registration-number rules --------------------------------------
INSERT INTO vehicle_registration_rules
  (vehicle_type_id, vehicle_category_id, code, pattern, placeholder, help_text, min_length, max_length, is_required, display_order)
VALUES
  -- Global default: permissive on purpose, so a vehicle type added tomorrow is
  -- never blocked by a format nobody has written a rule for yet.
  (NULL, NULL, 'default', '^[A-Z0-9-]{4,20}$', 'MH12AB1234',
   'Letters, digits and hyphens — as printed on the registration plate.', 4, 20, 1, 100)
ON CONFLICT (code) DO UPDATE
  SET pattern = EXCLUDED.pattern, placeholder = EXCLUDED.placeholder,
      help_text = EXCLUDED.help_text, min_length = EXCLUDED.min_length,
      max_length = EXCLUDED.max_length, is_required = EXCLUDED.is_required,
      is_active = 1, updated_at = now();

-- Standard Indian plate (BH-series and older formats included) for road types.
INSERT INTO vehicle_registration_rules
  (vehicle_type_id, vehicle_category_id, code, pattern, placeholder, help_text, min_length, max_length, is_required, display_order)
SELECT t.id, NULL, 'type_' || t.code,
       '^([A-Z]{2}[0-9]{1,2}[A-Z]{0,3}[0-9]{4}|[0-9]{2}BH[0-9]{4}[A-Z]{1,2})$',
       'MH12AB1234',
       'Standard plate format, e.g. MH12AB1234 or a 22BH1234A BH-series number.',
       8, 12, 1, 10
FROM vehicle_types t
WHERE t.code IN ('two_wheeler', 'three_wheeler', 'four_wheeler', 'commercial', 'heavy', 'emergency')
ON CONFLICT (code) DO UPDATE
  SET vehicle_type_id = EXCLUDED.vehicle_type_id, pattern = EXCLUDED.pattern,
      placeholder = EXCLUDED.placeholder, help_text = EXCLUDED.help_text,
      min_length = EXCLUDED.min_length, max_length = EXCLUDED.max_length,
      is_required = EXCLUDED.is_required, is_active = 1, updated_at = now();

-- Off-road machinery: many are registered on a chassis or trailer number, and
-- some construction equipment is never plated at all.
INSERT INTO vehicle_registration_rules
  (vehicle_type_id, vehicle_category_id, code, pattern, placeholder, help_text, min_length, max_length, is_required, display_order)
SELECT NULL, c.id, 'cat_' || c.code,
       '^[A-Z0-9-]{4,24}$', 'MH12AB1234 or chassis no.',
       'Plate, chassis or trailer number — whatever is on the papers.',
       4, 24, 1, 5
FROM vehicle_categories c
WHERE c.code IN ('tractor', 'tractor_trailer', 'agri_vehicle', 'construction', 'earthmoving')
ON CONFLICT (code) DO UPDATE
  SET vehicle_category_id = EXCLUDED.vehicle_category_id, pattern = EXCLUDED.pattern,
      placeholder = EXCLUDED.placeholder, help_text = EXCLUDED.help_text,
      min_length = EXCLUDED.min_length, max_length = EXCLUDED.max_length,
      is_required = EXCLUDED.is_required, is_active = 1, updated_at = now();

-- "Other": we do not know what it is, so we do not pretend to know its format.
INSERT INTO vehicle_registration_rules
  (vehicle_type_id, vehicle_category_id, code, pattern, placeholder, help_text, min_length, max_length, is_required, display_order)
SELECT t.id, NULL, 'type_' || t.code, NULL, 'Registration / chassis number',
       'Any identifier that lets the mechanic recognise the vehicle.', 3, 32, 1, 90
FROM vehicle_types t WHERE t.code = 'other_type'
ON CONFLICT (code) DO UPDATE
  SET vehicle_type_id = EXCLUDED.vehicle_type_id, pattern = EXCLUDED.pattern,
      placeholder = EXCLUDED.placeholder, help_text = EXCLUDED.help_text,
      min_length = EXCLUDED.min_length, max_length = EXCLUDED.max_length,
      is_required = EXCLUDED.is_required, is_active = 1, updated_at = now();


-- ---------------------------------------------------------------------
-- 4. MIGRATE EXISTING VEHICLE ROWS
--    Every pre-existing row is a car, so:
--      make  -> vehicle_manufacturers.name  (with the two legacy aliases)
--      model -> vehicle_models.name         (category taken from the model)
--    Rows that cannot be matched still get Four Wheeler / Car plus their
--    original text preserved in custom_manufacturer / custom_model, so the
--    user's garage never loses a vehicle and nothing 404s.
-- ---------------------------------------------------------------------

-- 4.1 Manufacturer, by exact name or a known legacy alias.
WITH alias(legacy, canonical) AS (
  VALUES ('Tata', 'Tata Motors'), ('MG', 'MG Motor'), ('VW', 'Volkswagen')
)
UPDATE vehicles v
SET vehicle_manufacturer_id = mf.id, updated_at = now()
FROM vehicle_manufacturers mf
LEFT JOIN alias a ON lower(a.canonical) = lower(mf.name)
WHERE v.vehicle_manufacturer_id IS NULL
  AND (lower(mf.name) = lower(v.make) OR lower(a.legacy) = lower(v.make));

-- 4.2 Model within that manufacturer, which also settles the category.
UPDATE vehicles v
SET vehicle_model_id = vm.id,
    vehicle_category_id = vm.vehicle_category_id,
    updated_at = now()
FROM vehicle_models vm
WHERE v.vehicle_model_id IS NULL
  AND v.vehicle_manufacturer_id = vm.vehicle_manufacturer_id
  AND lower(vm.name) = lower(v.model);

-- 4.3 Anything still unmatched: keep the original text and land it on Car.
UPDATE vehicles v
SET vehicle_category_id = COALESCE(v.vehicle_category_id, (SELECT id FROM vehicle_categories WHERE code = 'car')),
    custom_manufacturer = CASE WHEN v.vehicle_manufacturer_id IS NULL THEN v.make ELSE v.custom_manufacturer END,
    custom_model        = CASE WHEN v.vehicle_model_id IS NULL THEN v.model ELSE v.custom_model END,
    updated_at = now()
WHERE v.vehicle_category_id IS NULL
   OR v.vehicle_manufacturer_id IS NULL
   OR v.vehicle_model_id IS NULL;

-- 4.4 Type always follows from the category.
UPDATE vehicles v
SET vehicle_type_id = c.vehicle_type_id, updated_at = now()
FROM vehicle_categories c
WHERE v.vehicle_type_id IS NULL AND v.vehicle_category_id = c.id;

-- 4.5 Normalize registration numbers to the stored form (uppercase, no spaces).
UPDATE vehicles
SET registration_no = upper(replace(replace(registration_no, ' ', ''), '.', '')),
    updated_at = now()
WHERE registration_no <> upper(replace(replace(registration_no, ' ', ''), '.', ''));

COMMIT;

-- ---------------------------------------------------------------------
-- 5. VERIFICATION (read-only — run after the transaction commits)
-- ---------------------------------------------------------------------
-- SELECT COUNT(*) FROM vehicles;                                -- unchanged
-- SELECT COUNT(*) FROM vehicles WHERE vehicle_category_id IS NULL;  -- 0
-- SELECT COUNT(*) FROM service_requests;                        -- unchanged
-- SELECT t.name, COUNT(c.id) FROM vehicle_types t
--   LEFT JOIN vehicle_categories c ON c.vehicle_type_id = t.id GROUP BY t.name;
