-- =====================================================================
-- FixMyRide — Job completion, payment & rating (roadside assistance)
-- Target database : am_user
--
-- Extends the "Find Mechanics Nearby" feature with the closing half of the
-- lifecycle. The same nearby_requests row stays the source of truth; payment
-- and rating hang off it by request id, which is the single key joining
-- Job -> Payment -> Rating.
--
-- The existing `payments` table is NOT reused: its service_request_id is a
-- NOT NULL foreign key into service_requests, and a roadside request is not
-- a service request. A separate table keeps that ledger honest.
--
-- Additive and idempotent.
--   psql -U postgres -h localhost -d am_user -f docs/am_user_nearby_payment_rating.sql
-- =====================================================================

BEGIN;

-- ── nearby_requests: final amount + the extended lifecycle ────────────
ALTER TABLE nearby_requests ADD COLUMN IF NOT EXISTS final_amount NUMERIC(10,2);
ALTER TABLE nearby_requests ADD COLUMN IF NOT EXISTS completed_at  TIMESTAMPTZ;

ALTER TABLE nearby_requests DROP CONSTRAINT IF EXISTS nearby_requests_status_check;
ALTER TABLE nearby_requests ADD  CONSTRAINT nearby_requests_status_check
  CHECK (status IN ('SEARCHING','PENDING_MECHANIC_RESPONSE','ACCEPTED','REJECTED',
                    'MECHANIC_ON_THE_WAY','ARRIVED','IN_SERVICE','COMPLETED',
                    'PAYMENT_PENDING','PAYMENT_COMPLETED','CASH_SELECTED','RATED',
                    'CANCELLED','NO_MECHANIC_FOUND'));

-- The duplicate-request guard covers everything up to and including payment
-- due. Once the customer has paid (or chosen cash) they may raise a fresh
-- roadside request even if they have not rated the previous one yet — an
-- unrated job must never block a breakdown.
DROP INDEX IF EXISTS idx_nearby_requests_one_active;
CREATE UNIQUE INDEX IF NOT EXISTS idx_nearby_requests_one_active
    ON nearby_requests(user_id)
    WHERE status IN ('SEARCHING','PENDING_MECHANIC_RESPONSE','ACCEPTED',
                     'MECHANIC_ON_THE_WAY','ARRIVED','IN_SERVICE','PAYMENT_PENDING');

-- ── Payments ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nearby_payments (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id     INTEGER      NOT NULL REFERENCES nearby_requests(id) ON DELETE CASCADE,
    user_id        INTEGER      NOT NULL REFERENCES users(id)           ON DELETE CASCADE,
    mechanic_id    INTEGER,                       -- cross-module, no FK by design
    amount         NUMERIC(10,2) NOT NULL,
    -- NULL until the customer chooses. Only the two methods the POC supports.
    method         TEXT         CHECK (method IN ('ONLINE','CASH')),
    status         TEXT         NOT NULL DEFAULT 'PENDING'
                   CHECK (status IN ('PENDING','PAID','CASH_SELECTED','FAILED')),
    -- Generated by the payment gateway adapter, never by the UI.
    transaction_id TEXT,
    failure_reason TEXT,
    /* Number of gateway attempts, so a retry after a simulated failure is
       visible rather than silently overwriting the previous attempt. */
    attempts       INTEGER      NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- One payment per request: makes a double-charge structurally impossible.
CREATE UNIQUE INDEX IF NOT EXISTS idx_nearby_payments_request ON nearby_payments(request_id);
CREATE INDEX IF NOT EXISTS idx_nearby_payments_user ON nearby_payments(user_id);

-- ── Ratings ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nearby_ratings (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id  INTEGER     NOT NULL REFERENCES nearby_requests(id) ON DELETE CASCADE,
    user_id     INTEGER     NOT NULL REFERENCES users(id)           ON DELETE CASCADE,
    user_name   TEXT,
    mechanic_id INTEGER     NOT NULL,             -- cross-module, no FK by design
    rating      INTEGER     NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review      TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One rating per completed job. This UNIQUE index — not a UI guard — is what
-- actually prevents a duplicate rating.
CREATE UNIQUE INDEX IF NOT EXISTS idx_nearby_ratings_request ON nearby_ratings(request_id);
CREATE INDEX IF NOT EXISTS idx_nearby_ratings_mechanic ON nearby_ratings(mechanic_id);

COMMIT;
