-- =====================================================================
-- FixMyRide — "Find Mechanics Nearby" (roadside assistance)
-- Target database : am_user
--
-- The user module OWNS the request. The mechanic module keeps a dispatch
-- mirror (docs/am_mech_nearby_requests.sql) and reports its accept/reject
-- decision back, exactly like the existing cross-module mirrors: no foreign
-- key crosses a database boundary.
--
-- Additive and idempotent — safe to run against an already-seeded am_user.
--
--   psql -U postgres -h localhost -d am_user -f docs/am_user_nearby_requests.sql
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS nearby_requests (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference          TEXT        NOT NULL UNIQUE,
    user_id            INTEGER     NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    vehicle_id         INTEGER     REFERENCES vehicles(id)          ON DELETE SET NULL,
    mechanic_id        INTEGER,                    -- cross-module, no FK by design

    -- Vehicle snapshot: the request must stay readable even if the vehicle
    -- row is edited or removed later.
    vehicle_make       TEXT,
    vehicle_model      TEXT,
    vehicle_year       INTEGER,
    vehicle_reg_no     TEXT,

    issue_key          TEXT        NOT NULL,
    issue_label        TEXT        NOT NULL,
    description        TEXT,

    user_lat           NUMERIC(9,6) NOT NULL,
    user_lng           NUMERIC(9,6) NOT NULL,
    user_location_label TEXT,
    location_source    TEXT        NOT NULL DEFAULT 'mock'
                       CHECK (location_source IN ('gps','mock','manual')),

    mechanic_lat       NUMERIC(9,6),
    mechanic_lng       NUMERIC(9,6),
    mechanic_location_label TEXT,

    distance_km        NUMERIC(6,1),
    eta_minutes        INTEGER,
    -- ETA at the moment of acceptance; the live countdown is derived from
    -- this plus accepted_at, so every client agrees without a timer.
    initial_eta_minutes INTEGER,

    price_min          NUMERIC(10,2),
    price_max          NUMERIC(10,2),
    price_currency     TEXT        NOT NULL DEFAULT 'INR',
    price_requires_diagnosis INTEGER NOT NULL DEFAULT 0,

    status             TEXT        NOT NULL DEFAULT 'SEARCHING'
                       CHECK (status IN ('SEARCHING','PENDING_MECHANIC_RESPONSE','ACCEPTED',
                                         'REJECTED','MECHANIC_ON_THE_WAY','ARRIVED','IN_SERVICE',
                                         'COMPLETED','CANCELLED','NO_MECHANIC_FOUND')),
    rejection_reason   TEXT,

    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    accepted_at        TIMESTAMPTZ,
    responded_at       TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_nearby_requests_user   ON nearby_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_nearby_requests_status ON nearby_requests(status);

-- One live request per user: the partial unique index is what makes the
-- "duplicate request" edge case impossible rather than merely unlikely.
CREATE UNIQUE INDEX IF NOT EXISTS idx_nearby_requests_one_active
    ON nearby_requests(user_id)
    WHERE status IN ('SEARCHING','PENDING_MECHANIC_RESPONSE','ACCEPTED',
                     'MECHANIC_ON_THE_WAY','ARRIVED','IN_SERVICE');

COMMIT;
